<a href="https://colab.research.google.com/github/ImVrishank/VecStreetBoys/blob/main/Word2Vec(16th_july).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
!pip install datasets torch.nn torch pyarrow -q

ERROR: Could not find a version that satisfies the requirement torch.nn (from versions: none)
ERROR: No matching distribution found for torch.nn

In [23]:
import numpy as np
import pandas as pd
import dask.dataframe as dd
import re
from collections import Counter
import pandas as pd
import pyarrow.parquet as pq
import pyarrow as pa

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [24]:
splits = {'test': 'wikitext-103-raw-v1/test-00000-of-00001.parquet', 'train': 'wikitext-103-raw-v1/train-*.parquet', 'validation': 'wikitext-103-raw-v1/validation-00000-of-00001.parquet'}
ddf = dd.read_parquet("hf://datasets/Salesforce/wikitext/" + splits["test"])

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

In [25]:
df = ddf.compute()
display(df.head())

                                                text
0
1                               = Robert Boulter =

2
3   Robert Boulter is an English film , televisio...
4   In 2006 , Boulter starred alongside Whishaw i...

Cleaning up this data:

- remove all spl char
- make all rows into a singular corpus of text
- add the unk keyword to extra words
-

In [26]:
# Splitting corpus into words

corpus = df['text'].str.cat(sep=' ')
print(corpus[:500])

  = Robert Boulter =
   Robert Boulter is an English film , television and theatre actor . He had a guest @-@ starring role on the television series The Bill in 2000 . This was followed by a starring role in the play Herons written by Simon Stephens , which was performed in 2001 at the Royal Court Theatre . He had a guest role in the television series Judge John Deed in 2002 . In 2004 Boulter landed a role as " Craig " in the episode " Teddy 's Story " of the television series The Long Firm ; h

In [27]:
# Removing all special chars

corpus = re.sub(r'[^a-zA-Z0-9\s]', '', corpus)
print(corpus[:500])

   Robert Boulter
   Robert Boulter is an English film  television and theatre actor  He had a guest  starring role on the television series The Bill in 2000  This was followed by a starring role in the play Herons written by Simon Stephens  which was performed in 2001 at the Royal Court Theatre  He had a guest role in the television series Judge John Deed in 2002  In 2004 Boulter landed a role as  Craig  in the episode  Teddy s Story  of the television series The Long Firm  he starred alongsi

In [28]:
# Removing Capitalization

corpus = corpus.lower()
print(corpus[:500])

   robert boulter
   robert boulter is an english film  television and theatre actor  he had a guest  starring role on the television series the bill in 2000  this was followed by a starring role in the play herons written by simon stephens  which was performed in 2001 at the royal court theatre  he had a guest role in the television series judge john deed in 2002  in 2004 boulter landed a role as  craig  in the episode  teddy s story  of the television series the long firm  he starred alongsi

In [29]:
# Building the vocabulary (top 5000 words in order of most used)

words = corpus.split()
word_counts = Counter(words)

vocabulary = [word for word, count in word_counts.most_common(5000)]

print(vocabulary[:100])

['the', 'of', 'and', 'in', 'to', 'a', 'was', 'on', 'as', 'that', 'for', 's', 'with', 'by', 'he', 'at', 'his', 'is', 'were', 'from', 'it', 'had', 'an', 'which', 'are', 'be', 'first', 'also', 'this', 'but', 'its', 'after', 'their', 'not', 'two', 'one', 'they', 'have', 'been', 'or', '1', 'during', 'has', 'lesnar', 'when', 'into', 'war', 'time', 'would', 'who', 'all', 'more', 'new', 'only', 'nero', 'north', 'most', 'other', 'three', 'while', 'city', 'him', '2', 'out', 'american', 'tropical', 'there', 'these', 'division', 'later', 'no', 'some', '5', 'film', 'manila', 'up', '3', 'may', 'world', 'made', 'over', 'through', 'year', 'head', 'both', 'her', 'than', 'about', 'british', 'several', 'under', 'before', '000', 'km', 'between', 'game', 'season', 'number', 'against', 'used']

In [ ]:
# Removing all words that arent in vocabulary and replacing with <unk>

words = corpus.split()
processed_words = [word if word in vocabulary else '<unk>' for word in words]
processed_corpus = ' '.join(processed_words)

print(processed_corpus[:500])

robert boulter robert boulter is an english film television and theatre actor he had a guest starring role on the television series the bill in 2000 this was followed by a starring role in the play <unk> written by simon <unk> which was performed in 2001 at the royal court theatre he had a guest role in the television series judge john <unk> in 2002 in 2004 boulter landed a role as craig in the episode <unk> s story of the television series the long <unk> he starred alongside actors mark strong

In [ ]:
# Function to make feature and label vectors

def get_database(corpus, context_len):
  words = corpus.split()
  data = []

  for pointer in range(context_len, len(words) - context_len):
    context = words[pointer - context_len:pointer] + words[pointer + 1:pointer + context_len]
    lable = words[pointer]

    data.append({'context': ' '.join(context), 'label': lable})

  df = pd.DataFrame(data)
  return df

In [ ]:
# Context_window = 5, takes 5 words from before the present and 5 words after the present word
context_window_size = 5
context_df = get_database(processed_corpus, context_window_size)

print(context_df.head())

                                             context       label
0  robert boulter robert boulter is english film ...          an
1  boulter robert boulter is an film television a...     english
2  robert boulter is an english television and th...        film
3    boulter is an english film and theatre actor he  television
4  is an english film television theatre actor he...         and

# One hot Encodings

Now that we have the Context and Label. We need to make one hot vectors for each word. We need to add the one hot vectors element-wise to get the feature vectors and keep the label vector as it is.


# Splitting the Dataset
I needed to split to the dataset into four quarters because:
- I kept running out of memory
- It took a long time, so i did not want to end up losing the entire progress by mistake

In [ ]:
# first quarter

dummy_data = {"Features": np.zeros(len(vocabulary)), "Label": np.zeros(len(vocabulary))}
final_df = pd.DataFrame(dummy_data)
pd.set_option('display.max_colwidth', None)

for i in range(context_df.shape[0] // 4):
  bag_of_words = context_df['context'][i].split()
  label = context_df['label'][i]
  feature_vector = np.zeros(len(vocabulary))
  label_vector = np.zeros(len(vocabulary))

  word_to_index = {word:i for i, word in enumerate(vocabulary)}

  for word in bag_of_words:
    if word in vocabulary:
      feature_vector[word_to_index[word]] = 1

  if label in vocabulary:
    label_vector[word_to_index[label]] = 1

  final_df.loc[len(final_df)] = [feature_vector, label_vector]

  if i%10000 == 0:
    print(f"percentage completed: {100*i/context_df.shape[0]}%")

In [ ]:
# Tiny cleaning up of data.
final_df.drop(index=[i for i in range(0,5001)], inplace=True)

In [ ]:
final_df

In [ ]:
final_df['Features'][5001]

In [ ]:
# I used parquet because it is better for storing large values like this one.

final_df.to_parquet('first_quarter.parquet', engine='pyarrow', index=False, compression='snappy')

In [ ]:
# second quarter

dummy_data = {"Features": np.zeros(len(vocabulary)), "Label": np.zeros(len(vocabulary))}
final_df = pd.DataFrame(dummy_data)


for i in range(context_df.shape[0] // 4, context_df.shape[0] // 2):
  bag_of_words = context_df['context'][i].split()
  label = context_df['label'][i]
  feature_vector = np.zeros(len(vocabulary))
  label_vector = np.zeros(len(vocabulary))

  word_to_index = {word:i for i, word in enumerate(vocabulary)}

  for word in bag_of_words:
    if word in vocabulary:
      feature_vector[word_to_index[word]] = 1

  if label in vocabulary:
    label_vector[word_to_index[label]] = 1

  final_df.loc[len(final_df)] = [feature_vector, label_vector]

  if i%10000 == 0:
    print(f"percentage completed: {100*i/context_df.shape[0]}%")

In [ ]:
final_df.drop(index=[i for i in range(0,5001)], inplace=True)

In [ ]:
final_df

,Features,Label
5001,"[1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...]","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...]"
5002,"[1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...]","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...]"
5003,"[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...]","[0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...]"
5004,"[0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...]","[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...]"
5005,"[1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...]","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...]"
...,...,...
56562,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...]","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...]"
56563,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...]","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...]"
56564,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...]","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...]"
56565,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...]","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...]"
56566,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...]","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...]"

In [ ]:
final_df.to_parquet('second_quarter.parquet', engine='pyarrow', index=False, compression='snappy')

In [ ]:
# third quarter

dummy_data = {"Features": np.zeros(len(vocabulary)), "Label": np.zeros(len(vocabulary))}
final_df = pd.DataFrame(dummy_data)


for i in range(context_df.shape[0] // 2, 3*context_df.shape[0] // 4):
  bag_of_words = context_df['context'][i].split()
  label = context_df['label'][i]
  feature_vector = np.zeros(len(vocabulary))
  label_vector = np.zeros(len(vocabulary))

  word_to_index = {word:i for i, word in enumerate(vocabulary)}

  for word in bag_of_words:
    if word in vocabulary:
      feature_vector[word_to_index[word]] = 1

  if label in vocabulary:
    label_vector[word_to_index[label]] = 1

  final_df.loc[len(final_df)] = [feature_vector, label_vector]

  if i%10000 == 0:
    print(f"percentage completed: {100*i/context_df.shape[0]}%")

In [ ]:
final_df.drop(index=[i for i in range(0,5001)], inplace=True)

In [ ]:
final_df

In [ ]:
final_df.to_parquet('third_quarter.parquet', engine='pyarrow', index=False, compression='snappy')

In [ ]:
# last quarter

dummy_data = {"Features": np.zeros(len(vocabulary)), "Label": np.zeros(len(vocabulary))}
final_df = pd.DataFrame(dummy_data)


for i in range(3 * context_df.shape[0] // 4, context_df.shape[0]):
  bag_of_words = context_df['context'][i].split()
  label = context_df['label'][i]
  feature_vector = np.zeros(len(vocabulary))
  label_vector = np.zeros(len(vocabulary))

  word_to_index = {word:i for i, word in enumerate(vocabulary)}

  for word in bag_of_words:
    if word in vocabulary:
      feature_vector[word_to_index[word]] = 1

  if label in vocabulary:
    label_vector[word_to_index[label]] = 1

  final_df.loc[len(final_df)] = [feature_vector, label_vector]

  if i%10000 == 0:
    print(f"percentage completed: {100*i/context_df.shape[0]}%")

In [ ]:
final_df.drop(index=[i for i in range(0,5001)], inplace=True)

In [ ]:
final_df

In [ ]:
final_df.to_parquet('fourth_quarter.parquet', engine='pyarrow', index=False, compression='snappy')

# Train Test Split
Now that we have the four quarters. We will be using three quarters to train the model and the last quarter as validation dataset.

In [ ]:
# Concatenating the three quarters to make the test dataset

files = ["first_quarter.parquet", "second_quarter.parquet", "third_quarter.parquet"]
output_file = "train_merged.parquet"

writer = None

for file in files:
    print(f"Processing {file}")
    parquet_file = pq.ParquetFile(file)

    for batch in parquet_file.iter_batches(batch_size=2048):  # batch size to that we dont crash session due to lack of RAM
        table = pa.Table.from_batches([batch])
        if writer is None:
            writer = pq.ParquetWriter(output_file, table.schema)
        writer.write_table(table)

if writer:
    writer.close()

print(f"Merged parquet saved at {output_file}")

In [ ]:
pd.read_parquet("train_merged.parquet").shape

# Training
The model is very simple. The specifications of the Word Vectors we want:
- 5000 words in vocabulary
- Each vector having 60 cells
- context size is 5
- Bag of Words model, so we wont need to worry about the order of context words


To acheive this, we use a simple ANN. The ANN has 5000 neurons in the input layer so that it can take in the One-Hot Encodings' summation as input. 60 nurons as the hidden layer. 5000 neurons as the output layer. After softmax we could compare it to the label One-Hot encodings.

In [1]:
# A few issues with newer versions, so swapped back to older versions of these libraries
!pip install torch==2.2.2 torchvision==0.17.2 numpy==1.26 torchaudio==2.2.2 --index-url https://download.pytorch.org/whl/cu121 -qq

ERROR: Could not find a version that satisfies the requirement numpy==1.26 (from versions: 1.26.2, 1.26.3, 2.1.2)
ERROR: No matching distribution found for numpy==1.26

In [2]:
import torch
import torch.nn as nn
import torch.optim as optim
import pandas as pd
import pyarrow.parquet as pq
import numpy as np

In [3]:
class ANN(nn.Module):
    def __init__(self):
        super(ANN, self).__init__()
        self.fc1 = nn.Linear(5000, 60)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(60, 5000)
        # softmax will automatically be applied internally

    def forward(self, x):
        x = self.fc1(x)
        x = self.relu(x)
        x = self.fc2(x)
        return x

In [4]:
def train_model(parquet_file, model, optimizer, criterion, device, epochs=2, batch_size=256):
    parquet = pq.ParquetFile(parquet_file)

    for epoch in range(epochs):
        print(f"Epoch {epoch+1}/{epochs}")
        running_loss = 0.0
        steps = 0

        for batch in parquet.iter_batches(batch_size=batch_size):
            df = batch.to_pandas()

            # Case 1: Data stored as wide table
            if df.shape[1] >= 10000:
                X = torch.tensor(df.iloc[:, :5000].astype("float32").to_numpy(), device=device)
                y_onehot = torch.tensor(df.iloc[:, 5000:].astype("float32").to_numpy(), device=device)

            # Case 2: Data stored as object columns with list per row
            else:
                X = torch.tensor(np.stack(df.iloc[:, 0].values), dtype=torch.float32, device=device)
                y_onehot = torch.tensor(np.stack(df.iloc[:, 1].values), dtype=torch.float32, device=device)

            # Convert one-hot to class indices
            y = torch.argmax(y_onehot, dim=1)

            # Forward + backward passes
            optimizer.zero_grad()
            outputs = model(X)
            loss = criterion(outputs, y)
            loss.backward()
            optimizer.step()

            running_loss += loss.item()
            steps += 1

            if steps % 20 == 0:
                print(f"Step {steps}, Loss: {running_loss/steps:.4f}")

        print(f"Epoch {epoch+1} Loss: {running_loss/steps:.4f}")

In [ ]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = ANN().to(device)

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=1e-3)

train_model("train.parquet", model, optimizer, criterion, device, epochs=50, batch_size=512)

Epoch 1/50
Step 20, Loss: 8.4707
Step 40, Loss: 8.4022
Step 60, Loss: 8.2524
Step 80, Loss: 8.0096
Step 100, Loss: 7.7766
Step 120, Loss: 7.5839
Step 140, Loss: 7.4172
Step 160, Loss: 7.3341
Step 180, Loss: 7.2394
Step 200, Loss: 7.1706
Step 220, Loss: 7.0990
Step 240, Loss: 7.0580
Step 260, Loss: 7.0070
Step 280, Loss: 6.9556
Step 300, Loss: 6.9028
Epoch 1 Loss: 6.8988
Epoch 2/50
Step 20, Loss: 6.0775
Step 40, Loss: 6.1988
Step 60, Loss: 6.2188
Step 80, Loss: 6.1639
Step 100, Loss: 6.1558
Step 120, Loss: 6.1659
Step 140, Loss: 6.1549
Step 160, Loss: 6.1818
Step 180, Loss: 6.1784
Step 200, Loss: 6.1790
Step 220, Loss: 6.1727
Step 240, Loss: 6.1798
Step 260, Loss: 6.1724
Step 280, Loss: 6.1609
Step 300, Loss: 6.1440
Epoch 2 Loss: 6.1451
Epoch 3/50
Step 20, Loss: 5.9102
Step 40, Loss: 6.0572
Step 60, Loss: 6.0868
Step 80, Loss: 6.0399
Step 100, Loss: 6.0300
Step 120, Loss: 6.0407
Step 140, Loss: 6.0308
Step 160, Loss: 6.0471
Step 180, Loss: 6.0421
Step 200, Loss: 6.0386
Step 220, Loss: 6.0340
Step 240, Loss: 6.0366
Step 260, Loss: 6.0286
Step 280, Loss: 6.0174
Step 300, Loss: 5.9997
Epoch 3 Loss: 6.0006
Epoch 4/50
Step 20, Loss: 5.7814
Step 40, Loss: 5.9174
Step 60, Loss: 5.9500
Step 80, Loss: 5.9146
Step 100, Loss: 5.9061
Step 120, Loss: 5.9167
Step 140, Loss: 5.9097
Step 160, Loss: 5.9154
Step 180, Loss: 5.9124
Step 200, Loss: 5.9079
Step 220, Loss: 5.9054
Step 240, Loss: 5.9053
Step 260, Loss: 5.8983
Step 280, Loss: 5.8891
Step 300, Loss: 5.8723
Epoch 4 Loss: 5.8732
Epoch 5/50
Step 20, Loss: 5.6683
Step 40, Loss: 5.7902
Step 60, Loss: 5.8224
Step 80, Loss: 5.7965
Step 100, Loss: 5.7888
Step 120, Loss: 5.7994
Step 140, Loss: 5.7954
Step 160, Loss: 5.7912
Step 180, Loss: 5.7903
Step 200, Loss: 5.7862
Step 220, Loss: 5.7853
Step 240, Loss: 5.7826
Step 260, Loss: 5.7773
Step 280, Loss: 5.7703
Step 300, Loss: 5.7552
Epoch 5 Loss: 5.7559
Epoch 6/50
Step 20, Loss: 5.5643
Step 40, Loss: 5.6712
Step 60, Loss: 5.7008
Step 80, Loss: 5.6825
Step 100, Loss: 5.6742
Step 120, Loss: 5.6841
Step 140, Loss: 5.6836
Step 160, Loss: 5.6706
Step 180, Loss: 5.6716
Step 200, Loss: 5.6686
Step 220, Loss: 5.6691
Step 240, Loss: 5.6641
Step 260, Loss: 5.6605
Step 280, Loss: 5.6557
Step 300, Loss: 5.6427
Epoch 6 Loss: 5.6432
Epoch 7/50
Step 20, Loss: 5.4635
Step 40, Loss: 5.5567
Step 60, Loss: 5.5834
Step 80, Loss: 5.5709
Step 100, Loss: 5.5608
Step 120, Loss: 5.5692
Step 140, Loss: 5.5718
Step 160, Loss: 5.5515
Step 180, Loss: 5.5541
Step 200, Loss: 5.5523
Step 220, Loss: 5.5540
Step 240, Loss: 5.5471
Step 260, Loss: 5.5454
Step 280, Loss: 5.5427
Step 300, Loss: 5.5318
Epoch 7 Loss: 5.5320
Epoch 8/50
Step 20, Loss: 5.3640
Step 40, Loss: 5.4455
Step 60, Loss: 5.4697
Step 80, Loss: 5.4611
Step 100, Loss: 5.4487
Step 120, Loss: 5.4550
Step 140, Loss: 5.4605
Step 160, Loss: 5.4337
Step 180, Loss: 5.4377
Step 200, Loss: 5.4370
Step 220, Loss: 5.4397
Step 240, Loss: 5.4305
Step 260, Loss: 5.4307
Step 280, Loss: 5.4299
Step 300, Loss: 5.4211
Epoch 8 Loss: 5.4210
Epoch 9/50
Step 20, Loss: 5.2625
Step 40, Loss: 5.3356
Step 60, Loss: 5.3584
Step 80, Loss: 5.3527
Step 100, Loss: 5.3378
Step 120, Loss: 5.3418
Step 140, Loss: 5.3497
Step 160, Loss: 5.3171
Step 180, Loss: 5.3220
Step 200, Loss: 5.3222
Step 220, Loss: 5.3258
Step 240, Loss: 5.3142
Step 260, Loss: 5.3160
Step 280, Loss: 5.3170
Step 300, Loss: 5.3102
Epoch 9 Loss: 5.3097
Epoch 10/50
Step 20, Loss: 5.1574
Step 40, Loss: 5.2262
Step 60, Loss: 5.2488
Step 80, Loss: 5.2451
Step 100, Loss: 5.2279
Step 120, Loss: 5.2300
Step 140, Loss: 5.2397
Step 160, Loss: 5.2018
Step 180, Loss: 5.2071
Step 200, Loss: 5.2082
Step 220, Loss: 5.2124
Step 240, Loss: 5.1983
Step 260, Loss: 5.2017
Step 280, Loss: 5.2042
Step 300, Loss: 5.1993
Epoch 10 Loss: 5.1984
Epoch 11/50
Step 20, Loss: 5.0495
Step 40, Loss: 5.1170
Step 60, Loss: 5.1400
Step 80, Loss: 5.1384
Step 100, Loss: 5.1191
Step 120, Loss: 5.1195
Step 140, Loss: 5.1306
Step 160, Loss: 5.0878
Step 180, Loss: 5.0933
Step 200, Loss: 5.0953
Step 220, Loss: 5.1000
Step 240, Loss: 5.0835
Step 260, Loss: 5.0884
Step 280, Loss: 5.0922
Step 300, Loss: 5.0891
Epoch 11 Loss: 5.0876
Epoch 12/50
Step 20, Loss: 4.9403
Step 40, Loss: 5.0084
Step 60, Loss: 5.0321
Step 80, Loss: 5.0329
Step 100, Loss: 5.0117
Step 120, Loss: 5.0111
Step 140, Loss: 5.0230
Step 160, Loss: 4.9760
Step 180, Loss: 4.9814
Step 200, Loss: 4.9843
Step 220, Loss: 4.9894
Step 240, Loss: 4.9707
Step 260, Loss: 4.9769
Step 280, Loss: 4.9818
Step 300, Loss: 4.9804
Epoch 12 Loss: 4.9783
Epoch 13/50
Step 20, Loss: 4.8315
Step 40, Loss: 4.9012
Step 60, Loss: 4.9258
Step 80, Loss: 4.9291
Step 100, Loss: 4.9064
Step 120, Loss: 4.9051
Step 140, Loss: 4.9174
Step 160, Loss: 4.8671
Step 180, Loss: 4.8724
Step 200, Loss: 4.8761
Step 220, Loss: 4.8814
Step 240, Loss: 4.8608
Step 260, Loss: 4.8680
Step 280, Loss: 4.8740
Step 300, Loss: 4.8740
Epoch 13 Loss: 4.8713
Epoch 14/50
Step 20, Loss: 4.7255
Step 40, Loss: 4.7970
Step 60, Loss: 4.8220
Step 80, Loss: 4.8279
Step 100, Loss: 4.8038
Step 120, Loss: 4.8022
Step 140, Loss: 4.8146
Step 160, Loss: 4.7616
Step 180, Loss: 4.7667
Step 200, Loss: 4.7712
Step 220, Loss: 4.7766
Step 240, Loss: 4.7541
Step 260, Loss: 4.7625
Step 280, Loss: 4.7693
Step 300, Loss: 4.7705
Epoch 14 Loss: 4.7672
Epoch 15/50
Step 20, Loss: 4.6233
Step 40, Loss: 4.6965
Step 60, Loss: 4.7221
Step 80, Loss: 4.7305
Step 100, Loss: 4.7049
Step 120, Loss: 4.7033
Step 140, Loss: 4.7156
Step 160, Loss: 4.6605
Step 180, Loss: 4.6653
Step 200, Loss: 4.6704
Step 220, Loss: 4.6758
Step 240, Loss: 4.6517
Step 260, Loss: 4.6611
Step 280, Loss: 4.6685
Step 300, Loss: 4.6708
Epoch 15 Loss: 4.6668
Epoch 16/50
Step 20, Loss: 4.5253
Step 40, Loss: 4.6000
Step 60, Loss: 4.6261
Step 80, Loss: 4.6368
Step 100, Loss: 4.6099
Step 120, Loss: 4.6085
Step 140, Loss: 4.6204
Step 160, Loss: 4.5638
Step 180, Loss: 4.5683
Step 200, Loss: 4.5738
Step 220, Loss: 4.5792
Step 240, Loss: 4.5537
Step 260, Loss: 4.5639
Step 280, Loss: 4.5719
Step 300, Loss: 4.5750
Epoch 16 Loss: 4.5703
Epoch 17/50
Step 20, Loss: 4.4307
Step 40, Loss: 4.5074
Step 60, Loss: 4.5342
Step 80, Loss: 4.5470
Step 100, Loss: 4.5189
Step 120, Loss: 4.5177
Step 140, Loss: 4.5293
Step 160, Loss: 4.4715
Step 180, Loss: 4.4756
Step 200, Loss: 4.4815
Step 220, Loss: 4.4869
Step 240, Loss: 4.4603
Step 260, Loss: 4.4712
Step 280, Loss: 4.4795
Step 300, Loss: 4.4834
Epoch 17 Loss: 4.4781
Epoch 18/50
Step 20, Loss: 4.3396
Step 40, Loss: 4.4188
Step 60, Loss: 4.4466
Step 80, Loss: 4.4613
Step 100, Loss: 4.4321
Step 120, Loss: 4.4310
Step 140, Loss: 4.4422
Step 160, Loss: 4.3836
Step 180, Loss: 4.3874
Step 200, Loss: 4.3936
Step 220, Loss: 4.3989
Step 240, Loss: 4.3714
Step 260, Loss: 4.3830
Step 280, Loss: 4.3916
Step 300, Loss: 4.3962
Epoch 18 Loss: 4.3902
Epoch 19/50
Step 20, Loss: 4.2527
Step 40, Loss: 4.3344
Step 60, Loss: 4.3633
Step 80, Loss: 4.3798
Step 100, Loss: 4.3495
Step 120, Loss: 4.3485
Step 140, Loss: 4.3593
Step 160, Loss: 4.3001
Step 180, Loss: 4.3036
Step 200, Loss: 4.3100
Step 220, Loss: 4.3152
Step 240, Loss: 4.2871
Step 260, Loss: 4.2992
Step 280, Loss: 4.3080
Step 300, Loss: 4.3132
Epoch 19 Loss: 4.3067
Epoch 20/50
Step 20, Loss: 4.1700
Step 40, Loss: 4.2539
Step 60, Loss: 4.2842
Step 80, Loss: 4.3021
Step 100, Loss: 4.2706
Step 120, Loss: 4.2697
Step 140, Loss: 4.2801
Step 160, Loss: 4.2204
Step 180, Loss: 4.2237
Step 200, Loss: 4.2303
Step 220, Loss: 4.2354
Step 240, Loss: 4.2068
Step 260, Loss: 4.2193
Step 280, Loss: 4.2283
Step 300, Loss: 4.2340
Epoch 20 Loss: 4.2270
Epoch 21/50
Step 20, Loss: 4.0917
Step 40, Loss: 4.1776
Step 60, Loss: 4.2091
Step 80, Loss: 4.2283
Step 100, Loss: 4.1958
Step 120, Loss: 4.1949
Step 140, Loss: 4.2050
Step 160, Loss: 4.1450
Step 180, Loss: 4.1481
Step 200, Loss: 4.1548
Step 220, Loss: 4.1598
Step 240, Loss: 4.1308
Step 260, Loss: 4.1437
Step 280, Loss: 4.1528
Step 300, Loss: 4.1590
Epoch 21 Loss: 4.1516
Epoch 22/50
Step 20, Loss: 4.0176
Step 40, Loss: 4.1053
Step 60, Loss: 4.1379
Step 80, Loss: 4.1581
Step 100, Loss: 4.1246
Step 120, Loss: 4.1237
Step 140, Loss: 4.1335
Step 160, Loss: 4.0734
Step 180, Loss: 4.0763
Step 200, Loss: 4.0832
Step 220, Loss: 4.0880
Step 240, Loss: 4.0588
Step 260, Loss: 4.0720
Step 280, Loss: 4.0812
Step 300, Loss: 4.0877
Epoch 22 Loss: 4.0799
Epoch 23/50
Step 20, Loss: 3.9482
Step 40, Loss: 4.0369
Step 60, Loss: 4.0705
Step 80, Loss: 4.0914
Step 100, Loss: 4.0570
Step 120, Loss: 4.0561
Step 140, Loss: 4.0656
Step 160, Loss: 4.0053
Step 180, Loss: 4.0080
Step 200, Loss: 4.0150
Step 220, Loss: 4.0197
Step 240, Loss: 3.9902
Step 260, Loss: 4.0037
Step 280, Loss: 4.0129
Step 300, Loss: 4.0198
Epoch 23 Loss: 4.0117
Epoch 24/50
Step 20, Loss: 3.8829
Step 40, Loss: 3.9723
Step 60, Loss: 4.0065
Step 80, Loss: 4.0279
Step 100, Loss: 3.9927
Step 120, Loss: 3.9918
Step 140, Loss: 4.0010
Step 160, Loss: 3.9407
Step 180, Loss: 3.9432
Step 200, Loss: 3.9503
Step 220, Loss: 3.9549
Step 240, Loss: 3.9252
Step 260, Loss: 3.9388
Step 280, Loss: 3.9480
Step 300, Loss: 3.9553
Epoch 24 Loss: 3.9469
Epoch 25/50
Step 20, Loss: 3.8209
Step 40, Loss: 3.9107
Step 60, Loss: 3.9456
Step 80, Loss: 3.9674
Step 100, Loss: 3.9315
Step 120, Loss: 3.9304
Step 140, Loss: 3.9394
Step 160, Loss: 3.8790
Step 180, Loss: 3.8814
Step 200, Loss: 3.8886
Step 220, Loss: 3.8931
Step 240, Loss: 3.8632
Step 260, Loss: 3.8770
Step 280, Loss: 3.8862
Step 300, Loss: 3.8938
Epoch 25 Loss: 3.8852
Epoch 26/50
Step 20, Loss: 3.7626
Step 40, Loss: 3.8523
Step 60, Loss: 3.8878
Step 80, Loss: 3.9099
Step 100, Loss: 3.8733
Step 120, Loss: 3.8721
Step 140, Loss: 3.8810
Step 160, Loss: 3.8206
Step 180, Loss: 3.8227
Step 200, Loss: 3.8301
Step 220, Loss: 3.8344
Step 240, Loss: 3.8043
Step 260, Loss: 3.8183
Step 280, Loss: 3.8274
Step 300, Loss: 3.8352
Epoch 26 Loss: 3.8264
Epoch 27/50
Step 20, Loss: 3.7069
Step 40, Loss: 3.7968
Step 60, Loss: 3.8328
Step 80, Loss: 3.8550
Step 100, Loss: 3.8176
Step 120, Loss: 3.8163
Step 140, Loss: 3.8250
Step 160, Loss: 3.7646
Step 180, Loss: 3.7666
Step 200, Loss: 3.7741
Step 220, Loss: 3.7783
Step 240, Loss: 3.7481
Step 260, Loss: 3.7622
Step 280, Loss: 3.7712
Step 300, Loss: 3.7793
Epoch 27 Loss: 3.7703
Epoch 28/50
Step 20, Loss: 3.6540
Step 40, Loss: 3.7437
Step 60, Loss: 3.7802
Step 80, Loss: 3.8025
Step 100, Loss: 3.7645
Step 120, Loss: 3.7631
Step 140, Loss: 3.7717
Step 160, Loss: 3.7113
Step 180, Loss: 3.7131
Step 200, Loss: 3.7208
Step 220, Loss: 3.7248
Step 240, Loss: 3.6945
Step 260, Loss: 3.7086
Step 280, Loss: 3.7176
Step 300, Loss: 3.7258
Epoch 28 Loss: 3.7166
Epoch 29/50
Step 20, Loss: 3.6037
Step 40, Loss: 3.6930
Step 60, Loss: 3.7300
Step 80, Loss: 3.7522
Step 100, Loss: 3.7137
Step 120, Loss: 3.7122
Step 140, Loss: 3.7206
Step 160, Loss: 3.6601
Step 180, Loss: 3.6619
Step 200, Loss: 3.6697
Step 220, Loss: 3.6736
Step 240, Loss: 3.6432
Step 260, Loss: 3.6574
Step 280, Loss: 3.6663
Step 300, Loss: 3.6747
Epoch 29 Loss: 3.6653
Epoch 30/50
Step 20, Loss: 3.5554
Step 40, Loss: 3.6445
Step 60, Loss: 3.6818
Step 80, Loss: 3.7041
Step 100, Loss: 3.6650
Step 120, Loss: 3.6634
Step 140, Loss: 3.6717
Step 160, Loss: 3.6113
Step 180, Loss: 3.6130
Step 200, Loss: 3.6209
Step 220, Loss: 3.6247
Step 240, Loss: 3.5942
Step 260, Loss: 3.6084
Step 280, Loss: 3.6171
Step 300, Loss: 3.6257
Epoch 30 Loss: 3.6162
Epoch 31/50
Step 20, Loss: 3.5095
Step 40, Loss: 3.5979
Step 60, Loss: 3.6357
Step 80, Loss: 3.6579
Step 100, Loss: 3.6181
Step 120, Loss: 3.6165
Step 140, Loss: 3.6246
Step 160, Loss: 3.5643
Step 180, Loss: 3.5659
Step 200, Loss: 3.5739
Step 220, Loss: 3.5776
Step 240, Loss: 3.5471
Step 260, Loss: 3.5612
Step 280, Loss: 3.5699
Step 300, Loss: 3.5787
Epoch 31 Loss: 3.5690
Epoch 32/50
Step 20, Loss: 3.4651
Step 40, Loss: 3.5532
Step 60, Loss: 3.5913
Step 80, Loss: 3.6135
Step 100, Loss: 3.5733
Step 120, Loss: 3.5716
Step 140, Loss: 3.5796
Step 160, Loss: 3.5194
Step 180, Loss: 3.5208
Step 200, Loss: 3.5290
Step 220, Loss: 3.5326
Step 240, Loss: 3.5020
Step 260, Loss: 3.5161
Step 280, Loss: 3.5247
Step 300, Loss: 3.5336
Epoch 32 Loss: 3.5238
Epoch 33/50
Step 20, Loss: 3.4229
Step 40, Loss: 3.5105
Step 60, Loss: 3.5488
Step 80, Loss: 3.5708
Step 100, Loss: 3.5301
Step 120, Loss: 3.5283
Step 140, Loss: 3.5361
Step 160, Loss: 3.4760
Step 180, Loss: 3.4774
Step 200, Loss: 3.4858
Step 220, Loss: 3.4893
Step 240, Loss: 3.4586
Step 260, Loss: 3.4727
Step 280, Loss: 3.4811
Step 300, Loss: 3.4901
Epoch 33 Loss: 3.4803
Epoch 34/50
Step 20, Loss: 3.3819
Step 40, Loss: 3.4691
Step 60, Loss: 3.5077
Step 80, Loss: 3.5296
Step 100, Loss: 3.4885
Step 120, Loss: 3.4868
Step 140, Loss: 3.4944
Step 160, Loss: 3.4344
Step 180, Loss: 3.4357
Step 200, Loss: 3.4442
Step 220, Loss: 3.4476
Step 240, Loss: 3.4168
Step 260, Loss: 3.4309
Step 280, Loss: 3.4392
Step 300, Loss: 3.4484
Epoch 34 Loss: 3.4385
Epoch 35/50
Step 20, Loss: 3.3426
Step 40, Loss: 3.4291
Step 60, Loss: 3.4681
Step 80, Loss: 3.4897
Step 100, Loss: 3.4482
Step 120, Loss: 3.4465
Step 140, Loss: 3.4541
Step 160, Loss: 3.3941
Step 180, Loss: 3.3953
Step 200, Loss: 3.4041
Step 220, Loss: 3.4073
Step 240, Loss: 3.3765
Step 260, Loss: 3.3906
Step 280, Loss: 3.3988
Step 300, Loss: 3.4081
Epoch 35 Loss: 3.3981
Epoch 36/50
Step 20, Loss: 3.3048
Step 40, Loss: 3.3908
Step 60, Loss: 3.4299
Step 80, Loss: 3.4513
Step 100, Loss: 3.4096
Step 120, Loss: 3.4079
Step 140, Loss: 3.4153
Step 160, Loss: 3.3555
Step 180, Loss: 3.3566
Step 200, Loss: 3.3655
Step 220, Loss: 3.3687
Step 240, Loss: 3.3378
Step 260, Loss: 3.3518
Step 280, Loss: 3.3599
Step 300, Loss: 3.3693
Epoch 36 Loss: 3.3592
Epoch 37/50
Step 20, Loss: 3.2682
Step 40, Loss: 3.3536
Step 60, Loss: 3.3929
Step 80, Loss: 3.4140
Step 100, Loss: 3.3719
Step 120, Loss: 3.3703
Step 140, Loss: 3.3775
Step 160, Loss: 3.3179
Step 180, Loss: 3.3190
Step 200, Loss: 3.3281
Step 220, Loss: 3.3312
Step 240, Loss: 3.3003
Step 260, Loss: 3.3143
Step 280, Loss: 3.3223
Step 300, Loss: 3.3318
Epoch 37 Loss: 3.3217
Epoch 38/50
Step 20, Loss: 3.2332
Step 40, Loss: 3.3179
Step 60, Loss: 3.3573
Step 80, Loss: 3.3781
Step 100, Loss: 3.3356
Step 120, Loss: 3.3341
Step 140, Loss: 3.3412
Step 160, Loss: 3.2817
Step 180, Loss: 3.2827
Step 200, Loss: 3.2920
Step 220, Loss: 3.2950
Step 240, Loss: 3.2641
Step 260, Loss: 3.2780
Step 280, Loss: 3.2859
Step 300, Loss: 3.2955
Epoch 38 Loss: 3.2853
Epoch 39/50
Step 20, Loss: 3.1991
Step 40, Loss: 3.2834
Step 60, Loss: 3.3229
Step 80, Loss: 3.3434
Step 100, Loss: 3.3004
Step 120, Loss: 3.2990
Step 140, Loss: 3.3059
Step 160, Loss: 3.2466
Step 180, Loss: 3.2476
Step 200, Loss: 3.2570
Step 220, Loss: 3.2600
Step 240, Loss: 3.2291
Step 260, Loss: 3.2430
Step 280, Loss: 3.2508
Step 300, Loss: 3.2605
Epoch 39 Loss: 3.2502
Epoch 40/50
Step 20, Loss: 3.1661
Step 40, Loss: 3.2498
Step 60, Loss: 3.2895
Step 80, Loss: 3.3097
Step 100, Loss: 3.2665
Step 120, Loss: 3.2651
Step 140, Loss: 3.2719
Step 160, Loss: 3.2129
Step 180, Loss: 3.2137
Step 200, Loss: 3.2233
Step 220, Loss: 3.2262
Step 240, Loss: 3.1953
Step 260, Loss: 3.2091
Step 280, Loss: 3.2168
Step 300, Loss: 3.2266
Epoch 40 Loss: 3.2162
Epoch 41/50
Step 20, Loss: 3.1342
Step 40, Loss: 3.2174
Step 60, Loss: 3.2572
Step 80, Loss: 3.2770
Step 100, Loss: 3.2335
Step 120, Loss: 3.2322
Step 140, Loss: 3.2389
Step 160, Loss: 3.1801
Step 180, Loss: 3.1809
Step 200, Loss: 3.1906
Step 220, Loss: 3.1934
Step 240, Loss: 3.1625
Step 260, Loss: 3.1763
Step 280, Loss: 3.1838
Step 300, Loss: 3.1936
Epoch 41 Loss: 3.1833
Epoch 42/50
Step 20, Loss: 3.1032
Step 40, Loss: 3.1858
Step 60, Loss: 3.2257
Step 80, Loss: 3.2452
Step 100, Loss: 3.2015
Step 120, Loss: 3.2004
Step 140, Loss: 3.2069
Step 160, Loss: 3.1483
Step 180, Loss: 3.1490
Step 200, Loss: 3.1589
Step 220, Loss: 3.1617
Step 240, Loss: 3.1308
Step 260, Loss: 3.1445
Step 280, Loss: 3.1519
Step 300, Loss: 3.1618
Epoch 42 Loss: 3.1514
Epoch 43/50
Step 20, Loss: 3.0730
Step 40, Loss: 3.1553
Step 60, Loss: 3.1954
Step 80, Loss: 3.2145
Step 100, Loss: 3.1705
Step 120, Loss: 3.1695
Step 140, Loss: 3.1759
Step 160, Loss: 3.1175
Step 180, Loss: 3.1182
Step 200, Loss: 3.1282
Step 220, Loss: 3.1310
Step 240, Loss: 3.1000
Step 260, Loss: 3.1137
Step 280, Loss: 3.1209
Step 300, Loss: 3.1309
Epoch 43 Loss: 3.1205
Epoch 44/50
Step 20, Loss: 3.0441
Step 40, Loss: 3.1258
Step 60, Loss: 3.1659
Step 80, Loss: 3.1847
Step 100, Loss: 3.1404
Step 120, Loss: 3.1396
Step 140, Loss: 3.1459
Step 160, Loss: 3.0877
Step 180, Loss: 3.0883
Step 200, Loss: 3.0985
Step 220, Loss: 3.1011
Step 240, Loss: 3.0702
Step 260, Loss: 3.0838
Step 280, Loss: 3.0909
Step 300, Loss: 3.1009
Epoch 44 Loss: 3.0905
Epoch 45/50
Step 20, Loss: 3.0161
Step 40, Loss: 3.0973
Step 60, Loss: 3.1374
Step 80, Loss: 3.1558
Step 100, Loss: 3.1112
Step 120, Loss: 3.1106
Step 140, Loss: 3.1167
Step 160, Loss: 3.0588
Step 180, Loss: 3.0593
Step 200, Loss: 3.0696
Step 220, Loss: 3.0722
Step 240, Loss: 3.0413
Step 260, Loss: 3.0549
Step 280, Loss: 3.0619
Step 300, Loss: 3.0719
Epoch 45 Loss: 3.0615
Epoch 46/50
Step 20, Loss: 2.9888
Step 40, Loss: 3.0694
Step 60, Loss: 3.1096
Step 80, Loss: 3.1277
Step 100, Loss: 3.0829
Step 120, Loss: 3.0824
Step 140, Loss: 3.0883
Step 160, Loss: 3.0307
Step 180, Loss: 3.0311
Step 200, Loss: 3.0416
Step 220, Loss: 3.0441
Step 240, Loss: 3.0131
Step 260, Loss: 3.0267
Step 280, Loss: 3.0335
Step 300, Loss: 3.0436
Epoch 46 Loss: 3.0331
Epoch 47/50
Step 20, Loss: 2.9624
Step 40, Loss: 3.0427
Step 60, Loss: 3.0829
Step 80, Loss: 3.1006
Step 100, Loss: 3.0555
Step 120, Loss: 3.0551
Step 140, Loss: 3.0609
Step 160, Loss: 3.0035
Step 180, Loss: 3.0039
Step 200, Loss: 3.0144
Step 220, Loss: 3.0168
Step 240, Loss: 2.9859
Step 260, Loss: 2.9994
Step 280, Loss: 3.0061
Step 300, Loss: 3.0162
Epoch 47 Loss: 3.0058
Epoch 48/50
Step 20, Loss: 2.9368
Step 40, Loss: 3.0166
Step 60, Loss: 3.0568
Step 80, Loss: 3.0741
Step 100, Loss: 3.0288
Step 120, Loss: 3.0285
Step 140, Loss: 3.0341
Step 160, Loss: 2.9770
Step 180, Loss: 2.9773
Step 200, Loss: 2.9879
Step 220, Loss: 2.9903
Step 240, Loss: 2.9594
Step 260, Loss: 2.9728
Step 280, Loss: 2.9794
Step 300, Loss: 2.9895
Epoch 48 Loss: 2.9790
Epoch 49/50
Step 20, Loss: 2.9123
Step 40, Loss: 2.9915
Step 60, Loss: 3.0317
Step 80, Loss: 3.0487
Step 100, Loss: 3.0029
Step 120, Loss: 3.0028
Step 140, Loss: 3.0083
Step 160, Loss: 2.9514
Step 180, Loss: 2.9516
Step 200, Loss: 2.9623
Step 220, Loss: 2.9647
Step 240, Loss: 2.9338
Step 260, Loss: 2.9472
Step 280, Loss: 2.9536
Step 300, Loss: 2.9637
Epoch 49 Loss: 2.9533
Epoch 50/50
Step 20, Loss: 2.8878
Step 40, Loss: 2.9667
Step 60, Loss: 3.0070
Step 80, Loss: 3.0236
Step 100, Loss: 2.9777
Step 120, Loss: 2.9777
Step 140, Loss: 2.9831
Step 160, Loss: 2.9264
Step 180, Loss: 2.9265
Step 200, Loss: 2.9373
Step 220, Loss: 2.9396
Step 240, Loss: 2.9087
Step 260, Loss: 2.9221
Step 280, Loss: 2.9284
Step 300, Loss: 2.9385
Epoch 50 Loss: 2.9280

In [ ]:
# Saving checkpoint after 50 epochs(not neccessary, but i was afraid of losing data)
checkpoint = {
    "epoch": 50,
    "model_state": model.state_dict(),
    "optimizer_state": optimizer.state_dict()
}
torch.save(checkpoint, "model_checkpoint.pth")

In [ ]:
# Continuing training with the model we had before
checkpoint = torch.load("model_checkpoint.pth", map_location=device)

model.load_state_dict(checkpoint["model_state"])
optimizer.load_state_dict(checkpoint["optimizer_state"])

start_epoch = checkpoint["epoch"]
print(f"Resuming from epoch {start_epoch}")

Resuming from epoch 50

In [ ]:
# Since we already have a low loss, we could reduce learning rate to reach the minima easily and not bounce aorund
for g in optimizer.param_groups:
    g['lr'] = 1e-4 # from 1e-3

In [ ]:
train_model("train.parquet", model, optimizer, criterion, device, epochs=50, batch_size=512)

Epoch 1/50
Step 20, Loss: 2.8044
Step 40, Loss: 2.8766
Step 60, Loss: 2.9145
Step 80, Loss: 2.9293
Step 100, Loss: 2.8815
Step 120, Loss: 2.8782
Step 140, Loss: 2.8800
Step 160, Loss: 2.8242
Step 180, Loss: 2.8235
Step 200, Loss: 2.8345
Step 220, Loss: 2.8343
Step 240, Loss: 2.8024
Step 260, Loss: 2.8134
Step 280, Loss: 2.8173
Step 300, Loss: 2.8266
Epoch 1 Loss: 2.8167
Epoch 2/50
Step 20, Loss: 2.7999
Step 40, Loss: 2.8729
Step 60, Loss: 2.9123
Step 80, Loss: 2.9280
Step 100, Loss: 2.8803
Step 120, Loss: 2.8771
Step 140, Loss: 2.8787
Step 160, Loss: 2.8223
Step 180, Loss: 2.8210
Step 200, Loss: 2.8316
Step 220, Loss: 2.8312
Step 240, Loss: 2.7991
Step 260, Loss: 2.8100
Step 280, Loss: 2.8139
Step 300, Loss: 2.8233
Epoch 2 Loss: 2.8133
Epoch 3/50
Step 20, Loss: 2.7957
Step 40, Loss: 2.8688
Step 60, Loss: 2.9086
Step 80, Loss: 2.9245
Step 100, Loss: 2.8769
Step 120, Loss: 2.8738
Step 140, Loss: 2.8756
Step 160, Loss: 2.8190
Step 180, Loss: 2.8176
Step 200, Loss: 2.8281
Step 220, Loss: 2.8277
Step 240, Loss: 2.7956
Step 260, Loss: 2.8065
Step 280, Loss: 2.8105
Step 300, Loss: 2.8199
Epoch 3 Loss: 2.8100
Epoch 4/50
Step 20, Loss: 2.7916
Step 40, Loss: 2.8647
Step 60, Loss: 2.9046
Step 80, Loss: 2.9207
Step 100, Loss: 2.8732
Step 120, Loss: 2.8703
Step 140, Loss: 2.8721
Step 160, Loss: 2.8156
Step 180, Loss: 2.8140
Step 200, Loss: 2.8245
Step 220, Loss: 2.8241
Step 240, Loss: 2.7922
Step 260, Loss: 2.8031
Step 280, Loss: 2.8072
Step 300, Loss: 2.8166
Epoch 4 Loss: 2.8067
Epoch 5/50
Step 20, Loss: 2.7875
Step 40, Loss: 2.8606
Step 60, Loss: 2.9007
Step 80, Loss: 2.9169
Step 100, Loss: 2.8694
Step 120, Loss: 2.8666
Step 140, Loss: 2.8686
Step 160, Loss: 2.8121
Step 180, Loss: 2.8105
Step 200, Loss: 2.8210
Step 220, Loss: 2.8207
Step 240, Loss: 2.7888
Step 260, Loss: 2.7998
Step 280, Loss: 2.8039
Step 300, Loss: 2.8134
Epoch 5 Loss: 2.8034
Epoch 6/50
Step 20, Loss: 2.7837
Step 40, Loss: 2.8566
Step 60, Loss: 2.8970
Step 80, Loss: 2.9132
Step 100, Loss: 2.8658
Step 120, Loss: 2.8631
Step 140, Loss: 2.8651
Step 160, Loss: 2.8087
Step 180, Loss: 2.8071
Step 200, Loss: 2.8176
Step 220, Loss: 2.8174
Step 240, Loss: 2.7855
Step 260, Loss: 2.7965
Step 280, Loss: 2.8008
Step 300, Loss: 2.8103
Epoch 6 Loss: 2.8003
Epoch 7/50
Step 20, Loss: 2.7799
Step 40, Loss: 2.8528
Step 60, Loss: 2.8933
Step 80, Loss: 2.9096
Step 100, Loss: 2.8622
Step 120, Loss: 2.8597
Step 140, Loss: 2.8617
Step 160, Loss: 2.8054
Step 180, Loss: 2.8038
Step 200, Loss: 2.8144
Step 220, Loss: 2.8141
Step 240, Loss: 2.7823
Step 260, Loss: 2.7934
Step 280, Loss: 2.7977
Step 300, Loss: 2.8072
Epoch 7 Loss: 2.7972
Epoch 8/50
Step 20, Loss: 2.7763
Step 40, Loss: 2.8492
Step 60, Loss: 2.8898
Step 80, Loss: 2.9061
Step 100, Loss: 2.8587
Step 120, Loss: 2.8563
Step 140, Loss: 2.8584
Step 160, Loss: 2.8021
Step 180, Loss: 2.8005
Step 200, Loss: 2.8111
Step 220, Loss: 2.8109
Step 240, Loss: 2.7792
Step 260, Loss: 2.7903
Step 280, Loss: 2.7946
Step 300, Loss: 2.8042
Epoch 8 Loss: 2.7942
Epoch 9/50
Step 20, Loss: 2.7728
Step 40, Loss: 2.8456
Step 60, Loss: 2.8864
Step 80, Loss: 2.9027
Step 100, Loss: 2.8553
Step 120, Loss: 2.8530
Step 140, Loss: 2.8551
Step 160, Loss: 2.7989
Step 180, Loss: 2.7974
Step 200, Loss: 2.8080
Step 220, Loss: 2.8078
Step 240, Loss: 2.7761
Step 260, Loss: 2.7872
Step 280, Loss: 2.7916
Step 300, Loss: 2.8012
Epoch 9 Loss: 2.7912
Epoch 10/50
Step 20, Loss: 2.7694
Step 40, Loss: 2.8422
Step 60, Loss: 2.8830
Step 80, Loss: 2.8994
Step 100, Loss: 2.8520
Step 120, Loss: 2.8497
Step 140, Loss: 2.8519
Step 160, Loss: 2.7958
Step 180, Loss: 2.7942
Step 200, Loss: 2.8049
Step 220, Loss: 2.8047
Step 240, Loss: 2.7731
Step 260, Loss: 2.7843
Step 280, Loss: 2.7887
Step 300, Loss: 2.7983
Epoch 10 Loss: 2.7883
Epoch 11/50
Step 20, Loss: 2.7661
Step 40, Loss: 2.8388
Step 60, Loss: 2.8797
Step 80, Loss: 2.8961
Step 100, Loss: 2.8488
Step 120, Loss: 2.8465
Step 140, Loss: 2.8488
Step 160, Loss: 2.7927
Step 180, Loss: 2.7912
Step 200, Loss: 2.8019
Step 220, Loss: 2.8017
Step 240, Loss: 2.7701
Step 260, Loss: 2.7813
Step 280, Loss: 2.7858
Step 300, Loss: 2.7954
Epoch 11 Loss: 2.7854
Epoch 12/50
Step 20, Loss: 2.7628
Step 40, Loss: 2.8355
Step 60, Loss: 2.8765
Step 80, Loss: 2.8929
Step 100, Loss: 2.8456
Step 120, Loss: 2.8434
Step 140, Loss: 2.8457
Step 160, Loss: 2.7897
Step 180, Loss: 2.7881
Step 200, Loss: 2.7989
Step 220, Loss: 2.7988
Step 240, Loss: 2.7672
Step 260, Loss: 2.7785
Step 280, Loss: 2.7829
Step 300, Loss: 2.7926
Epoch 12 Loss: 2.7826
Epoch 13/50
Step 20, Loss: 2.7596
Step 40, Loss: 2.8323
Step 60, Loss: 2.8734
Step 80, Loss: 2.8898
Step 100, Loss: 2.8424
Step 120, Loss: 2.8403
Step 140, Loss: 2.8427
Step 160, Loss: 2.7867
Step 180, Loss: 2.7852
Step 200, Loss: 2.7959
Step 220, Loss: 2.7959
Step 240, Loss: 2.7643
Step 260, Loss: 2.7756
Step 280, Loss: 2.7801
Step 300, Loss: 2.7897
Epoch 13 Loss: 2.7798
Epoch 14/50
Step 20, Loss: 2.7565
Step 40, Loss: 2.8291
Step 60, Loss: 2.8703
Step 80, Loss: 2.8867
Step 100, Loss: 2.8393
Step 120, Loss: 2.8373
Step 140, Loss: 2.8397
Step 160, Loss: 2.7838
Step 180, Loss: 2.7822
Step 200, Loss: 2.7930
Step 220, Loss: 2.7930
Step 240, Loss: 2.7615
Step 260, Loss: 2.7728
Step 280, Loss: 2.7773
Step 300, Loss: 2.7870
Epoch 14 Loss: 2.7770
Epoch 15/50
Step 20, Loss: 2.7534
Step 40, Loss: 2.8260
Step 60, Loss: 2.8672
Step 80, Loss: 2.8836
Step 100, Loss: 2.8363
Step 120, Loss: 2.8343
Step 140, Loss: 2.8367
Step 160, Loss: 2.7809
Step 180, Loss: 2.7793
Step 200, Loss: 2.7902
Step 220, Loss: 2.7901
Step 240, Loss: 2.7587
Step 260, Loss: 2.7700
Step 280, Loss: 2.7746
Step 300, Loss: 2.7842
Epoch 15 Loss: 2.7742
Epoch 16/50
Step 20, Loss: 2.7504
Step 40, Loss: 2.8230
Step 60, Loss: 2.8642
Step 80, Loss: 2.8806
Step 100, Loss: 2.8333
Step 120, Loss: 2.8314
Step 140, Loss: 2.8338
Step 160, Loss: 2.7780
Step 180, Loss: 2.7765
Step 200, Loss: 2.7873
Step 220, Loss: 2.7873
Step 240, Loss: 2.7559
Step 260, Loss: 2.7672
Step 280, Loss: 2.7718
Step 300, Loss: 2.7815
Epoch 16 Loss: 2.7715
Epoch 17/50
Step 20, Loss: 2.7474
Step 40, Loss: 2.8200
Step 60, Loss: 2.8613
Step 80, Loss: 2.8777
Step 100, Loss: 2.8303
Step 120, Loss: 2.8284
Step 140, Loss: 2.8309
Step 160, Loss: 2.7752
Step 180, Loss: 2.7736
Step 200, Loss: 2.7845
Step 220, Loss: 2.7845
Step 240, Loss: 2.7531
Step 260, Loss: 2.7645
Step 280, Loss: 2.7691
Step 300, Loss: 2.7788
Epoch 17 Loss: 2.7688
Epoch 18/50
Step 20, Loss: 2.7445
Step 40, Loss: 2.8170
Step 60, Loss: 2.8584
Step 80, Loss: 2.8748
Step 100, Loss: 2.8273
Step 120, Loss: 2.8256
Step 140, Loss: 2.8280
Step 160, Loss: 2.7724
Step 180, Loss: 2.7709
Step 200, Loss: 2.7818
Step 220, Loss: 2.7818
Step 240, Loss: 2.7504
Step 260, Loss: 2.7618
Step 280, Loss: 2.7664
Step 300, Loss: 2.7761
Epoch 18 Loss: 2.7661
Epoch 19/50
Step 20, Loss: 2.7415
Step 40, Loss: 2.8140
Step 60, Loss: 2.8555
Step 80, Loss: 2.8719
Step 100, Loss: 2.8244
Step 120, Loss: 2.8227
Step 140, Loss: 2.8252
Step 160, Loss: 2.7696
Step 180, Loss: 2.7681
Step 200, Loss: 2.7790
Step 220, Loss: 2.7791
Step 240, Loss: 2.7477
Step 260, Loss: 2.7591
Step 280, Loss: 2.7638
Step 300, Loss: 2.7734
Epoch 19 Loss: 2.7635
Epoch 20/50
Step 20, Loss: 2.7387
Step 40, Loss: 2.8111
Step 60, Loss: 2.8526
Step 80, Loss: 2.8690
Step 100, Loss: 2.8216
Step 120, Loss: 2.8199
Step 140, Loss: 2.8224
Step 160, Loss: 2.7668
Step 180, Loss: 2.7653
Step 200, Loss: 2.7763
Step 220, Loss: 2.7764
Step 240, Loss: 2.7451
Step 260, Loss: 2.7565
Step 280, Loss: 2.7611
Step 300, Loss: 2.7708
Epoch 20 Loss: 2.7608
Epoch 21/50
Step 20, Loss: 2.7358
Step 40, Loss: 2.8083
Step 60, Loss: 2.8498
Step 80, Loss: 2.8662
Step 100, Loss: 2.8187
Step 120, Loss: 2.8171
Step 140, Loss: 2.8196
Step 160, Loss: 2.7641
Step 180, Loss: 2.7626
Step 200, Loss: 2.7736
Step 220, Loss: 2.7737
Step 240, Loss: 2.7424
Step 260, Loss: 2.7538
Step 280, Loss: 2.7585
Step 300, Loss: 2.7682
Epoch 21 Loss: 2.7582
Epoch 22/50
Step 20, Loss: 2.7330
Step 40, Loss: 2.8054
Step 60, Loss: 2.8470
Step 80, Loss: 2.8634
Step 100, Loss: 2.8159
Step 120, Loss: 2.8143
Step 140, Loss: 2.8168
Step 160, Loss: 2.7614
Step 180, Loss: 2.7599
Step 200, Loss: 2.7709
Step 220, Loss: 2.7710
Step 240, Loss: 2.7398
Step 260, Loss: 2.7512
Step 280, Loss: 2.7559
Step 300, Loss: 2.7656
Epoch 22 Loss: 2.7556
Epoch 23/50
Step 20, Loss: 2.7302
Step 40, Loss: 2.8026
Step 60, Loss: 2.8442
Step 80, Loss: 2.8606
Step 100, Loss: 2.8131
Step 120, Loss: 2.8116
Step 140, Loss: 2.8141
Step 160, Loss: 2.7587
Step 180, Loss: 2.7572
Step 200, Loss: 2.7683
Step 220, Loss: 2.7684
Step 240, Loss: 2.7372
Step 260, Loss: 2.7486
Step 280, Loss: 2.7533
Step 300, Loss: 2.7630
Epoch 23 Loss: 2.7530
Epoch 24/50
Step 20, Loss: 2.7275
Step 40, Loss: 2.7998
Step 60, Loss: 2.8415
Step 80, Loss: 2.8579
Step 100, Loss: 2.8103
Step 120, Loss: 2.8089
Step 140, Loss: 2.8114
Step 160, Loss: 2.7560
Step 180, Loss: 2.7546
Step 200, Loss: 2.7656
Step 220, Loss: 2.7658
Step 240, Loss: 2.7346
Step 260, Loss: 2.7460
Step 280, Loss: 2.7507
Step 300, Loss: 2.7604
Epoch 24 Loss: 2.7505
Epoch 25/50
Step 20, Loss: 2.7247
Step 40, Loss: 2.7971
Step 60, Loss: 2.8388
Step 80, Loss: 2.8552
Step 100, Loss: 2.8076
Step 120, Loss: 2.8061
Step 140, Loss: 2.8087
Step 160, Loss: 2.7534
Step 180, Loss: 2.7519
Step 200, Loss: 2.7630
Step 220, Loss: 2.7632
Step 240, Loss: 2.7320
Step 260, Loss: 2.7435
Step 280, Loss: 2.7482
Step 300, Loss: 2.7579
Epoch 25 Loss: 2.7479
Epoch 26/50
Step 20, Loss: 2.7221
Step 40, Loss: 2.7944
Step 60, Loss: 2.8361
Step 80, Loss: 2.8525
Step 100, Loss: 2.8049
Step 120, Loss: 2.8035
Step 140, Loss: 2.8060
Step 160, Loss: 2.7508
Step 180, Loss: 2.7493
Step 200, Loss: 2.7604
Step 220, Loss: 2.7606
Step 240, Loss: 2.7294
Step 260, Loss: 2.7409
Step 280, Loss: 2.7456
Step 300, Loss: 2.7553
Epoch 26 Loss: 2.7454
Epoch 27/50
Step 20, Loss: 2.7194
Step 40, Loss: 2.7917
Step 60, Loss: 2.8334
Step 80, Loss: 2.8498
Step 100, Loss: 2.8022
Step 120, Loss: 2.8008
Step 140, Loss: 2.8034
Step 160, Loss: 2.7482
Step 180, Loss: 2.7467
Step 200, Loss: 2.7578
Step 220, Loss: 2.7580
Step 240, Loss: 2.7269
Step 260, Loss: 2.7384
Step 280, Loss: 2.7431
Step 300, Loss: 2.7528
Epoch 27 Loss: 2.7429
Epoch 28/50
Step 20, Loss: 2.7167
Step 40, Loss: 2.7890
Step 60, Loss: 2.8308
Step 80, Loss: 2.8471
Step 100, Loss: 2.7995
Step 120, Loss: 2.7982
Step 140, Loss: 2.8007
Step 160, Loss: 2.7456
Step 180, Loss: 2.7441
Step 200, Loss: 2.7553
Step 220, Loss: 2.7555
Step 240, Loss: 2.7244
Step 260, Loss: 2.7359
Step 280, Loss: 2.7406
Step 300, Loss: 2.7503
Epoch 28 Loss: 2.7404
Epoch 29/50
Step 20, Loss: 2.7141
Step 40, Loss: 2.7863
Step 60, Loss: 2.8282
Step 80, Loss: 2.8445
Step 100, Loss: 2.7968
Step 120, Loss: 2.7955
Step 140, Loss: 2.7981
Step 160, Loss: 2.7430
Step 180, Loss: 2.7416
Step 200, Loss: 2.7527
Step 220, Loss: 2.7529
Step 240, Loss: 2.7218
Step 260, Loss: 2.7334
Step 280, Loss: 2.7381
Step 300, Loss: 2.7478
Epoch 29 Loss: 2.7379
Epoch 30/50
Step 20, Loss: 2.7115
Step 40, Loss: 2.7837
Step 60, Loss: 2.8256
Step 80, Loss: 2.8419
Step 100, Loss: 2.7942
Step 120, Loss: 2.7929
Step 140, Loss: 2.7955
Step 160, Loss: 2.7405
Step 180, Loss: 2.7390
Step 200, Loss: 2.7502
Step 220, Loss: 2.7504
Step 240, Loss: 2.7193
Step 260, Loss: 2.7309
Step 280, Loss: 2.7356
Step 300, Loss: 2.7454
Epoch 30 Loss: 2.7354
Epoch 31/50
Step 20, Loss: 2.7089
Step 40, Loss: 2.7811
Step 60, Loss: 2.8230
Step 80, Loss: 2.8393
Step 100, Loss: 2.7916
Step 120, Loss: 2.7904
Step 140, Loss: 2.7929
Step 160, Loss: 2.7379
Step 180, Loss: 2.7365
Step 200, Loss: 2.7477
Step 220, Loss: 2.7479
Step 240, Loss: 2.7169
Step 260, Loss: 2.7284
Step 280, Loss: 2.7332
Step 300, Loss: 2.7429
Epoch 31 Loss: 2.7329
Epoch 32/50
Step 20, Loss: 2.7063
Step 40, Loss: 2.7785
Step 60, Loss: 2.8204
Step 80, Loss: 2.8367
Step 100, Loss: 2.7890
Step 120, Loss: 2.7878
Step 140, Loss: 2.7904
Step 160, Loss: 2.7354
Step 180, Loss: 2.7340
Step 200, Loss: 2.7452
Step 220, Loss: 2.7454
Step 240, Loss: 2.7144
Step 260, Loss: 2.7260
Step 280, Loss: 2.7307
Step 300, Loss: 2.7404
Epoch 32 Loss: 2.7305
Epoch 33/50
Step 20, Loss: 2.7037
Step 40, Loss: 2.7759
Step 60, Loss: 2.8179
Step 80, Loss: 2.8341
Step 100, Loss: 2.7864
Step 120, Loss: 2.7852
Step 140, Loss: 2.7878
Step 160, Loss: 2.7329
Step 180, Loss: 2.7315
Step 200, Loss: 2.7427
Step 220, Loss: 2.7429
Step 240, Loss: 2.7119
Step 260, Loss: 2.7235
Step 280, Loss: 2.7282
Step 300, Loss: 2.7380
Epoch 33 Loss: 2.7280
Epoch 34/50
Step 20, Loss: 2.7012
Step 40, Loss: 2.7733
Step 60, Loss: 2.8153
Step 80, Loss: 2.8316
Step 100, Loss: 2.7838
Step 120, Loss: 2.7827
Step 140, Loss: 2.7853
Step 160, Loss: 2.7304
Step 180, Loss: 2.7290
Step 200, Loss: 2.7402
Step 220, Loss: 2.7405
Step 240, Loss: 2.7095
Step 260, Loss: 2.7211
Step 280, Loss: 2.7258
Step 300, Loss: 2.7356
Epoch 34 Loss: 2.7256
Epoch 35/50
Step 20, Loss: 2.6987
Step 40, Loss: 2.7708
Step 60, Loss: 2.8128
Step 80, Loss: 2.8291
Step 100, Loss: 2.7813
Step 120, Loss: 2.7802
Step 140, Loss: 2.7828
Step 160, Loss: 2.7280
Step 180, Loss: 2.7265
Step 200, Loss: 2.7378
Step 220, Loss: 2.7380
Step 240, Loss: 2.7071
Step 260, Loss: 2.7187
Step 280, Loss: 2.7234
Step 300, Loss: 2.7332
Epoch 35 Loss: 2.7232
Epoch 36/50
Step 20, Loss: 2.6962
Step 40, Loss: 2.7682
Step 60, Loss: 2.8103
Step 80, Loss: 2.8265
Step 100, Loss: 2.7787
Step 120, Loss: 2.7777
Step 140, Loss: 2.7803
Step 160, Loss: 2.7255
Step 180, Loss: 2.7240
Step 200, Loss: 2.7353
Step 220, Loss: 2.7356
Step 240, Loss: 2.7046
Step 260, Loss: 2.7162
Step 280, Loss: 2.7210
Step 300, Loss: 2.7307
Epoch 36 Loss: 2.7208
Epoch 37/50
Step 20, Loss: 2.6937
Step 40, Loss: 2.7657
Step 60, Loss: 2.8078
Step 80, Loss: 2.8240
Step 100, Loss: 2.7762
Step 120, Loss: 2.7752
Step 140, Loss: 2.7778
Step 160, Loss: 2.7230
Step 180, Loss: 2.7216
Step 200, Loss: 2.7329
Step 220, Loss: 2.7331
Step 240, Loss: 2.7022
Step 260, Loss: 2.7138
Step 280, Loss: 2.7186
Step 300, Loss: 2.7283
Epoch 37 Loss: 2.7184
Epoch 38/50
Step 20, Loss: 2.6912
Step 40, Loss: 2.7632
Step 60, Loss: 2.8054
Step 80, Loss: 2.8215
Step 100, Loss: 2.7736
Step 120, Loss: 2.7727
Step 140, Loss: 2.7753
Step 160, Loss: 2.7206
Step 180, Loss: 2.7191
Step 200, Loss: 2.7305
Step 220, Loss: 2.7307
Step 240, Loss: 2.6998
Step 260, Loss: 2.7114
Step 280, Loss: 2.7162
Step 300, Loss: 2.7260
Epoch 38 Loss: 2.7160
Epoch 39/50
Step 20, Loss: 2.6887
Step 40, Loss: 2.7608
Step 60, Loss: 2.8029
Step 80, Loss: 2.8190
Step 100, Loss: 2.7711
Step 120, Loss: 2.7702
Step 140, Loss: 2.7728
Step 160, Loss: 2.7182
Step 180, Loss: 2.7167
Step 200, Loss: 2.7281
Step 220, Loss: 2.7283
Step 240, Loss: 2.6974
Step 260, Loss: 2.7091
Step 280, Loss: 2.7138
Step 300, Loss: 2.7236
Epoch 39 Loss: 2.7136
Epoch 40/50
Step 20, Loss: 2.6863
Step 40, Loss: 2.7583
Step 60, Loss: 2.8005
Step 80, Loss: 2.8166
Step 100, Loss: 2.7687
Step 120, Loss: 2.7677
Step 140, Loss: 2.7704
Step 160, Loss: 2.7158
Step 180, Loss: 2.7143
Step 200, Loss: 2.7257
Step 220, Loss: 2.7259
Step 240, Loss: 2.6951
Step 260, Loss: 2.7067
Step 280, Loss: 2.7115
Step 300, Loss: 2.7212
Epoch 40 Loss: 2.7112
Epoch 41/50
Step 20, Loss: 2.6839
Step 40, Loss: 2.7558
Step 60, Loss: 2.7980
Step 80, Loss: 2.8141
Step 100, Loss: 2.7662
Step 120, Loss: 2.7653
Step 140, Loss: 2.7679
Step 160, Loss: 2.7134
Step 180, Loss: 2.7119
Step 200, Loss: 2.7233
Step 220, Loss: 2.7236
Step 240, Loss: 2.6927
Step 260, Loss: 2.7044
Step 280, Loss: 2.7091
Step 300, Loss: 2.7189
Epoch 41 Loss: 2.7089
Epoch 42/50
Step 20, Loss: 2.6814
Step 40, Loss: 2.7534
Step 60, Loss: 2.7956
Step 80, Loss: 2.8117
Step 100, Loss: 2.7637
Step 120, Loss: 2.7629
Step 140, Loss: 2.7655
Step 160, Loss: 2.7110
Step 180, Loss: 2.7095
Step 200, Loss: 2.7209
Step 220, Loss: 2.7212
Step 240, Loss: 2.6904
Step 260, Loss: 2.7020
Step 280, Loss: 2.7068
Step 300, Loss: 2.7165
Epoch 42 Loss: 2.7065
Epoch 43/50
Step 20, Loss: 2.6790
Step 40, Loss: 2.7510
Step 60, Loss: 2.7932
Step 80, Loss: 2.8093
Step 100, Loss: 2.7613
Step 120, Loss: 2.7605
Step 140, Loss: 2.7631
Step 160, Loss: 2.7086
Step 180, Loss: 2.7071
Step 200, Loss: 2.7185
Step 220, Loss: 2.7188
Step 240, Loss: 2.6880
Step 260, Loss: 2.6997
Step 280, Loss: 2.7044
Step 300, Loss: 2.7142
Epoch 43 Loss: 2.7042
Epoch 44/50
Step 20, Loss: 2.6766
Step 40, Loss: 2.7485
Step 60, Loss: 2.7908
Step 80, Loss: 2.8069
Step 100, Loss: 2.7588
Step 120, Loss: 2.7580
Step 140, Loss: 2.7607
Step 160, Loss: 2.7062
Step 180, Loss: 2.7048
Step 200, Loss: 2.7162
Step 220, Loss: 2.7165
Step 240, Loss: 2.6857
Step 260, Loss: 2.6973
Step 280, Loss: 2.7021
Step 300, Loss: 2.7119
Epoch 44 Loss: 2.7019
Epoch 45/50
Step 20, Loss: 2.6743
Step 40, Loss: 2.7461
Step 60, Loss: 2.7885
Step 80, Loss: 2.8045
Step 100, Loss: 2.7564
Step 120, Loss: 2.7556
Step 140, Loss: 2.7583
Step 160, Loss: 2.7039
Step 180, Loss: 2.7024
Step 200, Loss: 2.7138
Step 220, Loss: 2.7141
Step 240, Loss: 2.6834
Step 260, Loss: 2.6950
Step 280, Loss: 2.6998
Step 300, Loss: 2.7096
Epoch 45 Loss: 2.6996
Epoch 46/50
Step 20, Loss: 2.6719
Step 40, Loss: 2.7437
Step 60, Loss: 2.7861
Step 80, Loss: 2.8021
Step 100, Loss: 2.7540
Step 120, Loss: 2.7533
Step 140, Loss: 2.7559
Step 160, Loss: 2.7015
Step 180, Loss: 2.7000
Step 200, Loss: 2.7115
Step 220, Loss: 2.7118
Step 240, Loss: 2.6810
Step 260, Loss: 2.6927
Step 280, Loss: 2.6975
Step 300, Loss: 2.7072
Epoch 46 Loss: 2.6973
Epoch 47/50
Step 20, Loss: 2.6695
Step 40, Loss: 2.7414
Step 60, Loss: 2.7837
Step 80, Loss: 2.7997
Step 100, Loss: 2.7516
Step 120, Loss: 2.7509
Step 140, Loss: 2.7535
Step 160, Loss: 2.6992
Step 180, Loss: 2.6977
Step 200, Loss: 2.7092
Step 220, Loss: 2.7095
Step 240, Loss: 2.6787
Step 260, Loss: 2.6904
Step 280, Loss: 2.6952
Step 300, Loss: 2.7050
Epoch 47 Loss: 2.6950
Epoch 48/50
Step 20, Loss: 2.6672
Step 40, Loss: 2.7390
Step 60, Loss: 2.7814
Step 80, Loss: 2.7973
Step 100, Loss: 2.7492
Step 120, Loss: 2.7485
Step 140, Loss: 2.7511
Step 160, Loss: 2.6968
Step 180, Loss: 2.6954
Step 200, Loss: 2.7069
Step 220, Loss: 2.7072
Step 240, Loss: 2.6765
Step 260, Loss: 2.6881
Step 280, Loss: 2.6929
Step 300, Loss: 2.7027
Epoch 48 Loss: 2.6927
Epoch 49/50
Step 20, Loss: 2.6649
Step 40, Loss: 2.7367
Step 60, Loss: 2.7791
Step 80, Loss: 2.7950
Step 100, Loss: 2.7468
Step 120, Loss: 2.7462
Step 140, Loss: 2.7488
Step 160, Loss: 2.6945
Step 180, Loss: 2.6931
Step 200, Loss: 2.7046
Step 220, Loss: 2.7049
Step 240, Loss: 2.6742
Step 260, Loss: 2.6859
Step 280, Loss: 2.6906
Step 300, Loss: 2.7004
Epoch 49 Loss: 2.6904
Epoch 50/50
Step 20, Loss: 2.6626
Step 40, Loss: 2.7343
Step 60, Loss: 2.7768
Step 80, Loss: 2.7926
Step 100, Loss: 2.7444
Step 120, Loss: 2.7438
Step 140, Loss: 2.7464
Step 160, Loss: 2.6922
Step 180, Loss: 2.6907
Step 200, Loss: 2.7023
Step 220, Loss: 2.7026
Step 240, Loss: 2.6719
Step 260, Loss: 2.6836
Step 280, Loss: 2.6883
Step 300, Loss: 2.6981
Epoch 50 Loss: 2.6881

In [ ]:
# Final save of embeddings
checkpoint = {
    "epoch": 50,
    "model_state": model.state_dict(),
    "optimizer_state": optimizer.state_dict()
}
torch.save(checkpoint, "model_checkpoint_final.pth")

In [5]:
!pip install "sympy>=1.12"

Requirement already satisfied: sympy>=1.12 in /usr/local/lib/python3.12/dist-packages (1.14.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.12) (1.3.0)

In [6]:
# more training (in a new device because i ran out of free cloud GPU)
import torch
import torch.nn as nn
import torch.optim as optim
import pyarrow.parquet as pq
import numpy as np

model = ANN()
checkpoint = torch.load("model_checkpoint_final.pth", map_location="cuda" if torch.cuda.is_available() else "cpu")

model.load_state_dict(checkpoint["model_state"])
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)
optimizer = optim.Adam(model.parameters(), lr=1e-4)
optimizer.load_state_dict(checkpoint["optimizer_state"])
criterion = nn.CrossEntropyLoss()

train_model("train.parquet", model, optimizer, criterion, device, epochs=100, batch_size=512)

Epoch 1/100
Step 20, Loss: 2.6602
Step 40, Loss: 2.7320
Step 60, Loss: 2.7745
Step 80, Loss: 2.7903
Step 100, Loss: 2.7421
Step 120, Loss: 2.7415
Step 140, Loss: 2.7441
Step 160, Loss: 2.6899
Step 180, Loss: 2.6885
Step 200, Loss: 2.7000
Step 220, Loss: 2.7003
Step 240, Loss: 2.6696
Step 260, Loss: 2.6813
Step 280, Loss: 2.6861
Step 300, Loss: 2.6959
Epoch 1 Loss: 2.6859
Epoch 2/100
Step 20, Loss: 2.6580
Step 40, Loss: 2.7297
Step 60, Loss: 2.7722
Step 80, Loss: 2.7880
Step 100, Loss: 2.7397
Step 120, Loss: 2.7392
Step 140, Loss: 2.7418
Step 160, Loss: 2.6876
Step 180, Loss: 2.6862
Step 200, Loss: 2.6977
Step 220, Loss: 2.6980
Step 240, Loss: 2.6674
Step 260, Loss: 2.6791
Step 280, Loss: 2.6838
Step 300, Loss: 2.6936
Epoch 2 Loss: 2.6836
Epoch 3/100
Step 20, Loss: 2.6557
Step 40, Loss: 2.7274
Step 60, Loss: 2.7699
Step 80, Loss: 2.7857
Step 100, Loss: 2.7374
Step 120, Loss: 2.7369
Step 140, Loss: 2.7395
Step 160, Loss: 2.6854
Step 180, Loss: 2.6839
Step 200, Loss: 2.6955
Step 220, Loss: 2.6958
Step 240, Loss: 2.6651
Step 260, Loss: 2.6768
Step 280, Loss: 2.6816
Step 300, Loss: 2.6914
Epoch 3 Loss: 2.6814
Epoch 4/100
Step 20, Loss: 2.6534
Step 40, Loss: 2.7251
Step 60, Loss: 2.7676
Step 80, Loss: 2.7834
Step 100, Loss: 2.7351
Step 120, Loss: 2.7346
Step 140, Loss: 2.7372
Step 160, Loss: 2.6831
Step 180, Loss: 2.6816
Step 200, Loss: 2.6932
Step 220, Loss: 2.6935
Step 240, Loss: 2.6629
Step 260, Loss: 2.6746
Step 280, Loss: 2.6794
Step 300, Loss: 2.6891
Epoch 4 Loss: 2.6791
Epoch 5/100
Step 20, Loss: 2.6511
Step 40, Loss: 2.7228
Step 60, Loss: 2.7653
Step 80, Loss: 2.7811
Step 100, Loss: 2.7328
Step 120, Loss: 2.7323
Step 140, Loss: 2.7349
Step 160, Loss: 2.6808
Step 180, Loss: 2.6793
Step 200, Loss: 2.6909
Step 220, Loss: 2.6913
Step 240, Loss: 2.6607
Step 260, Loss: 2.6724
Step 280, Loss: 2.6771
Step 300, Loss: 2.6869
Epoch 5 Loss: 2.6769
Epoch 6/100
Step 20, Loss: 2.6489
Step 40, Loss: 2.7205
Step 60, Loss: 2.7631
Step 80, Loss: 2.7788
Step 100, Loss: 2.7304
Step 120, Loss: 2.7300
Step 140, Loss: 2.7326
Step 160, Loss: 2.6786
Step 180, Loss: 2.6771
Step 200, Loss: 2.6887
Step 220, Loss: 2.6890
Step 240, Loss: 2.6584
Step 260, Loss: 2.6702
Step 280, Loss: 2.6749
Step 300, Loss: 2.6847
Epoch 6 Loss: 2.6747
Epoch 7/100
Step 20, Loss: 2.6467
Step 40, Loss: 2.7183
Step 60, Loss: 2.7609
Step 80, Loss: 2.7765
Step 100, Loss: 2.7281
Step 120, Loss: 2.7277
Step 140, Loss: 2.7303
Step 160, Loss: 2.6763
Step 180, Loss: 2.6748
Step 200, Loss: 2.6865
Step 220, Loss: 2.6868
Step 240, Loss: 2.6562
Step 260, Loss: 2.6679
Step 280, Loss: 2.6727
Step 300, Loss: 2.6825
Epoch 7 Loss: 2.6725
Epoch 8/100
Step 20, Loss: 2.6444
Step 40, Loss: 2.7160
Step 60, Loss: 2.7586
Step 80, Loss: 2.7742
Step 100, Loss: 2.7259
Step 120, Loss: 2.7254
Step 140, Loss: 2.7281
Step 160, Loss: 2.6741
Step 180, Loss: 2.6726
Step 200, Loss: 2.6843
Step 220, Loss: 2.6846
Step 240, Loss: 2.6540
Step 260, Loss: 2.6657
Step 280, Loss: 2.6705
Step 300, Loss: 2.6802
Epoch 8 Loss: 2.6703
Epoch 9/100
Step 20, Loss: 2.6422
Step 40, Loss: 2.7138
Step 60, Loss: 2.7564
Step 80, Loss: 2.7720
Step 100, Loss: 2.7236
Step 120, Loss: 2.7232
Step 140, Loss: 2.7258
Step 160, Loss: 2.6719
Step 180, Loss: 2.6704
Step 200, Loss: 2.6820
Step 220, Loss: 2.6824
Step 240, Loss: 2.6518
Step 260, Loss: 2.6636
Step 280, Loss: 2.6683
Step 300, Loss: 2.6781
Epoch 9 Loss: 2.6681
Epoch 10/100
Step 20, Loss: 2.6400
Step 40, Loss: 2.7116
Step 60, Loss: 2.7542
Step 80, Loss: 2.7698
Step 100, Loss: 2.7213
Step 120, Loss: 2.7209
Step 140, Loss: 2.7236
Step 160, Loss: 2.6697
Step 180, Loss: 2.6682
Step 200, Loss: 2.6798
Step 220, Loss: 2.6802
Step 240, Loss: 2.6496
Step 260, Loss: 2.6614
Step 280, Loss: 2.6661
Step 300, Loss: 2.6759
Epoch 10 Loss: 2.6659
Epoch 11/100
Step 20, Loss: 2.6378
Step 40, Loss: 2.7093
Step 60, Loss: 2.7520
Step 80, Loss: 2.7675
Step 100, Loss: 2.7190
Step 120, Loss: 2.7187
Step 140, Loss: 2.7213
Step 160, Loss: 2.6675
Step 180, Loss: 2.6659
Step 200, Loss: 2.6776
Step 220, Loss: 2.6780
Step 240, Loss: 2.6474
Step 260, Loss: 2.6592
Step 280, Loss: 2.6639
Step 300, Loss: 2.6737
Epoch 11 Loss: 2.6637
Epoch 12/100
Step 20, Loss: 2.6356
Step 40, Loss: 2.7071
Step 60, Loss: 2.7498
Step 80, Loss: 2.7653
Step 100, Loss: 2.7168
Step 120, Loss: 2.7165
Step 140, Loss: 2.7191
Step 160, Loss: 2.6653
Step 180, Loss: 2.6637
Step 200, Loss: 2.6754
Step 220, Loss: 2.6758
Step 240, Loss: 2.6453
Step 260, Loss: 2.6570
Step 280, Loss: 2.6617
Step 300, Loss: 2.6715
Epoch 12 Loss: 2.6615
Epoch 13/100
Step 20, Loss: 2.6334
Step 40, Loss: 2.7049
Step 60, Loss: 2.7476
Step 80, Loss: 2.7631
Step 100, Loss: 2.7145
Step 120, Loss: 2.7143
Step 140, Loss: 2.7168
Step 160, Loss: 2.6631
Step 180, Loss: 2.6615
Step 200, Loss: 2.6733
Step 220, Loss: 2.6736
Step 240, Loss: 2.6431
Step 260, Loss: 2.6548
Step 280, Loss: 2.6596
Step 300, Loss: 2.6693
Epoch 13 Loss: 2.6594
Epoch 14/100
Step 20, Loss: 2.6313
Step 40, Loss: 2.7027
Step 60, Loss: 2.7454
Step 80, Loss: 2.7609
Step 100, Loss: 2.7123
Step 120, Loss: 2.7120
Step 140, Loss: 2.7146
Step 160, Loss: 2.6609
Step 180, Loss: 2.6594
Step 200, Loss: 2.6711
Step 220, Loss: 2.6715
Step 240, Loss: 2.6409
Step 260, Loss: 2.6527
Step 280, Loss: 2.6574
Step 300, Loss: 2.6672
Epoch 14 Loss: 2.6572
Epoch 15/100
Step 20, Loss: 2.6291
Step 40, Loss: 2.7005
Step 60, Loss: 2.7432
Step 80, Loss: 2.7587
Step 100, Loss: 2.7101
Step 120, Loss: 2.7098
Step 140, Loss: 2.7124
Step 160, Loss: 2.6587
Step 180, Loss: 2.6572
Step 200, Loss: 2.6689
Step 220, Loss: 2.6693
Step 240, Loss: 2.6388
Step 260, Loss: 2.6505
Step 280, Loss: 2.6553
Step 300, Loss: 2.6650
Epoch 15 Loss: 2.6551
Epoch 16/100
Step 20, Loss: 2.6269
Step 40, Loss: 2.6983
Step 60, Loss: 2.7411
Step 80, Loss: 2.7565
Step 100, Loss: 2.7079
Step 120, Loss: 2.7076
Step 140, Loss: 2.7102
Step 160, Loss: 2.6565
Step 180, Loss: 2.6550
Step 200, Loss: 2.6668
Step 220, Loss: 2.6671
Step 240, Loss: 2.6366
Step 260, Loss: 2.6484
Step 280, Loss: 2.6531
Step 300, Loss: 2.6629
Epoch 16 Loss: 2.6529
Epoch 17/100
Step 20, Loss: 2.6248
Step 40, Loss: 2.6962
Step 60, Loss: 2.7389
Step 80, Loss: 2.7543
Step 100, Loss: 2.7056
Step 120, Loss: 2.7055
Step 140, Loss: 2.7080
Step 160, Loss: 2.6544
Step 180, Loss: 2.6528
Step 200, Loss: 2.6646
Step 220, Loss: 2.6650
Step 240, Loss: 2.6345
Step 260, Loss: 2.6463
Step 280, Loss: 2.6510
Step 300, Loss: 2.6607
Epoch 17 Loss: 2.6508
Epoch 18/100
Step 20, Loss: 2.6227
Step 40, Loss: 2.6940
Step 60, Loss: 2.7368
Step 80, Loss: 2.7521
Step 100, Loss: 2.7034
Step 120, Loss: 2.7033
Step 140, Loss: 2.7059
Step 160, Loss: 2.6522
Step 180, Loss: 2.6507
Step 200, Loss: 2.6625
Step 220, Loss: 2.6628
Step 240, Loss: 2.6324
Step 260, Loss: 2.6441
Step 280, Loss: 2.6488
Step 300, Loss: 2.6586
Epoch 18 Loss: 2.6486
Epoch 19/100
Step 20, Loss: 2.6206
Step 40, Loss: 2.6919
Step 60, Loss: 2.7346
Step 80, Loss: 2.7499
Step 100, Loss: 2.7013
Step 120, Loss: 2.7011
Step 140, Loss: 2.7037
Step 160, Loss: 2.6501
Step 180, Loss: 2.6485
Step 200, Loss: 2.6603
Step 220, Loss: 2.6607
Step 240, Loss: 2.6303
Step 260, Loss: 2.6420
Step 280, Loss: 2.6467
Step 300, Loss: 2.6565
Epoch 19 Loss: 2.6465
Epoch 20/100
Step 20, Loss: 2.6184
Step 40, Loss: 2.6897
Step 60, Loss: 2.7325
Step 80, Loss: 2.7478
Step 100, Loss: 2.6991
Step 120, Loss: 2.6989
Step 140, Loss: 2.7015
Step 160, Loss: 2.6480
Step 180, Loss: 2.6464
Step 200, Loss: 2.6582
Step 220, Loss: 2.6586
Step 240, Loss: 2.6281
Step 260, Loss: 2.6399
Step 280, Loss: 2.6446
Step 300, Loss: 2.6543
Epoch 20 Loss: 2.6444
Epoch 21/100
Step 20, Loss: 2.6163
Step 40, Loss: 2.6876
Step 60, Loss: 2.7304
Step 80, Loss: 2.7456
Step 100, Loss: 2.6969
Step 120, Loss: 2.6968
Step 140, Loss: 2.6993
Step 160, Loss: 2.6458
Step 180, Loss: 2.6442
Step 200, Loss: 2.6561
Step 220, Loss: 2.6564
Step 240, Loss: 2.6260
Step 260, Loss: 2.6378
Step 280, Loss: 2.6425
Step 300, Loss: 2.6522
Epoch 21 Loss: 2.6423
Epoch 22/100
Step 20, Loss: 2.6142
Step 40, Loss: 2.6855
Step 60, Loss: 2.7283
Step 80, Loss: 2.7435
Step 100, Loss: 2.6947
Step 120, Loss: 2.6946
Step 140, Loss: 2.6972
Step 160, Loss: 2.6437
Step 180, Loss: 2.6421
Step 200, Loss: 2.6540
Step 220, Loss: 2.6543
Step 240, Loss: 2.6239
Step 260, Loss: 2.6357
Step 280, Loss: 2.6404
Step 300, Loss: 2.6501
Epoch 22 Loss: 2.6402
Epoch 23/100
Step 20, Loss: 2.6121
Step 40, Loss: 2.6833
Step 60, Loss: 2.7261
Step 80, Loss: 2.7413
Step 100, Loss: 2.6925
Step 120, Loss: 2.6925
Step 140, Loss: 2.6950
Step 160, Loss: 2.6416
Step 180, Loss: 2.6400
Step 200, Loss: 2.6518
Step 220, Loss: 2.6522
Step 240, Loss: 2.6218
Step 260, Loss: 2.6336
Step 280, Loss: 2.6383
Step 300, Loss: 2.6480
Epoch 23 Loss: 2.6381
Epoch 24/100
Step 20, Loss: 2.6100
Step 40, Loss: 2.6812
Step 60, Loss: 2.7241
Step 80, Loss: 2.7392
Step 100, Loss: 2.6904
Step 120, Loss: 2.6904
Step 140, Loss: 2.6929
Step 160, Loss: 2.6395
Step 180, Loss: 2.6379
Step 200, Loss: 2.6497
Step 220, Loss: 2.6501
Step 240, Loss: 2.6197
Step 260, Loss: 2.6315
Step 280, Loss: 2.6362
Step 300, Loss: 2.6459
Epoch 24 Loss: 2.6360
Epoch 25/100
Step 20, Loss: 2.6079
Step 40, Loss: 2.6791
Step 60, Loss: 2.7219
Step 80, Loss: 2.7371
Step 100, Loss: 2.6882
Step 120, Loss: 2.6882
Step 140, Loss: 2.6908
Step 160, Loss: 2.6374
Step 180, Loss: 2.6358
Step 200, Loss: 2.6476
Step 220, Loss: 2.6480
Step 240, Loss: 2.6177
Step 260, Loss: 2.6294
Step 280, Loss: 2.6341
Step 300, Loss: 2.6439
Epoch 25 Loss: 2.6339
Epoch 26/100
Step 20, Loss: 2.6059
Step 40, Loss: 2.6770
Step 60, Loss: 2.7199
Step 80, Loss: 2.7350
Step 100, Loss: 2.6861
Step 120, Loss: 2.6861
Step 140, Loss: 2.6887
Step 160, Loss: 2.6353
Step 180, Loss: 2.6337
Step 200, Loss: 2.6456
Step 220, Loss: 2.6459
Step 240, Loss: 2.6156
Step 260, Loss: 2.6274
Step 280, Loss: 2.6320
Step 300, Loss: 2.6418
Epoch 26 Loss: 2.6318
Epoch 27/100
Step 20, Loss: 2.6038
Step 40, Loss: 2.6749
Step 60, Loss: 2.7178
Step 80, Loss: 2.7329
Step 100, Loss: 2.6840
Step 120, Loss: 2.6840
Step 140, Loss: 2.6865
Step 160, Loss: 2.6332
Step 180, Loss: 2.6316
Step 200, Loss: 2.6435
Step 220, Loss: 2.6438
Step 240, Loss: 2.6135
Step 260, Loss: 2.6253
Step 280, Loss: 2.6300
Step 300, Loss: 2.6397
Epoch 27 Loss: 2.6297
Epoch 28/100
Step 20, Loss: 2.6018
Step 40, Loss: 2.6728
Step 60, Loss: 2.7157
Step 80, Loss: 2.7308
Step 100, Loss: 2.6818
Step 120, Loss: 2.6819
Step 140, Loss: 2.6844
Step 160, Loss: 2.6311
Step 180, Loss: 2.6295
Step 200, Loss: 2.6414
Step 220, Loss: 2.6418
Step 240, Loss: 2.6114
Step 260, Loss: 2.6232
Step 280, Loss: 2.6279
Step 300, Loss: 2.6376
Epoch 28 Loss: 2.6277
Epoch 29/100
Step 20, Loss: 2.5997
Step 40, Loss: 2.6708
Step 60, Loss: 2.7136
Step 80, Loss: 2.7287
Step 100, Loss: 2.6797
Step 120, Loss: 2.6798
Step 140, Loss: 2.6823
Step 160, Loss: 2.6290
Step 180, Loss: 2.6274
Step 200, Loss: 2.6393
Step 220, Loss: 2.6397
Step 240, Loss: 2.6094
Step 260, Loss: 2.6212
Step 280, Loss: 2.6258
Step 300, Loss: 2.6356
Epoch 29 Loss: 2.6256
Epoch 30/100
Step 20, Loss: 2.5976
Step 40, Loss: 2.6687
Step 60, Loss: 2.7116
Step 80, Loss: 2.7266
Step 100, Loss: 2.6776
Step 120, Loss: 2.6777
Step 140, Loss: 2.6802
Step 160, Loss: 2.6270
Step 180, Loss: 2.6254
Step 200, Loss: 2.6373
Step 220, Loss: 2.6377
Step 240, Loss: 2.6073
Step 260, Loss: 2.6191
Step 280, Loss: 2.6238
Step 300, Loss: 2.6335
Epoch 30 Loss: 2.6236
Epoch 31/100
Step 20, Loss: 2.5956
Step 40, Loss: 2.6666
Step 60, Loss: 2.7095
Step 80, Loss: 2.7245
Step 100, Loss: 2.6755
Step 120, Loss: 2.6756
Step 140, Loss: 2.6781
Step 160, Loss: 2.6249
Step 180, Loss: 2.6233
Step 200, Loss: 2.6352
Step 220, Loss: 2.6356
Step 240, Loss: 2.6053
Step 260, Loss: 2.6171
Step 280, Loss: 2.6217
Step 300, Loss: 2.6315
Epoch 31 Loss: 2.6215
Epoch 32/100
Step 20, Loss: 2.5936
Step 40, Loss: 2.6646
Step 60, Loss: 2.7075
Step 80, Loss: 2.7224
Step 100, Loss: 2.6734
Step 120, Loss: 2.6735
Step 140, Loss: 2.6760
Step 160, Loss: 2.6228
Step 180, Loss: 2.6212
Step 200, Loss: 2.6332
Step 220, Loss: 2.6335
Step 240, Loss: 2.6033
Step 260, Loss: 2.6150
Step 280, Loss: 2.6197
Step 300, Loss: 2.6294
Epoch 32 Loss: 2.6195
Epoch 33/100
Step 20, Loss: 2.5916
Step 40, Loss: 2.6625
Step 60, Loss: 2.7054
Step 80, Loss: 2.7204
Step 100, Loss: 2.6713
Step 120, Loss: 2.6715
Step 140, Loss: 2.6740
Step 160, Loss: 2.6208
Step 180, Loss: 2.6192
Step 200, Loss: 2.6311
Step 220, Loss: 2.6315
Step 240, Loss: 2.6012
Step 260, Loss: 2.6130
Step 280, Loss: 2.6177
Step 300, Loss: 2.6274
Epoch 33 Loss: 2.6174
Epoch 34/100
Step 20, Loss: 2.5895
Step 40, Loss: 2.6605
Step 60, Loss: 2.7034
Step 80, Loss: 2.7183
Step 100, Loss: 2.6692
Step 120, Loss: 2.6694
Step 140, Loss: 2.6719
Step 160, Loss: 2.6187
Step 180, Loss: 2.6171
Step 200, Loss: 2.6291
Step 220, Loss: 2.6295
Step 240, Loss: 2.5992
Step 260, Loss: 2.6110
Step 280, Loss: 2.6156
Step 300, Loss: 2.6254
Epoch 34 Loss: 2.6154
Epoch 35/100
Step 20, Loss: 2.5875
Step 40, Loss: 2.6585
Step 60, Loss: 2.7014
Step 80, Loss: 2.7162
Step 100, Loss: 2.6671
Step 120, Loss: 2.6673
Step 140, Loss: 2.6698
Step 160, Loss: 2.6167
Step 180, Loss: 2.6151
Step 200, Loss: 2.6271
Step 220, Loss: 2.6274
Step 240, Loss: 2.5972
Step 260, Loss: 2.6090
Step 280, Loss: 2.6136
Step 300, Loss: 2.6233
Epoch 35 Loss: 2.6134
Epoch 36/100
Step 20, Loss: 2.5855
Step 40, Loss: 2.6564
Step 60, Loss: 2.6994
Step 80, Loss: 2.7142
Step 100, Loss: 2.6651
Step 120, Loss: 2.6653
Step 140, Loss: 2.6678
Step 160, Loss: 2.6147
Step 180, Loss: 2.6130
Step 200, Loss: 2.6250
Step 220, Loss: 2.6254
Step 240, Loss: 2.5952
Step 260, Loss: 2.6070
Step 280, Loss: 2.6116
Step 300, Loss: 2.6213
Epoch 36 Loss: 2.6114
Epoch 37/100
Step 20, Loss: 2.5836
Step 40, Loss: 2.6544
Step 60, Loss: 2.6974
Step 80, Loss: 2.7122
Step 100, Loss: 2.6630
Step 120, Loss: 2.6633
Step 140, Loss: 2.6657
Step 160, Loss: 2.6127
Step 180, Loss: 2.6110
Step 200, Loss: 2.6230
Step 220, Loss: 2.6234
Step 240, Loss: 2.5932
Step 260, Loss: 2.6050
Step 280, Loss: 2.6096
Step 300, Loss: 2.6193
Epoch 37 Loss: 2.6094
Epoch 38/100
Step 20, Loss: 2.5816
Step 40, Loss: 2.6524
Step 60, Loss: 2.6954
Step 80, Loss: 2.7101
Step 100, Loss: 2.6610
Step 120, Loss: 2.6612
Step 140, Loss: 2.6637
Step 160, Loss: 2.6106
Step 180, Loss: 2.6090
Step 200, Loss: 2.6210
Step 220, Loss: 2.6214
Step 240, Loss: 2.5912
Step 260, Loss: 2.6030
Step 280, Loss: 2.6076
Step 300, Loss: 2.6173
Epoch 38 Loss: 2.6074
Epoch 39/100
Step 20, Loss: 2.5796
Step 40, Loss: 2.6504
Step 60, Loss: 2.6934
Step 80, Loss: 2.7081
Step 100, Loss: 2.6589
Step 120, Loss: 2.6592
Step 140, Loss: 2.6616
Step 160, Loss: 2.6086
Step 180, Loss: 2.6070
Step 200, Loss: 2.6190
Step 220, Loss: 2.6194
Step 240, Loss: 2.5892
Step 260, Loss: 2.6010
Step 280, Loss: 2.6056
Step 300, Loss: 2.6153
Epoch 39 Loss: 2.6054
Epoch 40/100
Step 20, Loss: 2.5776
Step 40, Loss: 2.6484
Step 60, Loss: 2.6914
Step 80, Loss: 2.7061
Step 100, Loss: 2.6569
Step 120, Loss: 2.6572
Step 140, Loss: 2.6596
Step 160, Loss: 2.6066
Step 180, Loss: 2.6050
Step 200, Loss: 2.6170
Step 220, Loss: 2.6174
Step 240, Loss: 2.5872
Step 260, Loss: 2.5990
Step 280, Loss: 2.6036
Step 300, Loss: 2.6133
Epoch 40 Loss: 2.6034
Epoch 41/100
Step 20, Loss: 2.5756
Step 40, Loss: 2.6464
Step 60, Loss: 2.6894
Step 80, Loss: 2.7041
Step 100, Loss: 2.6548
Step 120, Loss: 2.6551
Step 140, Loss: 2.6576
Step 160, Loss: 2.6046
Step 180, Loss: 2.6030
Step 200, Loss: 2.6150
Step 220, Loss: 2.6154
Step 240, Loss: 2.5852
Step 260, Loss: 2.5970
Step 280, Loss: 2.6016
Step 300, Loss: 2.6113
Epoch 41 Loss: 2.6014
Epoch 42/100
Step 20, Loss: 2.5737
Step 40, Loss: 2.6444
Step 60, Loss: 2.6874
Step 80, Loss: 2.7020
Step 100, Loss: 2.6528
Step 120, Loss: 2.6531
Step 140, Loss: 2.6556
Step 160, Loss: 2.6026
Step 180, Loss: 2.6010
Step 200, Loss: 2.6130
Step 220, Loss: 2.6134
Step 240, Loss: 2.5832
Step 260, Loss: 2.5950
Step 280, Loss: 2.5996
Step 300, Loss: 2.6093
Epoch 42 Loss: 2.5994
Epoch 43/100
Step 20, Loss: 2.5717
Step 40, Loss: 2.6424
Step 60, Loss: 2.6855
Step 80, Loss: 2.7001
Step 100, Loss: 2.6508
Step 120, Loss: 2.6511
Step 140, Loss: 2.6535
Step 160, Loss: 2.6006
Step 180, Loss: 2.5990
Step 200, Loss: 2.6110
Step 220, Loss: 2.6114
Step 240, Loss: 2.5813
Step 260, Loss: 2.5931
Step 280, Loss: 2.5976
Step 300, Loss: 2.6074
Epoch 43 Loss: 2.5974
Epoch 44/100
Step 20, Loss: 2.5698
Step 40, Loss: 2.6405
Step 60, Loss: 2.6835
Step 80, Loss: 2.6981
Step 100, Loss: 2.6487
Step 120, Loss: 2.6491
Step 140, Loss: 2.6515
Step 160, Loss: 2.5987
Step 180, Loss: 2.5970
Step 200, Loss: 2.6091
Step 220, Loss: 2.6095
Step 240, Loss: 2.5793
Step 260, Loss: 2.5911
Step 280, Loss: 2.5957
Step 300, Loss: 2.6054
Epoch 44 Loss: 2.5955
Epoch 45/100
Step 20, Loss: 2.5678
Step 40, Loss: 2.6385
Step 60, Loss: 2.6815
Step 80, Loss: 2.6961
Step 100, Loss: 2.6467
Step 120, Loss: 2.6471
Step 140, Loss: 2.6495
Step 160, Loss: 2.5967
Step 180, Loss: 2.5950
Step 200, Loss: 2.6071
Step 220, Loss: 2.6075
Step 240, Loss: 2.5773
Step 260, Loss: 2.5891
Step 280, Loss: 2.5937
Step 300, Loss: 2.6034
Epoch 45 Loss: 2.5935
Epoch 46/100
Step 20, Loss: 2.5659
Step 40, Loss: 2.6365
Step 60, Loss: 2.6796
Step 80, Loss: 2.6941
Step 100, Loss: 2.6447
Step 120, Loss: 2.6451
Step 140, Loss: 2.6475
Step 160, Loss: 2.5947
Step 180, Loss: 2.5930
Step 200, Loss: 2.6051
Step 220, Loss: 2.6055
Step 240, Loss: 2.5754
Step 260, Loss: 2.5872
Step 280, Loss: 2.5917
Step 300, Loss: 2.6015
Epoch 46 Loss: 2.5915
Epoch 47/100
Step 20, Loss: 2.5640
Step 40, Loss: 2.6346
Step 60, Loss: 2.6776
Step 80, Loss: 2.6921
Step 100, Loss: 2.6427
Step 120, Loss: 2.6432
Step 140, Loss: 2.6456
Step 160, Loss: 2.5928
Step 180, Loss: 2.5911
Step 200, Loss: 2.6032
Step 220, Loss: 2.6036
Step 240, Loss: 2.5734
Step 260, Loss: 2.5852
Step 280, Loss: 2.5898
Step 300, Loss: 2.5995
Epoch 47 Loss: 2.5896
Epoch 48/100
Step 20, Loss: 2.5621
Step 40, Loss: 2.6326
Step 60, Loss: 2.6757
Step 80, Loss: 2.6901
Step 100, Loss: 2.6407
Step 120, Loss: 2.6412
Step 140, Loss: 2.6436
Step 160, Loss: 2.5908
Step 180, Loss: 2.5891
Step 200, Loss: 2.6012
Step 220, Loss: 2.6016
Step 240, Loss: 2.5715
Step 260, Loss: 2.5833
Step 280, Loss: 2.5879
Step 300, Loss: 2.5976
Epoch 48 Loss: 2.5876
Epoch 49/100
Step 20, Loss: 2.5601
Step 40, Loss: 2.6307
Step 60, Loss: 2.6738
Step 80, Loss: 2.6882
Step 100, Loss: 2.6387
Step 120, Loss: 2.6392
Step 140, Loss: 2.6416
Step 160, Loss: 2.5889
Step 180, Loss: 2.5872
Step 200, Loss: 2.5993
Step 220, Loss: 2.5997
Step 240, Loss: 2.5696
Step 260, Loss: 2.5814
Step 280, Loss: 2.5859
Step 300, Loss: 2.5956
Epoch 49 Loss: 2.5857
Epoch 50/100
Step 20, Loss: 2.5582
Step 40, Loss: 2.6287
Step 60, Loss: 2.6718
Step 80, Loss: 2.6862
Step 100, Loss: 2.6368
Step 120, Loss: 2.6372
Step 140, Loss: 2.6396
Step 160, Loss: 2.5869
Step 180, Loss: 2.5852
Step 200, Loss: 2.5973
Step 220, Loss: 2.5977
Step 240, Loss: 2.5676
Step 260, Loss: 2.5794
Step 280, Loss: 2.5840
Step 300, Loss: 2.5937
Epoch 50 Loss: 2.5838
Epoch 51/100
Step 20, Loss: 2.5563
Step 40, Loss: 2.6268
Step 60, Loss: 2.6699
Step 80, Loss: 2.6843
Step 100, Loss: 2.6348
Step 120, Loss: 2.6353
Step 140, Loss: 2.6377
Step 160, Loss: 2.5850
Step 180, Loss: 2.5833
Step 200, Loss: 2.5954
Step 220, Loss: 2.5958
Step 240, Loss: 2.5657
Step 260, Loss: 2.5775
Step 280, Loss: 2.5820
Step 300, Loss: 2.5918
Epoch 51 Loss: 2.5818
Epoch 52/100
Step 20, Loss: 2.5544
Step 40, Loss: 2.6249
Step 60, Loss: 2.6680
Step 80, Loss: 2.6823
Step 100, Loss: 2.6328
Step 120, Loss: 2.6333
Step 140, Loss: 2.6357
Step 160, Loss: 2.5830
Step 180, Loss: 2.5813
Step 200, Loss: 2.5935
Step 220, Loss: 2.5939
Step 240, Loss: 2.5638
Step 260, Loss: 2.5756
Step 280, Loss: 2.5801
Step 300, Loss: 2.5898
Epoch 52 Loss: 2.5799
Epoch 53/100
Step 20, Loss: 2.5525
Step 40, Loss: 2.6230
Step 60, Loss: 2.6661
Step 80, Loss: 2.6804
Step 100, Loss: 2.6309
Step 120, Loss: 2.6314
Step 140, Loss: 2.6338
Step 160, Loss: 2.5811
Step 180, Loss: 2.5794
Step 200, Loss: 2.5916
Step 220, Loss: 2.5920
Step 240, Loss: 2.5619
Step 260, Loss: 2.5737
Step 280, Loss: 2.5782
Step 300, Loss: 2.5879
Epoch 53 Loss: 2.5780
Epoch 54/100
Step 20, Loss: 2.5507
Step 40, Loss: 2.6211
Step 60, Loss: 2.6642

In [7]:
torch.save({
    "epoch": checkpoint["epoch"] + 10,   # continue epoch count
    "model_state": model.state_dict(),
    "optimizer_state": optimizer.state_dict(),
}, "model_checkpoint_200_epochs.pth")

In [8]:
# more training (continue from checkpoint)
import torch
import torch.nn as nn
import torch.optim as optim

model = ANN()
checkpoint = torch.load("model_checkpoint_200_epochs.pth", map_location="cuda" if torch.cuda.is_available() else "cpu")

# restore model + optimizer
model.load_state_dict(checkpoint["model_state"])
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

optimizer = optim.Adam(model.parameters(), lr=1e-4)
optimizer.load_state_dict(checkpoint["optimizer_state"])
criterion = nn.CrossEntropyLoss()

# train 100 more epochs
train_model("train.parquet", model, optimizer, criterion, device, epochs=100, batch_size=512)

# save new checkpoint
torch.save({
    "model_state": model.state_dict(),
    "optimizer_state": optimizer.state_dict()
}, "model_checkpoint_300_epochs.pth")

Epoch 1/100
Step 20, Loss: 2.4685
Step 40, Loss: 2.5376
Step 60, Loss: 2.5808
Step 80, Loss: 2.5936
Step 100, Loss: 2.5431
Step 120, Loss: 2.5443
Step 140, Loss: 2.5462
Step 160, Loss: 2.4947
Step 180, Loss: 2.4928
Step 200, Loss: 2.5053
Step 220, Loss: 2.5056
Step 240, Loss: 2.4760
Step 260, Loss: 2.4878
Step 280, Loss: 2.4920
Step 300, Loss: 2.5016
Epoch 1 Loss: 2.4917
Epoch 2/100
Step 20, Loss: 2.4669
Step 40, Loss: 2.5360
Step 60, Loss: 2.5791
Step 80, Loss: 2.5920
Step 100, Loss: 2.5414
Step 120, Loss: 2.5426
Step 140, Loss: 2.5445
Step 160, Loss: 2.4931
Step 180, Loss: 2.4911
Step 200, Loss: 2.5036
Step 220, Loss: 2.5039
Step 240, Loss: 2.4744
Step 260, Loss: 2.4861
Step 280, Loss: 2.4903
Step 300, Loss: 2.4999
Epoch 2 Loss: 2.4900
Epoch 3/100
Step 20, Loss: 2.4652
Step 40, Loss: 2.5343
Step 60, Loss: 2.5775
Step 80, Loss: 2.5903
Step 100, Loss: 2.5396
Step 120, Loss: 2.5409
Step 140, Loss: 2.5428
Step 160, Loss: 2.4914
Step 180, Loss: 2.4894
Step 200, Loss: 2.5019
Step 220, Loss: 2.5023
Step 240, Loss: 2.4727
Step 260, Loss: 2.4844
Step 280, Loss: 2.4886
Step 300, Loss: 2.4982
Epoch 3 Loss: 2.4884
Epoch 4/100
Step 20, Loss: 2.4636
Step 40, Loss: 2.5327
Step 60, Loss: 2.5758
Step 80, Loss: 2.5886
Step 100, Loss: 2.5379
Step 120, Loss: 2.5392
Step 140, Loss: 2.5411
Step 160, Loss: 2.4897
Step 180, Loss: 2.4877
Step 200, Loss: 2.5002
Step 220, Loss: 2.5006
Step 240, Loss: 2.4710
Step 260, Loss: 2.4827
Step 280, Loss: 2.4869
Step 300, Loss: 2.4965
Epoch 4 Loss: 2.4867
Epoch 5/100
Step 20, Loss: 2.4620
Step 40, Loss: 2.5310
Step 60, Loss: 2.5742
Step 80, Loss: 2.5869
Step 100, Loss: 2.5363
Step 120, Loss: 2.5375
Step 140, Loss: 2.5394
Step 160, Loss: 2.4880
Step 180, Loss: 2.4860
Step 200, Loss: 2.4986
Step 220, Loss: 2.4989
Step 240, Loss: 2.4694
Step 260, Loss: 2.4811
Step 280, Loss: 2.4853
Step 300, Loss: 2.4948
Epoch 5 Loss: 2.4850
Epoch 6/100
Step 20, Loss: 2.4604
Step 40, Loss: 2.5294
Step 60, Loss: 2.5725
Step 80, Loss: 2.5852
Step 100, Loss: 2.5346
Step 120, Loss: 2.5358
Step 140, Loss: 2.5377
Step 160, Loss: 2.4864
Step 180, Loss: 2.4844
Step 200, Loss: 2.4969
Step 220, Loss: 2.4972
Step 240, Loss: 2.4677
Step 260, Loss: 2.4794
Step 280, Loss: 2.4836
Step 300, Loss: 2.4932
Epoch 6 Loss: 2.4833
Epoch 7/100
Step 20, Loss: 2.4588
Step 40, Loss: 2.5277
Step 60, Loss: 2.5709
Step 80, Loss: 2.5836
Step 100, Loss: 2.5329
Step 120, Loss: 2.5342
Step 140, Loss: 2.5360
Step 160, Loss: 2.4847
Step 180, Loss: 2.4827
Step 200, Loss: 2.4952
Step 220, Loss: 2.4956
Step 240, Loss: 2.4660
Step 260, Loss: 2.4778
Step 280, Loss: 2.4819
Step 300, Loss: 2.4915
Epoch 7 Loss: 2.4817
Epoch 8/100
Step 20, Loss: 2.4572
Step 40, Loss: 2.5261
Step 60, Loss: 2.5692
Step 80, Loss: 2.5819
Step 100, Loss: 2.5312
Step 120, Loss: 2.5325
Step 140, Loss: 2.5343
Step 160, Loss: 2.4830
Step 180, Loss: 2.4810
Step 200, Loss: 2.4936
Step 220, Loss: 2.4939
Step 240, Loss: 2.4644
Step 260, Loss: 2.4761
Step 280, Loss: 2.4803
Step 300, Loss: 2.4898
Epoch 8 Loss: 2.4800
Epoch 9/100
Step 20, Loss: 2.4556
Step 40, Loss: 2.5245
Step 60, Loss: 2.5676
Step 80, Loss: 2.5802
Step 100, Loss: 2.5295
Step 120, Loss: 2.5308
Step 140, Loss: 2.5326
Step 160, Loss: 2.4814
Step 180, Loss: 2.4794
Step 200, Loss: 2.4919
Step 220, Loss: 2.4923
Step 240, Loss: 2.4627
Step 260, Loss: 2.4745
Step 280, Loss: 2.4786
Step 300, Loss: 2.4882
Epoch 9 Loss: 2.4784
Epoch 10/100
Step 20, Loss: 2.4540
Step 40, Loss: 2.5229
Step 60, Loss: 2.5660
Step 80, Loss: 2.5786
Step 100, Loss: 2.5278
Step 120, Loss: 2.5292
Step 140, Loss: 2.5310
Step 160, Loss: 2.4797
Step 180, Loss: 2.4777
Step 200, Loss: 2.4903
Step 220, Loss: 2.4906
Step 240, Loss: 2.4611
Step 260, Loss: 2.4728
Step 280, Loss: 2.4770
Step 300, Loss: 2.4865
Epoch 10 Loss: 2.4767
Epoch 11/100
Step 20, Loss: 2.4524
Step 40, Loss: 2.5213
Step 60, Loss: 2.5644
Step 80, Loss: 2.5769
Step 100, Loss: 2.5262
Step 120, Loss: 2.5275
Step 140, Loss: 2.5293
Step 160, Loss: 2.4781
Step 180, Loss: 2.4761
Step 200, Loss: 2.4886
Step 220, Loss: 2.4890
Step 240, Loss: 2.4595
Step 260, Loss: 2.4712
Step 280, Loss: 2.4753
Step 300, Loss: 2.4849
Epoch 11 Loss: 2.4751
Epoch 12/100
Step 20, Loss: 2.4509
Step 40, Loss: 2.5196
Step 60, Loss: 2.5628
Step 80, Loss: 2.5753
Step 100, Loss: 2.5245
Step 120, Loss: 2.5258
Step 140, Loss: 2.5276
Step 160, Loss: 2.4764
Step 180, Loss: 2.4744
Step 200, Loss: 2.4870
Step 220, Loss: 2.4873
Step 240, Loss: 2.4578
Step 260, Loss: 2.4695
Step 280, Loss: 2.4737
Step 300, Loss: 2.4832
Epoch 12 Loss: 2.4734
Epoch 13/100
Step 20, Loss: 2.4493
Step 40, Loss: 2.5180
Step 60, Loss: 2.5611
Step 80, Loss: 2.5737
Step 100, Loss: 2.5228
Step 120, Loss: 2.5242
Step 140, Loss: 2.5260
Step 160, Loss: 2.4748
Step 180, Loss: 2.4728
Step 200, Loss: 2.4853
Step 220, Loss: 2.4857
Step 240, Loss: 2.4562
Step 260, Loss: 2.4679
Step 280, Loss: 2.4720
Step 300, Loss: 2.4816
Epoch 13 Loss: 2.4718
Epoch 14/100
Step 20, Loss: 2.4477
Step 40, Loss: 2.5164
Step 60, Loss: 2.5595
Step 80, Loss: 2.5720
Step 100, Loss: 2.5212
Step 120, Loss: 2.5226
Step 140, Loss: 2.5243
Step 160, Loss: 2.4732
Step 180, Loss: 2.4711
Step 200, Loss: 2.4837
Step 220, Loss: 2.4841
Step 240, Loss: 2.4546
Step 260, Loss: 2.4663
Step 280, Loss: 2.4704
Step 300, Loss: 2.4800
Epoch 14 Loss: 2.4701
Epoch 15/100
Step 20, Loss: 2.4461
Step 40, Loss: 2.5148
Step 60, Loss: 2.5580
Step 80, Loss: 2.5704
Step 100, Loss: 2.5196
Step 120, Loss: 2.5209
Step 140, Loss: 2.5227
Step 160, Loss: 2.4715
Step 180, Loss: 2.4695
Step 200, Loss: 2.4821
Step 220, Loss: 2.4824
Step 240, Loss: 2.4530
Step 260, Loss: 2.4647
Step 280, Loss: 2.4688
Step 300, Loss: 2.4783
Epoch 15 Loss: 2.4685
Epoch 16/100
Step 20, Loss: 2.4446
Step 40, Loss: 2.5132
Step 60, Loss: 2.5564
Step 80, Loss: 2.5688
Step 100, Loss: 2.5179
Step 120, Loss: 2.5193
Step 140, Loss: 2.5210
Step 160, Loss: 2.4699
Step 180, Loss: 2.4679
Step 200, Loss: 2.4804
Step 220, Loss: 2.4808
Step 240, Loss: 2.4513
Step 260, Loss: 2.4630
Step 280, Loss: 2.4671
Step 300, Loss: 2.4767
Epoch 16 Loss: 2.4669
Epoch 17/100
Step 20, Loss: 2.4430
Step 40, Loss: 2.5117
Step 60, Loss: 2.5548
Step 80, Loss: 2.5672
Step 100, Loss: 2.5163
Step 120, Loss: 2.5177
Step 140, Loss: 2.5194
Step 160, Loss: 2.4683
Step 180, Loss: 2.4662
Step 200, Loss: 2.4788
Step 220, Loss: 2.4792
Step 240, Loss: 2.4497
Step 260, Loss: 2.4614
Step 280, Loss: 2.4655
Step 300, Loss: 2.4751
Epoch 17 Loss: 2.4653
Epoch 18/100
Step 20, Loss: 2.4415
Step 40, Loss: 2.5101
Step 60, Loss: 2.5532
Step 80, Loss: 2.5655
Step 100, Loss: 2.5146
Step 120, Loss: 2.5160
Step 140, Loss: 2.5178
Step 160, Loss: 2.4667
Step 180, Loss: 2.4646
Step 200, Loss: 2.4772
Step 220, Loss: 2.4776
Step 240, Loss: 2.4481
Step 260, Loss: 2.4598
Step 280, Loss: 2.4639
Step 300, Loss: 2.4734
Epoch 18 Loss: 2.4636
Epoch 19/100
Step 20, Loss: 2.4399
Step 40, Loss: 2.5085
Step 60, Loss: 2.5516
Step 80, Loss: 2.5639
Step 100, Loss: 2.5130
Step 120, Loss: 2.5144
Step 140, Loss: 2.5161
Step 160, Loss: 2.4651
Step 180, Loss: 2.4630
Step 200, Loss: 2.4756
Step 220, Loss: 2.4760
Step 240, Loss: 2.4465
Step 260, Loss: 2.4582
Step 280, Loss: 2.4623
Step 300, Loss: 2.4718
Epoch 19 Loss: 2.4620
Epoch 20/100
Step 20, Loss: 2.4384
Step 40, Loss: 2.5069
Step 60, Loss: 2.5500
Step 80, Loss: 2.5623
Step 100, Loss: 2.5114
Step 120, Loss: 2.5128
Step 140, Loss: 2.5145
Step 160, Loss: 2.4635
Step 180, Loss: 2.4614
Step 200, Loss: 2.4740
Step 220, Loss: 2.4743
Step 240, Loss: 2.4449
Step 260, Loss: 2.4566
Step 280, Loss: 2.4607
Step 300, Loss: 2.4702
Epoch 20 Loss: 2.4604
Epoch 21/100
Step 20, Loss: 2.4368
Step 40, Loss: 2.5054
Step 60, Loss: 2.5484
Step 80, Loss: 2.5607
Step 100, Loss: 2.5097
Step 120, Loss: 2.5112
Step 140, Loss: 2.5129
Step 160, Loss: 2.4618
Step 180, Loss: 2.4598
Step 200, Loss: 2.4724
Step 220, Loss: 2.4727
Step 240, Loss: 2.4433
Step 260, Loss: 2.4550
Step 280, Loss: 2.4591
Step 300, Loss: 2.4686
Epoch 21 Loss: 2.4588
Epoch 22/100
Step 20, Loss: 2.4353
Step 40, Loss: 2.5038
Step 60, Loss: 2.5469
Step 80, Loss: 2.5591
Step 100, Loss: 2.5081
Step 120, Loss: 2.5096
Step 140, Loss: 2.5112
Step 160, Loss: 2.4602
Step 180, Loss: 2.4582
Step 200, Loss: 2.4708
Step 220, Loss: 2.4711
Step 240, Loss: 2.4417
Step 260, Loss: 2.4534
Step 280, Loss: 2.4575
Step 300, Loss: 2.4670
Epoch 22 Loss: 2.4572
Epoch 23/100
Step 20, Loss: 2.4338
Step 40, Loss: 2.5022
Step 60, Loss: 2.5453
Step 80, Loss: 2.5575
Step 100, Loss: 2.5065
Step 120, Loss: 2.5080
Step 140, Loss: 2.5096
Step 160, Loss: 2.4586
Step 180, Loss: 2.4566
Step 200, Loss: 2.4692
Step 220, Loss: 2.4695
Step 240, Loss: 2.4401
Step 260, Loss: 2.4518
Step 280, Loss: 2.4559
Step 300, Loss: 2.4654
Epoch 23 Loss: 2.4556
Epoch 24/100
Step 20, Loss: 2.4322
Step 40, Loss: 2.5007
Step 60, Loss: 2.5437
Step 80, Loss: 2.5559
Step 100, Loss: 2.5049
Step 120, Loss: 2.5064
Step 140, Loss: 2.5080
Step 160, Loss: 2.4571
Step 180, Loss: 2.4550
Step 200, Loss: 2.4676
Step 220, Loss: 2.4680
Step 240, Loss: 2.4386
Step 260, Loss: 2.4502
Step 280, Loss: 2.4543
Step 300, Loss: 2.4638
Epoch 24 Loss: 2.4540
Epoch 25/100
Step 20, Loss: 2.4307
Step 40, Loss: 2.4991
Step 60, Loss: 2.5422
Step 80, Loss: 2.5543
Step 100, Loss: 2.5033
Step 120, Loss: 2.5048
Step 140, Loss: 2.5064
Step 160, Loss: 2.4555
Step 180, Loss: 2.4534
Step 200, Loss: 2.4660
Step 220, Loss: 2.4664
Step 240, Loss: 2.4370
Step 260, Loss: 2.4486
Step 280, Loss: 2.4527
Step 300, Loss: 2.4622
Epoch 25 Loss: 2.4524
Epoch 26/100
Step 20, Loss: 2.4292
Step 40, Loss: 2.4976
Step 60, Loss: 2.5406
Step 80, Loss: 2.5528
Step 100, Loss: 2.5017
Step 120, Loss: 2.5032
Step 140, Loss: 2.5048
Step 160, Loss: 2.4539
Step 180, Loss: 2.4518
Step 200, Loss: 2.4644
Step 220, Loss: 2.4648
Step 240, Loss: 2.4354
Step 260, Loss: 2.4471
Step 280, Loss: 2.4511
Step 300, Loss: 2.4606
Epoch 26 Loss: 2.4508
Epoch 27/100
Step 20, Loss: 2.4277
Step 40, Loss: 2.4960
Step 60, Loss: 2.5391
Step 80, Loss: 2.5512
Step 100, Loss: 2.5001
Step 120, Loss: 2.5016
Step 140, Loss: 2.5032
Step 160, Loss: 2.4523
Step 180, Loss: 2.4502
Step 200, Loss: 2.4628
Step 220, Loss: 2.4632
Step 240, Loss: 2.4338
Step 260, Loss: 2.4455
Step 280, Loss: 2.4495
Step 300, Loss: 2.4590
Epoch 27 Loss: 2.4492
Epoch 28/100
Step 20, Loss: 2.4262
Step 40, Loss: 2.4945
Step 60, Loss: 2.5375
Step 80, Loss: 2.5496
Step 100, Loss: 2.4985
Step 120, Loss: 2.5000
Step 140, Loss: 2.5016
Step 160, Loss: 2.4507
Step 180, Loss: 2.4487
Step 200, Loss: 2.4613
Step 220, Loss: 2.4616
Step 240, Loss: 2.4323
Step 260, Loss: 2.4439
Step 280, Loss: 2.4479
Step 300, Loss: 2.4574
Epoch 28 Loss: 2.4477
Epoch 29/100
Step 20, Loss: 2.4247
Step 40, Loss: 2.4929
Step 60, Loss: 2.5360
Step 80, Loss: 2.5480
Step 100, Loss: 2.4969
Step 120, Loss: 2.4984
Step 140, Loss: 2.5000
Step 160, Loss: 2.4492
Step 180, Loss: 2.4471
Step 200, Loss: 2.4597
Step 220, Loss: 2.4600
Step 240, Loss: 2.4307
Step 260, Loss: 2.4423
Step 280, Loss: 2.4464
Step 300, Loss: 2.4559
Epoch 29 Loss: 2.4461
Epoch 30/100
Step 20, Loss: 2.4232
Step 40, Loss: 2.4914
Step 60, Loss: 2.5345
Step 80, Loss: 2.5465
Step 100, Loss: 2.4953
Step 120, Loss: 2.4968
Step 140, Loss: 2.4984
Step 160, Loss: 2.4476
Step 180, Loss: 2.4455
Step 200, Loss: 2.4581
Step 220, Loss: 2.4585
Step 240, Loss: 2.4291
Step 260, Loss: 2.4408
Step 280, Loss: 2.4448
Step 300, Loss: 2.4543
Epoch 30 Loss: 2.4445
Epoch 31/100
Step 20, Loss: 2.4217
Step 40, Loss: 2.4899
Step 60, Loss: 2.5329
Step 80, Loss: 2.5449
Step 100, Loss: 2.4937
Step 120, Loss: 2.4953
Step 140, Loss: 2.4968
Step 160, Loss: 2.4460
Step 180, Loss: 2.4439
Step 200, Loss: 2.4566
Step 220, Loss: 2.4569
Step 240, Loss: 2.4276
Step 260, Loss: 2.4392
Step 280, Loss: 2.4432
Step 300, Loss: 2.4527
Epoch 31 Loss: 2.4429
Epoch 32/100
Step 20, Loss: 2.4202
Step 40, Loss: 2.4883
Step 60, Loss: 2.5314
Step 80, Loss: 2.5434
Step 100, Loss: 2.4921
Step 120, Loss: 2.4937
Step 140, Loss: 2.4952
Step 160, Loss: 2.4445
Step 180, Loss: 2.4424
Step 200, Loss: 2.4550
Step 220, Loss: 2.4553
Step 240, Loss: 2.4260
Step 260, Loss: 2.4377
Step 280, Loss: 2.4417
Step 300, Loss: 2.4512
Epoch 32 Loss: 2.4414
Epoch 33/100
Step 20, Loss: 2.4187
Step 40, Loss: 2.4868
Step 60, Loss: 2.5299
Step 80, Loss: 2.5418
Step 100, Loss: 2.4906
Step 120, Loss: 2.4921
Step 140, Loss: 2.4937
Step 160, Loss: 2.4429
Step 180, Loss: 2.4408
Step 200, Loss: 2.4534
Step 220, Loss: 2.4538
Step 240, Loss: 2.4245
Step 260, Loss: 2.4361
Step 280, Loss: 2.4401
Step 300, Loss: 2.4496
Epoch 33 Loss: 2.4398
Epoch 34/100
Step 20, Loss: 2.4172
Step 40, Loss: 2.4853
Step 60, Loss: 2.5283
Step 80, Loss: 2.5402
Step 100, Loss: 2.4890
Step 120, Loss: 2.4905
Step 140, Loss: 2.4921
Step 160, Loss: 2.4413
Step 180, Loss: 2.4392
Step 200, Loss: 2.4519
Step 220, Loss: 2.4522
Step 240, Loss: 2.4229
Step 260, Loss: 2.4346
Step 280, Loss: 2.4385
Step 300, Loss: 2.4480
Epoch 34 Loss: 2.4383
Epoch 35/100
Step 20, Loss: 2.4157
Step 40, Loss: 2.4838
Step 60, Loss: 2.5268
Step 80, Loss: 2.5387
Step 100, Loss: 2.4874
Step 120, Loss: 2.4890
Step 140, Loss: 2.4905
Step 160, Loss: 2.4398
Step 180, Loss: 2.4377
Step 200, Loss: 2.4503
Step 220, Loss: 2.4507
Step 240, Loss: 2.4214
Step 260, Loss: 2.4330
Step 280, Loss: 2.4370
Step 300, Loss: 2.4465
Epoch 35 Loss: 2.4367
Epoch 36/100
Step 20, Loss: 2.4142
Step 40, Loss: 2.4823
Step 60, Loss: 2.5253
Step 80, Loss: 2.5371
Step 100, Loss: 2.4859
Step 120, Loss: 2.4874
Step 140, Loss: 2.4889
Step 160, Loss: 2.4382
Step 180, Loss: 2.4361
Step 200, Loss: 2.4488
Step 220, Loss: 2.4491
Step 240, Loss: 2.4198
Step 260, Loss: 2.4315
Step 280, Loss: 2.4354
Step 300, Loss: 2.4449
Epoch 36 Loss: 2.4352
Epoch 37/100
Step 20, Loss: 2.4127
Step 40, Loss: 2.4807
Step 60, Loss: 2.5238
Step 80, Loss: 2.5356
Step 100, Loss: 2.4843
Step 120, Loss: 2.4859
Step 140, Loss: 2.4874
Step 160, Loss: 2.4367
Step 180, Loss: 2.4346
Step 200, Loss: 2.4473
Step 220, Loss: 2.4476
Step 240, Loss: 2.4183
Step 260, Loss: 2.4299
Step 280, Loss: 2.4339
Step 300, Loss: 2.4434
Epoch 37 Loss: 2.4336
Epoch 38/100
Step 20, Loss: 2.4113
Step 40, Loss: 2.4792
Step 60, Loss: 2.5223
Step 80, Loss: 2.5341
Step 100, Loss: 2.4827
Step 120, Loss: 2.4843
Step 140, Loss: 2.4858
Step 160, Loss: 2.4352
Step 180, Loss: 2.4330
Step 200, Loss: 2.4457
Step 220, Loss: 2.4460
Step 240, Loss: 2.4168
Step 260, Loss: 2.4284
Step 280, Loss: 2.4323
Step 300, Loss: 2.4418
Epoch 38 Loss: 2.4321
Epoch 39/100
Step 20, Loss: 2.4098
Step 40, Loss: 2.4777
Step 60, Loss: 2.5208
Step 80, Loss: 2.5325
Step 100, Loss: 2.4812
Step 120, Loss: 2.4828
Step 140, Loss: 2.4843
Step 160, Loss: 2.4336
Step 180, Loss: 2.4315
Step 200, Loss: 2.4442
Step 220, Loss: 2.4445
Step 240, Loss: 2.4152
Step 260, Loss: 2.4269
Step 280, Loss: 2.4308
Step 300, Loss: 2.4403
Epoch 39 Loss: 2.4305
Epoch 40/100
Step 20, Loss: 2.4083
Step 40, Loss: 2.4762
Step 60, Loss: 2.5193
Step 80, Loss: 2.5310
Step 100, Loss: 2.4796
Step 120, Loss: 2.4812
Step 140, Loss: 2.4827
Step 160, Loss: 2.4321
Step 180, Loss: 2.4300
Step 200, Loss: 2.4426
Step 220, Loss: 2.4430
Step 240, Loss: 2.4137
Step 260, Loss: 2.4253
Step 280, Loss: 2.4293
Step 300, Loss: 2.4387
Epoch 40 Loss: 2.4290
Epoch 41/100
Step 20, Loss: 2.4069
Step 40, Loss: 2.4747
Step 60, Loss: 2.5178
Step 80, Loss: 2.5295
Step 100, Loss: 2.4781
Step 120, Loss: 2.4797
Step 140, Loss: 2.4812
Step 160, Loss: 2.4306
Step 180, Loss: 2.4284
Step 200, Loss: 2.4411
Step 220, Loss: 2.4414
Step 240, Loss: 2.4122
Step 260, Loss: 2.4238
Step 280, Loss: 2.4277
Step 300, Loss: 2.4372
Epoch 41 Loss: 2.4275
Epoch 42/100
Step 20, Loss: 2.4054
Step 40, Loss: 2.4732
Step 60, Loss: 2.5163
Step 80, Loss: 2.5279
Step 100, Loss: 2.4765
Step 120, Loss: 2.4782
Step 140, Loss: 2.4796
Step 160, Loss: 2.4290
Step 180, Loss: 2.4269
Step 200, Loss: 2.4396
Step 220, Loss: 2.4399
Step 240, Loss: 2.4107
Step 260, Loss: 2.4223
Step 280, Loss: 2.4262
Step 300, Loss: 2.4357
Epoch 42 Loss: 2.4259
Epoch 43/100
Step 20, Loss: 2.4039
Step 40, Loss: 2.4718
Step 60, Loss: 2.5148
Step 80, Loss: 2.5264
Step 100, Loss: 2.4750
Step 120, Loss: 2.4766
Step 140, Loss: 2.4781
Step 160, Loss: 2.4275
Step 180, Loss: 2.4254
Step 200, Loss: 2.4381
Step 220, Loss: 2.4384
Step 240, Loss: 2.4092
Step 260, Loss: 2.4208
Step 280, Loss: 2.4247
Step 300, Loss: 2.4342
Epoch 43 Loss: 2.4244
Epoch 44/100
Step 20, Loss: 2.4025
Step 40, Loss: 2.4703
Step 60, Loss: 2.5133
Step 80, Loss: 2.5249
Step 100, Loss: 2.4735
Step 120, Loss: 2.4751
Step 140, Loss: 2.4765
Step 160, Loss: 2.4260
Step 180, Loss: 2.4238
Step 200, Loss: 2.4366
Step 220, Loss: 2.4369
Step 240, Loss: 2.4077
Step 260, Loss: 2.4193
Step 280, Loss: 2.4232
Step 300, Loss: 2.4326
Epoch 44 Loss: 2.4229
Epoch 45/100
Step 20, Loss: 2.4010
Step 40, Loss: 2.4688
Step 60, Loss: 2.5118
Step 80, Loss: 2.5234
Step 100, Loss: 2.4719
Step 120, Loss: 2.4736
Step 140, Loss: 2.4750
Step 160, Loss: 2.4245
Step 180, Loss: 2.4223
Step 200, Loss: 2.4350
Step 220, Loss: 2.4354
Step 240, Loss: 2.4061
Step 260, Loss: 2.4178
Step 280, Loss: 2.4217
Step 300, Loss: 2.4311
Epoch 45 Loss: 2.4214
Epoch 46/100
Step 20, Loss: 2.3996
Step 40, Loss: 2.4673
Step 60, Loss: 2.5104
Step 80, Loss: 2.5219
Step 100, Loss: 2.4704
Step 120, Loss: 2.4721
Step 140, Loss: 2.4735
Step 160, Loss: 2.4230
Step 180, Loss: 2.4208
Step 200, Loss: 2.4335
Step 220, Loss: 2.4339
Step 240, Loss: 2.4047
Step 260, Loss: 2.4163
Step 280, Loss: 2.4201
Step 300, Loss: 2.4296
Epoch 46 Loss: 2.4199
Epoch 47/100
Step 20, Loss: 2.3981
Step 40, Loss: 2.4659
Step 60, Loss: 2.5089
Step 80, Loss: 2.5204
Step 100, Loss: 2.4689
Step 120, Loss: 2.4706
Step 140, Loss: 2.4719
Step 160, Loss: 2.4215
Step 180, Loss: 2.4193
Step 200, Loss: 2.4320
Step 220, Loss: 2.4323
Step 240, Loss: 2.4031
Step 260, Loss: 2.4147
Step 280, Loss: 2.4186
Step 300, Loss: 2.4281
Epoch 47 Loss: 2.4183
Epoch 48/100
Step 20, Loss: 2.3967
Step 40, Loss: 2.4644
Step 60, Loss: 2.5074
Step 80, Loss: 2.5189
Step 100, Loss: 2.4674
Step 120, Loss: 2.4690
Step 140, Loss: 2.4704
Step 160, Loss: 2.4200
Step 180, Loss: 2.4178
Step 200, Loss: 2.4305
Step 220, Loss: 2.4308
Step 240, Loss: 2.4017
Step 260, Loss: 2.4133
Step 280, Loss: 2.4171
Step 300, Loss: 2.4266
Epoch 48 Loss: 2.4168
Epoch 49/100
Step 20, Loss: 2.3953
Step 40, Loss: 2.4629
Step 60, Loss: 2.5060
Step 80, Loss: 2.5174
Step 100, Loss: 2.4659
Step 120, Loss: 2.4675
Step 140, Loss: 2.4689
Step 160, Loss: 2.4185
Step 180, Loss: 2.4163
Step 200, Loss: 2.4290
Step 220, Loss: 2.4293
Step 240, Loss: 2.4002
Step 260, Loss: 2.4118
Step 280, Loss: 2.4156
Step 300, Loss: 2.4251
Epoch 49 Loss: 2.4153
Epoch 50/100
Step 20, Loss: 2.3938
Step 40, Loss: 2.4615
Step 60, Loss: 2.5045
Step 80, Loss: 2.5159
Step 100, Loss: 2.4643
Step 120, Loss: 2.4660
Step 140, Loss: 2.4674
Step 160, Loss: 2.4170
Step 180, Loss: 2.4148
Step 200, Loss: 2.4275
Step 220, Loss: 2.4278
Step 240, Loss: 2.3987
Step 260, Loss: 2.4103
Step 280, Loss: 2.4141
Step 300, Loss: 2.4236
Epoch 50 Loss: 2.4138
Epoch 51/100
Step 20, Loss: 2.3924
Step 40, Loss: 2.4600
Step 60, Loss: 2.5030
Step 80, Loss: 2.5144
Step 100, Loss: 2.4628
Step 120, Loss: 2.4645
Step 140, Loss: 2.4659
Step 160, Loss: 2.4155
Step 180, Loss: 2.4133
Step 200, Loss: 2.4260
Step 220, Loss: 2.4263
Step 240, Loss: 2.3972
Step 260, Loss: 2.4088
Step 280, Loss: 2.4126
Step 300, Loss: 2.4221
Epoch 51 Loss: 2.4123
Epoch 52/100
Step 20, Loss: 2.3910
Step 40, Loss: 2.4586
Step 60, Loss: 2.5016
Step 80, Loss: 2.5129
Step 100, Loss: 2.4613
Step 120, Loss: 2.4630
Step 140, Loss: 2.4644
Step 160, Loss: 2.4140
Step 180, Loss: 2.4118
Step 200, Loss: 2.4245
Step 220, Loss: 2.4249
Step 240, Loss: 2.3957
Step 260, Loss: 2.4073
Step 280, Loss: 2.4111
Step 300, Loss: 2.4206
Epoch 52 Loss: 2.4108
Epoch 53/100
Step 20, Loss: 2.3896
Step 40, Loss: 2.4571
Step 60, Loss: 2.5001
Step 80, Loss: 2.5115
Step 100, Loss: 2.4598
Step 120, Loss: 2.4616
Step 140, Loss: 2.4629
Step 160, Loss: 2.4125
Step 180, Loss: 2.4103
Step 200, Loss: 2.4231
Step 220, Loss: 2.4234
Step 240, Loss: 2.3942
Step 260, Loss: 2.4058
Step 280, Loss: 2.4096
Step 300, Loss: 2.4191
Epoch 53 Loss: 2.4093
Epoch 54/100
Step 20, Loss: 2.3881
Step 40, Loss: 2.4557
Step 60, Loss: 2.4987

In [9]:
torch.save({
    "epoch": checkpoint["epoch"] + 10,   # continue epoch count
    "model_state": model.state_dict(),
    "optimizer_state": optimizer.state_dict(),
}, "model_checkpoint_300_epochs.pth")

In [10]:
# more training (continue from checkpoint)
import torch
import torch.nn as nn
import torch.optim as optim

model = ANN()
checkpoint = torch.load("model_checkpoint_300_epochs.pth", map_location="cuda" if torch.cuda.is_available() else "cpu")

# restore model + optimizer
model.load_state_dict(checkpoint["model_state"])
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

optimizer = optim.Adam(model.parameters(), lr=1e-4)
optimizer.load_state_dict(checkpoint["optimizer_state"])
criterion = nn.CrossEntropyLoss()

# train 100 more epochs
train_model("train.parquet", model, optimizer, criterion, device, epochs=100, batch_size=512)

Epoch 1/100
Step 20, Loss: 2.3251
Step 40, Loss: 2.3913
Step 60, Loss: 2.4340
Step 80, Loss: 2.4441
Step 100, Loss: 2.3916
Step 120, Loss: 2.3937
Step 140, Loss: 2.3945
Step 160, Loss: 2.3451
Step 180, Loss: 2.3426
Step 200, Loss: 2.3555
Step 220, Loss: 2.3558
Step 240, Loss: 2.3271
Step 260, Loss: 2.3385
Step 280, Loss: 2.3420
Step 300, Loss: 2.3512
Epoch 1 Loss: 2.3416
Epoch 2/100
Step 20, Loss: 2.3238
Step 40, Loss: 2.3900
Step 60, Loss: 2.4327
Step 80, Loss: 2.4428
Step 100, Loss: 2.3903
Step 120, Loss: 2.3924
Step 140, Loss: 2.3931
Step 160, Loss: 2.3437
Step 180, Loss: 2.3413
Step 200, Loss: 2.3542
Step 220, Loss: 2.3545
Step 240, Loss: 2.3258
Step 260, Loss: 2.3372
Step 280, Loss: 2.3407
Step 300, Loss: 2.3499
Epoch 2 Loss: 2.3403
Epoch 3/100
Step 20, Loss: 2.3226
Step 40, Loss: 2.3887
Step 60, Loss: 2.4314
Step 80, Loss: 2.4415
Step 100, Loss: 2.3889
Step 120, Loss: 2.3911
Step 140, Loss: 2.3918
Step 160, Loss: 2.3424
Step 180, Loss: 2.3400
Step 200, Loss: 2.3529
Step 220, Loss: 2.3531
Step 240, Loss: 2.3245
Step 260, Loss: 2.3359
Step 280, Loss: 2.3393
Step 300, Loss: 2.3486
Epoch 3 Loss: 2.3389
Epoch 4/100
Step 20, Loss: 2.3213
Step 40, Loss: 2.3874
Step 60, Loss: 2.4301
Step 80, Loss: 2.4402
Step 100, Loss: 2.3876
Step 120, Loss: 2.3897
Step 140, Loss: 2.3905
Step 160, Loss: 2.3411
Step 180, Loss: 2.3386
Step 200, Loss: 2.3516
Step 220, Loss: 2.3518
Step 240, Loss: 2.3231
Step 260, Loss: 2.3346
Step 280, Loss: 2.3380
Step 300, Loss: 2.3472
Epoch 4 Loss: 2.3376
Epoch 5/100
Step 20, Loss: 2.3200
Step 40, Loss: 2.3861
Step 60, Loss: 2.4289
Step 80, Loss: 2.4388
Step 100, Loss: 2.3863
Step 120, Loss: 2.3884
Step 140, Loss: 2.3891
Step 160, Loss: 2.3398
Step 180, Loss: 2.3373
Step 200, Loss: 2.3502
Step 220, Loss: 2.3505
Step 240, Loss: 2.3218
Step 260, Loss: 2.3332
Step 280, Loss: 2.3367
Step 300, Loss: 2.3459
Epoch 5 Loss: 2.3363
Epoch 6/100
Step 20, Loss: 2.3188
Step 40, Loss: 2.3848
Step 60, Loss: 2.4275
Step 80, Loss: 2.4375
Step 100, Loss: 2.3849
Step 120, Loss: 2.3871
Step 140, Loss: 2.3878
Step 160, Loss: 2.3384
Step 180, Loss: 2.3360
Step 200, Loss: 2.3489
Step 220, Loss: 2.3492
Step 240, Loss: 2.3205
Step 260, Loss: 2.3319
Step 280, Loss: 2.3354
Step 300, Loss: 2.3446
Epoch 6 Loss: 2.3350
Epoch 7/100
Step 20, Loss: 2.3175
Step 40, Loss: 2.3835
Step 60, Loss: 2.4263
Step 80, Loss: 2.4362
Step 100, Loss: 2.3836
Step 120, Loss: 2.3858
Step 140, Loss: 2.3864
Step 160, Loss: 2.3371
Step 180, Loss: 2.3347
Step 200, Loss: 2.3476
Step 220, Loss: 2.3478
Step 240, Loss: 2.3192
Step 260, Loss: 2.3306
Step 280, Loss: 2.3340
Step 300, Loss: 2.3433
Epoch 7 Loss: 2.3336
Epoch 8/100
Step 20, Loss: 2.3163
Step 40, Loss: 2.3823
Step 60, Loss: 2.4250
Step 80, Loss: 2.4349
Step 100, Loss: 2.3823
Step 120, Loss: 2.3844
Step 140, Loss: 2.3851
Step 160, Loss: 2.3358
Step 180, Loss: 2.3333
Step 200, Loss: 2.3463
Step 220, Loss: 2.3465
Step 240, Loss: 2.3179
Step 260, Loss: 2.3293
Step 280, Loss: 2.3327
Step 300, Loss: 2.3419
Epoch 8 Loss: 2.3323
Epoch 9/100
Step 20, Loss: 2.3150
Step 40, Loss: 2.3810
Step 60, Loss: 2.4237
Step 80, Loss: 2.4336
Step 100, Loss: 2.3810
Step 120, Loss: 2.3831
Step 140, Loss: 2.3838
Step 160, Loss: 2.3345
Step 180, Loss: 2.3320
Step 200, Loss: 2.3450
Step 220, Loss: 2.3452
Step 240, Loss: 2.3166
Step 260, Loss: 2.3280
Step 280, Loss: 2.3314
Step 300, Loss: 2.3406
Epoch 9 Loss: 2.3310
Epoch 10/100
Step 20, Loss: 2.3138
Step 40, Loss: 2.3797
Step 60, Loss: 2.4224
Step 80, Loss: 2.4323
Step 100, Loss: 2.3796
Step 120, Loss: 2.3818
Step 140, Loss: 2.3824
Step 160, Loss: 2.3332
Step 180, Loss: 2.3307
Step 200, Loss: 2.3437
Step 220, Loss: 2.3439
Step 240, Loss: 2.3153
Step 260, Loss: 2.3267
Step 280, Loss: 2.3301
Step 300, Loss: 2.3393
Epoch 10 Loss: 2.3297
Epoch 11/100
Step 20, Loss: 2.3126
Step 40, Loss: 2.3785
Step 60, Loss: 2.4211
Step 80, Loss: 2.4310
Step 100, Loss: 2.3783
Step 120, Loss: 2.3805
Step 140, Loss: 2.3811
Step 160, Loss: 2.3319
Step 180, Loss: 2.3294
Step 200, Loss: 2.3423
Step 220, Loss: 2.3426
Step 240, Loss: 2.3140
Step 260, Loss: 2.3254
Step 280, Loss: 2.3288
Step 300, Loss: 2.3380
Epoch 11 Loss: 2.3284
Epoch 12/100
Step 20, Loss: 2.3113
Step 40, Loss: 2.3772
Step 60, Loss: 2.4198
Step 80, Loss: 2.4297
Step 100, Loss: 2.3770
Step 120, Loss: 2.3792
Step 140, Loss: 2.3798
Step 160, Loss: 2.3306
Step 180, Loss: 2.3281
Step 200, Loss: 2.3410
Step 220, Loss: 2.3413
Step 240, Loss: 2.3127
Step 260, Loss: 2.3241
Step 280, Loss: 2.3275
Step 300, Loss: 2.3367
Epoch 12 Loss: 2.3271
Epoch 13/100
Step 20, Loss: 2.3101
Step 40, Loss: 2.3759
Step 60, Loss: 2.4186
Step 80, Loss: 2.4284
Step 100, Loss: 2.3757
Step 120, Loss: 2.3779
Step 140, Loss: 2.3785
Step 160, Loss: 2.3293
Step 180, Loss: 2.3268
Step 200, Loss: 2.3398
Step 220, Loss: 2.3400
Step 240, Loss: 2.3114
Step 260, Loss: 2.3228
Step 280, Loss: 2.3262
Step 300, Loss: 2.3354
Epoch 13 Loss: 2.3258
Epoch 14/100
Step 20, Loss: 2.3089
Step 40, Loss: 2.3747
Step 60, Loss: 2.4173
Step 80, Loss: 2.4271
Step 100, Loss: 2.3744
Step 120, Loss: 2.3766
Step 140, Loss: 2.3772
Step 160, Loss: 2.3280
Step 180, Loss: 2.3255
Step 200, Loss: 2.3384
Step 220, Loss: 2.3387
Step 240, Loss: 2.3101
Step 260, Loss: 2.3215
Step 280, Loss: 2.3249
Step 300, Loss: 2.3341
Epoch 14 Loss: 2.3245
Epoch 15/100
Step 20, Loss: 2.3076
Step 40, Loss: 2.3734
Step 60, Loss: 2.4160
Step 80, Loss: 2.4258
Step 100, Loss: 2.3731
Step 120, Loss: 2.3753
Step 140, Loss: 2.3759
Step 160, Loss: 2.3267
Step 180, Loss: 2.3242
Step 200, Loss: 2.3371
Step 220, Loss: 2.3374
Step 240, Loss: 2.3088
Step 260, Loss: 2.3202
Step 280, Loss: 2.3236
Step 300, Loss: 2.3328
Epoch 15 Loss: 2.3232
Epoch 16/100
Step 20, Loss: 2.3064
Step 40, Loss: 2.3722
Step 60, Loss: 2.4148
Step 80, Loss: 2.4245
Step 100, Loss: 2.3718
Step 120, Loss: 2.3740
Step 140, Loss: 2.3746
Step 160, Loss: 2.3254
Step 180, Loss: 2.3229
Step 200, Loss: 2.3359
Step 220, Loss: 2.3361
Step 240, Loss: 2.3075
Step 260, Loss: 2.3189
Step 280, Loss: 2.3223
Step 300, Loss: 2.3315
Epoch 16 Loss: 2.3219
Epoch 17/100
Step 20, Loss: 2.3052
Step 40, Loss: 2.3709
Step 60, Loss: 2.4135
Step 80, Loss: 2.4232
Step 100, Loss: 2.3705
Step 120, Loss: 2.3727
Step 140, Loss: 2.3732
Step 160, Loss: 2.3241
Step 180, Loss: 2.3216
Step 200, Loss: 2.3346
Step 220, Loss: 2.3348
Step 240, Loss: 2.3063
Step 260, Loss: 2.3176
Step 280, Loss: 2.3210
Step 300, Loss: 2.3302
Epoch 17 Loss: 2.3206
Epoch 18/100
Step 20, Loss: 2.3040
Step 40, Loss: 2.3697
Step 60, Loss: 2.4122
Step 80, Loss: 2.4219
Step 100, Loss: 2.3692
Step 120, Loss: 2.3714
Step 140, Loss: 2.3719
Step 160, Loss: 2.3228
Step 180, Loss: 2.3203
Step 200, Loss: 2.3333
Step 220, Loss: 2.3335
Step 240, Loss: 2.3050
Step 260, Loss: 2.3163
Step 280, Loss: 2.3197
Step 300, Loss: 2.3289
Epoch 18 Loss: 2.3193
Epoch 19/100
Step 20, Loss: 2.3028
Step 40, Loss: 2.3684
Step 60, Loss: 2.4110
Step 80, Loss: 2.4207
Step 100, Loss: 2.3679
Step 120, Loss: 2.3701
Step 140, Loss: 2.3706
Step 160, Loss: 2.3215
Step 180, Loss: 2.3190
Step 200, Loss: 2.3320
Step 220, Loss: 2.3322
Step 240, Loss: 2.3037
Step 260, Loss: 2.3151
Step 280, Loss: 2.3184
Step 300, Loss: 2.3276
Epoch 19 Loss: 2.3180
Epoch 20/100
Step 20, Loss: 2.3016
Step 40, Loss: 2.3672
Step 60, Loss: 2.4097
Step 80, Loss: 2.4194
Step 100, Loss: 2.3666
Step 120, Loss: 2.3688
Step 140, Loss: 2.3693
Step 160, Loss: 2.3202
Step 180, Loss: 2.3177
Step 200, Loss: 2.3307
Step 220, Loss: 2.3310
Step 240, Loss: 2.3024
Step 260, Loss: 2.3138
Step 280, Loss: 2.3171
Step 300, Loss: 2.3263
Epoch 20 Loss: 2.3167
Epoch 21/100
Step 20, Loss: 2.3004
Step 40, Loss: 2.3659
Step 60, Loss: 2.4085
Step 80, Loss: 2.4181
Step 100, Loss: 2.3653
Step 120, Loss: 2.3675
Step 140, Loss: 2.3680
Step 160, Loss: 2.3190
Step 180, Loss: 2.3165
Step 200, Loss: 2.3294
Step 220, Loss: 2.3297
Step 240, Loss: 2.3011
Step 260, Loss: 2.3125
Step 280, Loss: 2.3158
Step 300, Loss: 2.3250
Epoch 21 Loss: 2.3154
Epoch 22/100
Step 20, Loss: 2.2991
Step 40, Loss: 2.3647
Step 60, Loss: 2.4072
Step 80, Loss: 2.4168
Step 100, Loss: 2.3640
Step 120, Loss: 2.3663
Step 140, Loss: 2.3667
Step 160, Loss: 2.3177
Step 180, Loss: 2.3152
Step 200, Loss: 2.3282
Step 220, Loss: 2.3284
Step 240, Loss: 2.2999
Step 260, Loss: 2.3112
Step 280, Loss: 2.3146
Step 300, Loss: 2.3237
Epoch 22 Loss: 2.3142
Epoch 23/100
Step 20, Loss: 2.2980
Step 40, Loss: 2.3635
Step 60, Loss: 2.4060
Step 80, Loss: 2.4155
Step 100, Loss: 2.3627
Step 120, Loss: 2.3650
Step 140, Loss: 2.3655
Step 160, Loss: 2.3164
Step 180, Loss: 2.3139
Step 200, Loss: 2.3269
Step 220, Loss: 2.3271
Step 240, Loss: 2.2986
Step 260, Loss: 2.3100
Step 280, Loss: 2.3133
Step 300, Loss: 2.3225
Epoch 23 Loss: 2.3129
Epoch 24/100
Step 20, Loss: 2.2967
Step 40, Loss: 2.3622
Step 60, Loss: 2.4047
Step 80, Loss: 2.4143
Step 100, Loss: 2.3614
Step 120, Loss: 2.3637
Step 140, Loss: 2.3642
Step 160, Loss: 2.3151
Step 180, Loss: 2.3126
Step 200, Loss: 2.3256
Step 220, Loss: 2.3259
Step 240, Loss: 2.2974
Step 260, Loss: 2.3087
Step 280, Loss: 2.3120
Step 300, Loss: 2.3212
Epoch 24 Loss: 2.3116
Epoch 25/100
Step 20, Loss: 2.2956
Step 40, Loss: 2.3610
Step 60, Loss: 2.4035
Step 80, Loss: 2.4130
Step 100, Loss: 2.3602
Step 120, Loss: 2.3624
Step 140, Loss: 2.3629
Step 160, Loss: 2.3139
Step 180, Loss: 2.3114
Step 200, Loss: 2.3243
Step 220, Loss: 2.3246
Step 240, Loss: 2.2961
Step 260, Loss: 2.3074
Step 280, Loss: 2.3108
Step 300, Loss: 2.3199
Epoch 25 Loss: 2.3103
Epoch 26/100
Step 20, Loss: 2.2944
Step 40, Loss: 2.3598
Step 60, Loss: 2.4023
Step 80, Loss: 2.4118
Step 100, Loss: 2.3589
Step 120, Loss: 2.3612
Step 140, Loss: 2.3616
Step 160, Loss: 2.3126
Step 180, Loss: 2.3101
Step 200, Loss: 2.3231
Step 220, Loss: 2.3233
Step 240, Loss: 2.2948
Step 260, Loss: 2.3062
Step 280, Loss: 2.3095
Step 300, Loss: 2.3186
Epoch 26 Loss: 2.3091
Epoch 27/100
Step 20, Loss: 2.2932
Step 40, Loss: 2.3585
Step 60, Loss: 2.4010
Step 80, Loss: 2.4105
Step 100, Loss: 2.3576
Step 120, Loss: 2.3599
Step 140, Loss: 2.3603
Step 160, Loss: 2.3113
Step 180, Loss: 2.3088
Step 200, Loss: 2.3218
Step 220, Loss: 2.3220
Step 240, Loss: 2.2936
Step 260, Loss: 2.3049
Step 280, Loss: 2.3082
Step 300, Loss: 2.3174
Epoch 27 Loss: 2.3078
Epoch 28/100
Step 20, Loss: 2.2920
Step 40, Loss: 2.3573
Step 60, Loss: 2.3998
Step 80, Loss: 2.4092
Step 100, Loss: 2.3563
Step 120, Loss: 2.3586
Step 140, Loss: 2.3590
Step 160, Loss: 2.3101
Step 180, Loss: 2.3076
Step 200, Loss: 2.3205
Step 220, Loss: 2.3208
Step 240, Loss: 2.2923
Step 260, Loss: 2.3037
Step 280, Loss: 2.3069
Step 300, Loss: 2.3161
Epoch 28 Loss: 2.3065
Epoch 29/100
Step 20, Loss: 2.2908
Step 40, Loss: 2.3561
Step 60, Loss: 2.3985
Step 80, Loss: 2.4080
Step 100, Loss: 2.3551
Step 120, Loss: 2.3574
Step 140, Loss: 2.3578
Step 160, Loss: 2.3088
Step 180, Loss: 2.3063
Step 200, Loss: 2.3193
Step 220, Loss: 2.3195
Step 240, Loss: 2.2911
Step 260, Loss: 2.3024
Step 280, Loss: 2.3057
Step 300, Loss: 2.3148
Epoch 29 Loss: 2.3053
Epoch 30/100
Step 20, Loss: 2.2896
Step 40, Loss: 2.3549
Step 60, Loss: 2.3973
Step 80, Loss: 2.4067
Step 100, Loss: 2.3538
Step 120, Loss: 2.3561
Step 140, Loss: 2.3565
Step 160, Loss: 2.3076
Step 180, Loss: 2.3050
Step 200, Loss: 2.3180
Step 220, Loss: 2.3183
Step 240, Loss: 2.2898
Step 260, Loss: 2.3011
Step 280, Loss: 2.3044
Step 300, Loss: 2.3136
Epoch 30 Loss: 2.3040
Epoch 31/100
Step 20, Loss: 2.2884
Step 40, Loss: 2.3536
Step 60, Loss: 2.3961
Step 80, Loss: 2.4055
Step 100, Loss: 2.3525
Step 120, Loss: 2.3548
Step 140, Loss: 2.3552
Step 160, Loss: 2.3063
Step 180, Loss: 2.3038
Step 200, Loss: 2.3168
Step 220, Loss: 2.3170
Step 240, Loss: 2.2886
Step 260, Loss: 2.2999
Step 280, Loss: 2.3032
Step 300, Loss: 2.3123
Epoch 31 Loss: 2.3027
Epoch 32/100
Step 20, Loss: 2.2872
Step 40, Loss: 2.3524
Step 60, Loss: 2.3949
Step 80, Loss: 2.4042
Step 100, Loss: 2.3513
Step 120, Loss: 2.3536
Step 140, Loss: 2.3540
Step 160, Loss: 2.3051
Step 180, Loss: 2.3025
Step 200, Loss: 2.3155
Step 220, Loss: 2.3158
Step 240, Loss: 2.2873
Step 260, Loss: 2.2987
Step 280, Loss: 2.3019
Step 300, Loss: 2.3110
Epoch 32 Loss: 2.3015
Epoch 33/100
Step 20, Loss: 2.2860
Step 40, Loss: 2.3512
Step 60, Loss: 2.3936
Step 80, Loss: 2.4030
Step 100, Loss: 2.3500
Step 120, Loss: 2.3523
Step 140, Loss: 2.3527
Step 160, Loss: 2.3038
Step 180, Loss: 2.3013
Step 200, Loss: 2.3143
Step 220, Loss: 2.3145
Step 240, Loss: 2.2861
Step 260, Loss: 2.2974
Step 280, Loss: 2.3007
Step 300, Loss: 2.3098
Epoch 33 Loss: 2.3002
Epoch 34/100
Step 20, Loss: 2.2848
Step 40, Loss: 2.3500
Step 60, Loss: 2.3924
Step 80, Loss: 2.4017
Step 100, Loss: 2.3487
Step 120, Loss: 2.3511
Step 140, Loss: 2.3514
Step 160, Loss: 2.3026
Step 180, Loss: 2.3000
Step 200, Loss: 2.3130
Step 220, Loss: 2.3133
Step 240, Loss: 2.2849
Step 260, Loss: 2.2962
Step 280, Loss: 2.2994
Step 300, Loss: 2.3085
Epoch 34 Loss: 2.2990
Epoch 35/100
Step 20, Loss: 2.2837
Step 40, Loss: 2.3488
Step 60, Loss: 2.3912
Step 80, Loss: 2.4005
Step 100, Loss: 2.3475
Step 120, Loss: 2.3498
Step 140, Loss: 2.3502
Step 160, Loss: 2.3013
Step 180, Loss: 2.2988
Step 200, Loss: 2.3118
Step 220, Loss: 2.3120
Step 240, Loss: 2.2836
Step 260, Loss: 2.2949
Step 280, Loss: 2.2982
Step 300, Loss: 2.3073
Epoch 35 Loss: 2.2977
Epoch 36/100
Step 20, Loss: 2.2825
Step 40, Loss: 2.3476
Step 60, Loss: 2.3900
Step 80, Loss: 2.3992
Step 100, Loss: 2.3462
Step 120, Loss: 2.3486
Step 140, Loss: 2.3489
Step 160, Loss: 2.3001
Step 180, Loss: 2.2975
Step 200, Loss: 2.3106
Step 220, Loss: 2.3108
Step 240, Loss: 2.2824
Step 260, Loss: 2.2937
Step 280, Loss: 2.2969
Step 300, Loss: 2.3060
Epoch 36 Loss: 2.2965
Epoch 37/100
Step 20, Loss: 2.2813
Step 40, Loss: 2.3464
Step 60, Loss: 2.3887
Step 80, Loss: 2.3980
Step 100, Loss: 2.3450
Step 120, Loss: 2.3474
Step 140, Loss: 2.3477
Step 160, Loss: 2.2989
Step 180, Loss: 2.2963
Step 200, Loss: 2.3093
Step 220, Loss: 2.3095
Step 240, Loss: 2.2812
Step 260, Loss: 2.2925
Step 280, Loss: 2.2957
Step 300, Loss: 2.3048
Epoch 37 Loss: 2.2952
Epoch 38/100
Step 20, Loss: 2.2802
Step 40, Loss: 2.3452
Step 60, Loss: 2.3875
Step 80, Loss: 2.3968
Step 100, Loss: 2.3438
Step 120, Loss: 2.3461
Step 140, Loss: 2.3464
Step 160, Loss: 2.2976
Step 180, Loss: 2.2950
Step 200, Loss: 2.3081
Step 220, Loss: 2.3083
Step 240, Loss: 2.2799
Step 260, Loss: 2.2912
Step 280, Loss: 2.2945
Step 300, Loss: 2.3036
Epoch 38 Loss: 2.2940
Epoch 39/100
Step 20, Loss: 2.2790
Step 40, Loss: 2.3440
Step 60, Loss: 2.3863
Step 80, Loss: 2.3955
Step 100, Loss: 2.3425
Step 120, Loss: 2.3449
Step 140, Loss: 2.3452
Step 160, Loss: 2.2964
Step 180, Loss: 2.2938
Step 200, Loss: 2.3068
Step 220, Loss: 2.3071
Step 240, Loss: 2.2787
Step 260, Loss: 2.2900
Step 280, Loss: 2.2932
Step 300, Loss: 2.3023
Epoch 39 Loss: 2.2928
Epoch 40/100
Step 20, Loss: 2.2778
Step 40, Loss: 2.3428
Step 60, Loss: 2.3851
Step 80, Loss: 2.3943
Step 100, Loss: 2.3413
Step 120, Loss: 2.3436
Step 140, Loss: 2.3439
Step 160, Loss: 2.2952
Step 180, Loss: 2.2926
Step 200, Loss: 2.3056
Step 220, Loss: 2.3058
Step 240, Loss: 2.2775
Step 260, Loss: 2.2888
Step 280, Loss: 2.2920
Step 300, Loss: 2.3011
Epoch 40 Loss: 2.2915
Epoch 41/100
Step 20, Loss: 2.2767
Step 40, Loss: 2.3416
Step 60, Loss: 2.3839
Step 80, Loss: 2.3931
Step 100, Loss: 2.3400
Step 120, Loss: 2.3424
Step 140, Loss: 2.3427
Step 160, Loss: 2.2939
Step 180, Loss: 2.2913
Step 200, Loss: 2.3044
Step 220, Loss: 2.3046
Step 240, Loss: 2.2763
Step 260, Loss: 2.2875
Step 280, Loss: 2.2907
Step 300, Loss: 2.2998
Epoch 41 Loss: 2.2903
Epoch 42/100
Step 20, Loss: 2.2755
Step 40, Loss: 2.3404
Step 60, Loss: 2.3827
Step 80, Loss: 2.3919
Step 100, Loss: 2.3388
Step 120, Loss: 2.3412
Step 140, Loss: 2.3414
Step 160, Loss: 2.2927
Step 180, Loss: 2.2901
Step 200, Loss: 2.3032
Step 220, Loss: 2.3034
Step 240, Loss: 2.2750
Step 260, Loss: 2.2863
Step 280, Loss: 2.2895
Step 300, Loss: 2.2986
Epoch 42 Loss: 2.2891
Epoch 43/100
Step 20, Loss: 2.2744
Step 40, Loss: 2.3392
Step 60, Loss: 2.3815
Step 80, Loss: 2.3906
Step 100, Loss: 2.3376
Step 120, Loss: 2.3400
Step 140, Loss: 2.3402
Step 160, Loss: 2.2915
Step 180, Loss: 2.2889
Step 200, Loss: 2.3019
Step 220, Loss: 2.3022
Step 240, Loss: 2.2738
Step 260, Loss: 2.2851
Step 280, Loss: 2.2883
Step 300, Loss: 2.2974
Epoch 43 Loss: 2.2878
Epoch 44/100
Step 20, Loss: 2.2732
Step 40, Loss: 2.3380
Step 60, Loss: 2.3803
Step 80, Loss: 2.3894
Step 100, Loss: 2.3363
Step 120, Loss: 2.3387
Step 140, Loss: 2.3389
Step 160, Loss: 2.2903
Step 180, Loss: 2.2877
Step 200, Loss: 2.3007
Step 220, Loss: 2.3009
Step 240, Loss: 2.2726
Step 260, Loss: 2.2839
Step 280, Loss: 2.2871
Step 300, Loss: 2.2961
Epoch 44 Loss: 2.2866
Epoch 45/100
Step 20, Loss: 2.2721
Step 40, Loss: 2.3368
Step 60, Loss: 2.3791
Step 80, Loss: 2.3882
Step 100, Loss: 2.3351
Step 120, Loss: 2.3375
Step 140, Loss: 2.3377
Step 160, Loss: 2.2890
Step 180, Loss: 2.2864
Step 200, Loss: 2.2995
Step 220, Loss: 2.2997
Step 240, Loss: 2.2714
Step 260, Loss: 2.2827
Step 280, Loss: 2.2858
Step 300, Loss: 2.2949
Epoch 45 Loss: 2.2854
Epoch 46/100
Step 20, Loss: 2.2709
Step 40, Loss: 2.3357
Step 60, Loss: 2.3779
Step 80, Loss: 2.3870
Step 100, Loss: 2.3339
Step 120, Loss: 2.3363
Step 140, Loss: 2.3365
Step 160, Loss: 2.2878
Step 180, Loss: 2.2852
Step 200, Loss: 2.2983
Step 220, Loss: 2.2985
Step 240, Loss: 2.2702
Step 260, Loss: 2.2815
Step 280, Loss: 2.2846
Step 300, Loss: 2.2937
Epoch 46 Loss: 2.2842
Epoch 47/100
Step 20, Loss: 2.2698
Step 40, Loss: 2.3345
Step 60, Loss: 2.3767
Step 80, Loss: 2.3858
Step 100, Loss: 2.3326
Step 120, Loss: 2.3351
Step 140, Loss: 2.3352
Step 160, Loss: 2.2866
Step 180, Loss: 2.2840
Step 200, Loss: 2.2971
Step 220, Loss: 2.2973
Step 240, Loss: 2.2690
Step 260, Loss: 2.2803
Step 280, Loss: 2.2834
Step 300, Loss: 2.2925
Epoch 47 Loss: 2.2830
Epoch 48/100
Step 20, Loss: 2.2686
Step 40, Loss: 2.3333
Step 60, Loss: 2.3755
Step 80, Loss: 2.3846
Step 100, Loss: 2.3314
Step 120, Loss: 2.3339
Step 140, Loss: 2.3340
Step 160, Loss: 2.2854
Step 180, Loss: 2.2828
Step 200, Loss: 2.2958
Step 220, Loss: 2.2961
Step 240, Loss: 2.2678
Step 260, Loss: 2.2790
Step 280, Loss: 2.2822
Step 300, Loss: 2.2913
Epoch 48 Loss: 2.2817
Epoch 49/100
Step 20, Loss: 2.2675
Step 40, Loss: 2.3321
Step 60, Loss: 2.3744
Step 80, Loss: 2.3834
Step 100, Loss: 2.3302
Step 120, Loss: 2.3326
Step 140, Loss: 2.3328
Step 160, Loss: 2.2842
Step 180, Loss: 2.2816
Step 200, Loss: 2.2946
Step 220, Loss: 2.2949
Step 240, Loss: 2.2666
Step 260, Loss: 2.2778
Step 280, Loss: 2.2810
Step 300, Loss: 2.2900
Epoch 49 Loss: 2.2805
Epoch 50/100
Step 20, Loss: 2.2664
Step 40, Loss: 2.3310
Step 60, Loss: 2.3732
Step 80, Loss: 2.3822
Step 100, Loss: 2.3290
Step 120, Loss: 2.3314
Step 140, Loss: 2.3316
Step 160, Loss: 2.2830
Step 180, Loss: 2.2804
Step 200, Loss: 2.2934
Step 220, Loss: 2.2937
Step 240, Loss: 2.2654
Step 260, Loss: 2.2766
Step 280, Loss: 2.2798
Step 300, Loss: 2.2888
Epoch 50 Loss: 2.2793
Epoch 51/100
Step 20, Loss: 2.2652
Step 40, Loss: 2.3298
Step 60, Loss: 2.3720
Step 80, Loss: 2.3810
Step 100, Loss: 2.3278
Step 120, Loss: 2.3302
Step 140, Loss: 2.3304
Step 160, Loss: 2.2818
Step 180, Loss: 2.2792
Step 200, Loss: 2.2922
Step 220, Loss: 2.2925
Step 240, Loss: 2.2642
Step 260, Loss: 2.2754
Step 280, Loss: 2.2786
Step 300, Loss: 2.2876
Epoch 51 Loss: 2.2781
Epoch 52/100
Step 20, Loss: 2.2641
Step 40, Loss: 2.3286
Step 60, Loss: 2.3708
Step 80, Loss: 2.3798
Step 100, Loss: 2.3266
Step 120, Loss: 2.3290
Step 140, Loss: 2.3291
Step 160, Loss: 2.2806
Step 180, Loss: 2.2780
Step 200, Loss: 2.2910
Step 220, Loss: 2.2913
Step 240, Loss: 2.2630
Step 260, Loss: 2.2742
Step 280, Loss: 2.2774
Step 300, Loss: 2.2864
Epoch 52 Loss: 2.2769
Epoch 53/100
Step 20, Loss: 2.2630
Step 40, Loss: 2.3275
Step 60, Loss: 2.3696
Step 80, Loss: 2.3786
Step 100, Loss: 2.3254
Step 120, Loss: 2.3278
Step 140, Loss: 2.3279
Step 160, Loss: 2.2794
Step 180, Loss: 2.2768
Step 200, Loss: 2.2898
Step 220, Loss: 2.2901
Step 240, Loss: 2.2618
Step 260, Loss: 2.2730
Step 280, Loss: 2.2762
Step 300, Loss: 2.2852
Epoch 53 Loss: 2.2757
Epoch 54/100
Step 20, Loss: 2.2619
Step 40, Loss: 2.3263
Step 60, Loss: 2.3685

In [11]:
# save new checkpoint
torch.save({
    "model_state": model.state_dict(),
    "optimizer_state": optimizer.state_dict()
}, "model_checkpoint_400_epochs.pth")

In [12]:
# more training (continue from checkpoint)
import torch
import torch.nn as nn
import torch.optim as optim

model = ANN()
checkpoint = torch.load("model_checkpoint_400_epochs.pth", map_location="cuda" if torch.cuda.is_available() else "cpu")

# restore model + optimizer
model.load_state_dict(checkpoint["model_state"])
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

optimizer = optim.Adam(model.parameters(), lr=1e-4)
optimizer.load_state_dict(checkpoint["optimizer_state"])
criterion = nn.CrossEntropyLoss()

# train 100 more epochs
train_model("train.parquet", model, optimizer, criterion, device, epochs=100, batch_size=512)

Epoch 1/100
Step 20, Loss: 2.2116
Step 40, Loss: 2.2744
Step 60, Loss: 2.3160
Step 80, Loss: 2.3240
Step 100, Loss: 2.2701
Step 120, Loss: 2.2729
Step 140, Loss: 2.2724
Step 160, Loss: 2.2246
Step 180, Loss: 2.2218
Step 200, Loss: 2.2350
Step 220, Loss: 2.2352
Step 240, Loss: 2.2073
Step 260, Loss: 2.2184
Step 280, Loss: 2.2212
Step 300, Loss: 2.2301
Epoch 1 Loss: 2.2207
Epoch 2/100
Step 20, Loss: 2.2106
Step 40, Loss: 2.2733
Step 60, Loss: 2.3149
Step 80, Loss: 2.3229
Step 100, Loss: 2.2691
Step 120, Loss: 2.2718
Step 140, Loss: 2.2713
Step 160, Loss: 2.2235
Step 180, Loss: 2.2208
Step 200, Loss: 2.2339
Step 220, Loss: 2.2341
Step 240, Loss: 2.2063
Step 260, Loss: 2.2173
Step 280, Loss: 2.2201
Step 300, Loss: 2.2290
Epoch 2 Loss: 2.2196
Epoch 3/100
Step 20, Loss: 2.2095
Step 40, Loss: 2.2722
Step 60, Loss: 2.3139
Step 80, Loss: 2.3218
Step 100, Loss: 2.2680
Step 120, Loss: 2.2707
Step 140, Loss: 2.2702
Step 160, Loss: 2.2224
Step 180, Loss: 2.2197
Step 200, Loss: 2.2328
Step 220, Loss: 2.2330
Step 240, Loss: 2.2052
Step 260, Loss: 2.2162
Step 280, Loss: 2.2190
Step 300, Loss: 2.2279
Epoch 3 Loss: 2.2185
Epoch 4/100
Step 20, Loss: 2.2085
Step 40, Loss: 2.2712
Step 60, Loss: 2.3128
Step 80, Loss: 2.3207
Step 100, Loss: 2.2669
Step 120, Loss: 2.2696
Step 140, Loss: 2.2691
Step 160, Loss: 2.2214
Step 180, Loss: 2.2186
Step 200, Loss: 2.2318
Step 220, Loss: 2.2319
Step 240, Loss: 2.2041
Step 260, Loss: 2.2152
Step 280, Loss: 2.2179
Step 300, Loss: 2.2268
Epoch 4 Loss: 2.2174
Epoch 5/100
Step 20, Loss: 2.2075
Step 40, Loss: 2.2701
Step 60, Loss: 2.3117
Step 80, Loss: 2.3196
Step 100, Loss: 2.2658
Step 120, Loss: 2.2685
Step 140, Loss: 2.2680
Step 160, Loss: 2.2203
Step 180, Loss: 2.2175
Step 200, Loss: 2.2307
Step 220, Loss: 2.2308
Step 240, Loss: 2.2030
Step 260, Loss: 2.2141
Step 280, Loss: 2.2169
Step 300, Loss: 2.2257
Epoch 5 Loss: 2.2163
Epoch 6/100
Step 20, Loss: 2.2065
Step 40, Loss: 2.2691
Step 60, Loss: 2.3107
Step 80, Loss: 2.3186
Step 100, Loss: 2.2647
Step 120, Loss: 2.2675
Step 140, Loss: 2.2669
Step 160, Loss: 2.2192
Step 180, Loss: 2.2164
Step 200, Loss: 2.2296
Step 220, Loss: 2.2297
Step 240, Loss: 2.2020
Step 260, Loss: 2.2130
Step 280, Loss: 2.2158
Step 300, Loss: 2.2246
Epoch 6 Loss: 2.2152
Epoch 7/100
Step 20, Loss: 2.2055
Step 40, Loss: 2.2681
Step 60, Loss: 2.3096
Step 80, Loss: 2.3175
Step 100, Loss: 2.2636
Step 120, Loss: 2.2664
Step 140, Loss: 2.2658
Step 160, Loss: 2.2181
Step 180, Loss: 2.2153
Step 200, Loss: 2.2285
Step 220, Loss: 2.2287
Step 240, Loss: 2.2009
Step 260, Loss: 2.2119
Step 280, Loss: 2.2147
Step 300, Loss: 2.2235
Epoch 7 Loss: 2.2141
Epoch 8/100
Step 20, Loss: 2.2045
Step 40, Loss: 2.2670
Step 60, Loss: 2.3086
Step 80, Loss: 2.3164
Step 100, Loss: 2.2625
Step 120, Loss: 2.2653
Step 140, Loss: 2.2647
Step 160, Loss: 2.2170
Step 180, Loss: 2.2143
Step 200, Loss: 2.2274
Step 220, Loss: 2.2276
Step 240, Loss: 2.1998
Step 260, Loss: 2.2109
Step 280, Loss: 2.2136
Step 300, Loss: 2.2224
Epoch 8 Loss: 2.2131
Epoch 9/100
Step 20, Loss: 2.2035
Step 40, Loss: 2.2660
Step 60, Loss: 2.3075
Step 80, Loss: 2.3153
Step 100, Loss: 2.2614
Step 120, Loss: 2.2642
Step 140, Loss: 2.2636
Step 160, Loss: 2.2160
Step 180, Loss: 2.2132
Step 200, Loss: 2.2264
Step 220, Loss: 2.2265
Step 240, Loss: 2.1987
Step 260, Loss: 2.2098
Step 280, Loss: 2.2125
Step 300, Loss: 2.2214
Epoch 9 Loss: 2.2120
Epoch 10/100
Step 20, Loss: 2.2025
Step 40, Loss: 2.2649
Step 60, Loss: 2.3065
Step 80, Loss: 2.3143
Step 100, Loss: 2.2604
Step 120, Loss: 2.2632
Step 140, Loss: 2.2626
Step 160, Loss: 2.2149
Step 180, Loss: 2.2121
Step 200, Loss: 2.2253
Step 220, Loss: 2.2254
Step 240, Loss: 2.1977
Step 260, Loss: 2.2087
Step 280, Loss: 2.2115
Step 300, Loss: 2.2203
Epoch 10 Loss: 2.2109
Epoch 11/100
Step 20, Loss: 2.2015
Step 40, Loss: 2.2639
Step 60, Loss: 2.3054
Step 80, Loss: 2.3132
Step 100, Loss: 2.2593
Step 120, Loss: 2.2621
Step 140, Loss: 2.2615
Step 160, Loss: 2.2138
Step 180, Loss: 2.2110
Step 200, Loss: 2.2242
Step 220, Loss: 2.2244
Step 240, Loss: 2.1966
Step 260, Loss: 2.2077
Step 280, Loss: 2.2104
Step 300, Loss: 2.2192
Epoch 11 Loss: 2.2098
Epoch 12/100
Step 20, Loss: 2.2005
Step 40, Loss: 2.2629
Step 60, Loss: 2.3044
Step 80, Loss: 2.3122
Step 100, Loss: 2.2582
Step 120, Loss: 2.2610
Step 140, Loss: 2.2604
Step 160, Loss: 2.2128
Step 180, Loss: 2.2100
Step 200, Loss: 2.2231
Step 220, Loss: 2.2233
Step 240, Loss: 2.1956
Step 260, Loss: 2.2066
Step 280, Loss: 2.2093
Step 300, Loss: 2.2181
Epoch 12 Loss: 2.2088
Epoch 13/100
Step 20, Loss: 2.1995
Step 40, Loss: 2.2618
Step 60, Loss: 2.3033
Step 80, Loss: 2.3111
Step 100, Loss: 2.2571
Step 120, Loss: 2.2599
Step 140, Loss: 2.2593
Step 160, Loss: 2.2117
Step 180, Loss: 2.2089
Step 200, Loss: 2.2221
Step 220, Loss: 2.2222
Step 240, Loss: 2.1945
Step 260, Loss: 2.2055
Step 280, Loss: 2.2082
Step 300, Loss: 2.2170
Epoch 13 Loss: 2.2077
Epoch 14/100
Step 20, Loss: 2.1985
Step 40, Loss: 2.2608
Step 60, Loss: 2.3023
Step 80, Loss: 2.3100
Step 100, Loss: 2.2561
Step 120, Loss: 2.2589
Step 140, Loss: 2.2582
Step 160, Loss: 2.2106
Step 180, Loss: 2.2078
Step 200, Loss: 2.2210
Step 220, Loss: 2.2212
Step 240, Loss: 2.1934
Step 260, Loss: 2.2045
Step 280, Loss: 2.2072
Step 300, Loss: 2.2160
Epoch 14 Loss: 2.2066
Epoch 15/100
Step 20, Loss: 2.1975
Step 40, Loss: 2.2598
Step 60, Loss: 2.3013
Step 80, Loss: 2.3090
Step 100, Loss: 2.2550
Step 120, Loss: 2.2578
Step 140, Loss: 2.2571
Step 160, Loss: 2.2096
Step 180, Loss: 2.2068
Step 200, Loss: 2.2199
Step 220, Loss: 2.2201
Step 240, Loss: 2.1924
Step 260, Loss: 2.2034
Step 280, Loss: 2.2061
Step 300, Loss: 2.2149
Epoch 15 Loss: 2.2055
Epoch 16/100
Step 20, Loss: 2.1966
Step 40, Loss: 2.2588
Step 60, Loss: 2.3002
Step 80, Loss: 2.3079
Step 100, Loss: 2.2539
Step 120, Loss: 2.2568
Step 140, Loss: 2.2561
Step 160, Loss: 2.2085
Step 180, Loss: 2.2057
Step 200, Loss: 2.2189
Step 220, Loss: 2.2190
Step 240, Loss: 2.1913
Step 260, Loss: 2.2024
Step 280, Loss: 2.2051
Step 300, Loss: 2.2138
Epoch 16 Loss: 2.2045
Epoch 17/100
Step 20, Loss: 2.1955
Step 40, Loss: 2.2577
Step 60, Loss: 2.2992
Step 80, Loss: 2.3069
Step 100, Loss: 2.2529
Step 120, Loss: 2.2557
Step 140, Loss: 2.2550
Step 160, Loss: 2.2075
Step 180, Loss: 2.2046
Step 200, Loss: 2.2178
Step 220, Loss: 2.2180
Step 240, Loss: 2.1903
Step 260, Loss: 2.2013
Step 280, Loss: 2.2040
Step 300, Loss: 2.2128
Epoch 17 Loss: 2.2034
Epoch 18/100
Step 20, Loss: 2.1946
Step 40, Loss: 2.2567
Step 60, Loss: 2.2982
Step 80, Loss: 2.3058
Step 100, Loss: 2.2518
Step 120, Loss: 2.2546
Step 140, Loss: 2.2539
Step 160, Loss: 2.2064
Step 180, Loss: 2.2036
Step 200, Loss: 2.2168
Step 220, Loss: 2.2169
Step 240, Loss: 2.1892
Step 260, Loss: 2.2002
Step 280, Loss: 2.2029
Step 300, Loss: 2.2117
Epoch 18 Loss: 2.2024
Epoch 19/100
Step 20, Loss: 2.1936
Step 40, Loss: 2.2557
Step 60, Loss: 2.2971
Step 80, Loss: 2.3048
Step 100, Loss: 2.2507
Step 120, Loss: 2.2536
Step 140, Loss: 2.2529
Step 160, Loss: 2.2053
Step 180, Loss: 2.2025
Step 200, Loss: 2.2157
Step 220, Loss: 2.2159
Step 240, Loss: 2.1882
Step 260, Loss: 2.1992
Step 280, Loss: 2.2019
Step 300, Loss: 2.2107
Epoch 19 Loss: 2.2013
Epoch 20/100
Step 20, Loss: 2.1926
Step 40, Loss: 2.2547
Step 60, Loss: 2.2961
Step 80, Loss: 2.3037
Step 100, Loss: 2.2497
Step 120, Loss: 2.2525
Step 140, Loss: 2.2518
Step 160, Loss: 2.2043
Step 180, Loss: 2.2015
Step 200, Loss: 2.2147
Step 220, Loss: 2.2148
Step 240, Loss: 2.1871
Step 260, Loss: 2.1981
Step 280, Loss: 2.2008
Step 300, Loss: 2.2096
Epoch 20 Loss: 2.2002
Epoch 21/100
Step 20, Loss: 2.1916
Step 40, Loss: 2.2536
Step 60, Loss: 2.2951
Step 80, Loss: 2.3027
Step 100, Loss: 2.2486
Step 120, Loss: 2.2515
Step 140, Loss: 2.2507
Step 160, Loss: 2.2032
Step 180, Loss: 2.2004
Step 200, Loss: 2.2136
Step 220, Loss: 2.2138
Step 240, Loss: 2.1861
Step 260, Loss: 2.1971
Step 280, Loss: 2.1998
Step 300, Loss: 2.2085
Epoch 21 Loss: 2.1992
Epoch 22/100
Step 20, Loss: 2.1906
Step 40, Loss: 2.2526
Step 60, Loss: 2.2940
Step 80, Loss: 2.3016
Step 100, Loss: 2.2476
Step 120, Loss: 2.2504
Step 140, Loss: 2.2497
Step 160, Loss: 2.2022
Step 180, Loss: 2.1994
Step 200, Loss: 2.2126
Step 220, Loss: 2.2127
Step 240, Loss: 2.1850
Step 260, Loss: 2.1960
Step 280, Loss: 2.1987
Step 300, Loss: 2.2075
Epoch 22 Loss: 2.1981
Epoch 23/100
Step 20, Loss: 2.1896
Step 40, Loss: 2.2516
Step 60, Loss: 2.2930
Step 80, Loss: 2.3006
Step 100, Loss: 2.2465
Step 120, Loss: 2.2494
Step 140, Loss: 2.2486
Step 160, Loss: 2.2011
Step 180, Loss: 2.1983
Step 200, Loss: 2.2115
Step 220, Loss: 2.2117
Step 240, Loss: 2.1840
Step 260, Loss: 2.1950
Step 280, Loss: 2.1977
Step 300, Loss: 2.2064
Epoch 23 Loss: 2.1971
Epoch 24/100
Step 20, Loss: 2.1887
Step 40, Loss: 2.2506
Step 60, Loss: 2.2920
Step 80, Loss: 2.2996
Step 100, Loss: 2.2455
Step 120, Loss: 2.2483
Step 140, Loss: 2.2476
Step 160, Loss: 2.2001
Step 180, Loss: 2.1973
Step 200, Loss: 2.2105
Step 220, Loss: 2.2106
Step 240, Loss: 2.1830
Step 260, Loss: 2.1940
Step 280, Loss: 2.1966
Step 300, Loss: 2.2054
Epoch 24 Loss: 2.1960
Epoch 25/100
Step 20, Loss: 2.1877
Step 40, Loss: 2.2496
Step 60, Loss: 2.2910
Step 80, Loss: 2.2985
Step 100, Loss: 2.2444
Step 120, Loss: 2.2473
Step 140, Loss: 2.2465
Step 160, Loss: 2.1991
Step 180, Loss: 2.1962
Step 200, Loss: 2.2094
Step 220, Loss: 2.2096
Step 240, Loss: 2.1819
Step 260, Loss: 2.1929
Step 280, Loss: 2.1956
Step 300, Loss: 2.2043
Epoch 25 Loss: 2.1950
Epoch 26/100
Step 20, Loss: 2.1867
Step 40, Loss: 2.2486
Step 60, Loss: 2.2900
Step 80, Loss: 2.2975
Step 100, Loss: 2.2434
Step 120, Loss: 2.2462
Step 140, Loss: 2.2454
Step 160, Loss: 2.1980
Step 180, Loss: 2.1952
Step 200, Loss: 2.2084
Step 220, Loss: 2.2085
Step 240, Loss: 2.1809
Step 260, Loss: 2.1919
Step 280, Loss: 2.1945
Step 300, Loss: 2.2033
Epoch 26 Loss: 2.1939
Epoch 27/100
Step 20, Loss: 2.1858
Step 40, Loss: 2.2476
Step 60, Loss: 2.2889
Step 80, Loss: 2.2965
Step 100, Loss: 2.2423
Step 120, Loss: 2.2452
Step 140, Loss: 2.2444
Step 160, Loss: 2.1970
Step 180, Loss: 2.1941
Step 200, Loss: 2.2073
Step 220, Loss: 2.2075
Step 240, Loss: 2.1799
Step 260, Loss: 2.1909
Step 280, Loss: 2.1935
Step 300, Loss: 2.2022
Epoch 27 Loss: 2.1929
Epoch 28/100
Step 20, Loss: 2.1848
Step 40, Loss: 2.2466
Step 60, Loss: 2.2879
Step 80, Loss: 2.2954
Step 100, Loss: 2.2413
Step 120, Loss: 2.2442
Step 140, Loss: 2.2433
Step 160, Loss: 2.1960
Step 180, Loss: 2.1931
Step 200, Loss: 2.2063
Step 220, Loss: 2.2064
Step 240, Loss: 2.1788
Step 260, Loss: 2.1898
Step 280, Loss: 2.1924
Step 300, Loss: 2.2012
Epoch 28 Loss: 2.1919
Epoch 29/100
Step 20, Loss: 2.1838
Step 40, Loss: 2.2456
Step 60, Loss: 2.2869
Step 80, Loss: 2.2944
Step 100, Loss: 2.2402
Step 120, Loss: 2.2431
Step 140, Loss: 2.2423
Step 160, Loss: 2.1949
Step 180, Loss: 2.1921
Step 200, Loss: 2.2053
Step 220, Loss: 2.2054
Step 240, Loss: 2.1778
Step 260, Loss: 2.1888
Step 280, Loss: 2.1914
Step 300, Loss: 2.2001
Epoch 29 Loss: 2.1908
Epoch 30/100
Step 20, Loss: 2.1829
Step 40, Loss: 2.2446
Step 60, Loss: 2.2859
Step 80, Loss: 2.2934
Step 100, Loss: 2.2392
Step 120, Loss: 2.2421
Step 140, Loss: 2.2412
Step 160, Loss: 2.1939
Step 180, Loss: 2.1910
Step 200, Loss: 2.2042
Step 220, Loss: 2.2044
Step 240, Loss: 2.1768
Step 260, Loss: 2.1878
Step 280, Loss: 2.1904
Step 300, Loss: 2.1991
Epoch 30 Loss: 2.1898
Epoch 31/100
Step 20, Loss: 2.1819
Step 40, Loss: 2.2436
Step 60, Loss: 2.2849
Step 80, Loss: 2.2923
Step 100, Loss: 2.2382
Step 120, Loss: 2.2411
Step 140, Loss: 2.2402
Step 160, Loss: 2.1929
Step 180, Loss: 2.1900
Step 200, Loss: 2.2032
Step 220, Loss: 2.2033
Step 240, Loss: 2.1757
Step 260, Loss: 2.1867
Step 280, Loss: 2.1893
Step 300, Loss: 2.1981
Epoch 31 Loss: 2.1887
Epoch 32/100
Step 20, Loss: 2.1809
Step 40, Loss: 2.2426
Step 60, Loss: 2.2839
Step 80, Loss: 2.2913
Step 100, Loss: 2.2371
Step 120, Loss: 2.2400
Step 140, Loss: 2.2392
Step 160, Loss: 2.1918
Step 180, Loss: 2.1890
Step 200, Loss: 2.2022
Step 220, Loss: 2.2023
Step 240, Loss: 2.1747
Step 260, Loss: 2.1857
Step 280, Loss: 2.1883
Step 300, Loss: 2.1970
Epoch 32 Loss: 2.1877
Epoch 33/100
Step 20, Loss: 2.1800
Step 40, Loss: 2.2416
Step 60, Loss: 2.2829
Step 80, Loss: 2.2903
Step 100, Loss: 2.2361
Step 120, Loss: 2.2390
Step 140, Loss: 2.2381
Step 160, Loss: 2.1908
Step 180, Loss: 2.1879
Step 200, Loss: 2.2011
Step 220, Loss: 2.2013
Step 240, Loss: 2.1737
Step 260, Loss: 2.1847
Step 280, Loss: 2.1873
Step 300, Loss: 2.1960
Epoch 33 Loss: 2.1867
Epoch 34/100
Step 20, Loss: 2.1790
Step 40, Loss: 2.2406
Step 60, Loss: 2.2819
Step 80, Loss: 2.2893
Step 100, Loss: 2.2351
Step 120, Loss: 2.2380
Step 140, Loss: 2.2371
Step 160, Loss: 2.1898
Step 180, Loss: 2.1869
Step 200, Loss: 2.2001
Step 220, Loss: 2.2002
Step 240, Loss: 2.1727
Step 260, Loss: 2.1836
Step 280, Loss: 2.1862
Step 300, Loss: 2.1950
Epoch 34 Loss: 2.1856
Epoch 35/100
Step 20, Loss: 2.1781
Step 40, Loss: 2.2396
Step 60, Loss: 2.2809
Step 80, Loss: 2.2883
Step 100, Loss: 2.2340
Step 120, Loss: 2.2369
Step 140, Loss: 2.2360
Step 160, Loss: 2.1888
Step 180, Loss: 2.1859
Step 200, Loss: 2.1991
Step 220, Loss: 2.1992
Step 240, Loss: 2.1717
Step 260, Loss: 2.1826
Step 280, Loss: 2.1852
Step 300, Loss: 2.1939
Epoch 35 Loss: 2.1846
Epoch 36/100
Step 20, Loss: 2.1771
Step 40, Loss: 2.2386
Step 60, Loss: 2.2798
Step 80, Loss: 2.2872
Step 100, Loss: 2.2330
Step 120, Loss: 2.2359
Step 140, Loss: 2.2350
Step 160, Loss: 2.1877
Step 180, Loss: 2.1849
Step 200, Loss: 2.1981
Step 220, Loss: 2.1982
Step 240, Loss: 2.1706
Step 260, Loss: 2.1816
Step 280, Loss: 2.1842
Step 300, Loss: 2.1929
Epoch 36 Loss: 2.1836
Epoch 37/100
Step 20, Loss: 2.1761
Step 40, Loss: 2.2377
Step 60, Loss: 2.2788
Step 80, Loss: 2.2862
Step 100, Loss: 2.2320
Step 120, Loss: 2.2349
Step 140, Loss: 2.2340
Step 160, Loss: 2.1867
Step 180, Loss: 2.1838
Step 200, Loss: 2.1970
Step 220, Loss: 2.1972
Step 240, Loss: 2.1696
Step 260, Loss: 2.1806
Step 280, Loss: 2.1832
Step 300, Loss: 2.1919
Epoch 37 Loss: 2.1826
Epoch 38/100
Step 20, Loss: 2.1752
Step 40, Loss: 2.2367
Step 60, Loss: 2.2779
Step 80, Loss: 2.2852
Step 100, Loss: 2.2309
Step 120, Loss: 2.2339
Step 140, Loss: 2.2329
Step 160, Loss: 2.1857
Step 180, Loss: 2.1828
Step 200, Loss: 2.1960
Step 220, Loss: 2.1961
Step 240, Loss: 2.1686
Step 260, Loss: 2.1796
Step 280, Loss: 2.1821
Step 300, Loss: 2.1908
Epoch 38 Loss: 2.1815
Epoch 39/100
Step 20, Loss: 2.1742
Step 40, Loss: 2.2357
Step 60, Loss: 2.2768
Step 80, Loss: 2.2842
Step 100, Loss: 2.2299
Step 120, Loss: 2.2329
Step 140, Loss: 2.2319
Step 160, Loss: 2.1847
Step 180, Loss: 2.1818
Step 200, Loss: 2.1950
Step 220, Loss: 2.1951
Step 240, Loss: 2.1676
Step 260, Loss: 2.1785
Step 280, Loss: 2.1811
Step 300, Loss: 2.1898
Epoch 39 Loss: 2.1805
Epoch 40/100
Step 20, Loss: 2.1733
Step 40, Loss: 2.2347
Step 60, Loss: 2.2758
Step 80, Loss: 2.2832
Step 100, Loss: 2.2289
Step 120, Loss: 2.2318
Step 140, Loss: 2.2309
Step 160, Loss: 2.1837
Step 180, Loss: 2.1808
Step 200, Loss: 2.1940
Step 220, Loss: 2.1941
Step 240, Loss: 2.1666
Step 260, Loss: 2.1775
Step 280, Loss: 2.1801
Step 300, Loss: 2.1888
Epoch 40 Loss: 2.1795
Epoch 41/100
Step 20, Loss: 2.1723
Step 40, Loss: 2.2337
Step 60, Loss: 2.2749
Step 80, Loss: 2.2822
Step 100, Loss: 2.2279
Step 120, Loss: 2.2308
Step 140, Loss: 2.2298
Step 160, Loss: 2.1826
Step 180, Loss: 2.1798
Step 200, Loss: 2.1930
Step 220, Loss: 2.1931
Step 240, Loss: 2.1656
Step 260, Loss: 2.1765
Step 280, Loss: 2.1791
Step 300, Loss: 2.1878
Epoch 41 Loss: 2.1785
Epoch 42/100
Step 20, Loss: 2.1714
Step 40, Loss: 2.2327
Step 60, Loss: 2.2739
Step 80, Loss: 2.2812
Step 100, Loss: 2.2268
Step 120, Loss: 2.2298
Step 140, Loss: 2.2288
Step 160, Loss: 2.1816
Step 180, Loss: 2.1787
Step 200, Loss: 2.1920
Step 220, Loss: 2.1921
Step 240, Loss: 2.1646
Step 260, Loss: 2.1755
Step 280, Loss: 2.1781
Step 300, Loss: 2.1868
Epoch 42 Loss: 2.1775
Epoch 43/100
Step 20, Loss: 2.1705
Step 40, Loss: 2.2318
Step 60, Loss: 2.2729
Step 80, Loss: 2.2802
Step 100, Loss: 2.2258
Step 120, Loss: 2.2288
Step 140, Loss: 2.2278
Step 160, Loss: 2.1806
Step 180, Loss: 2.1777
Step 200, Loss: 2.1909
Step 220, Loss: 2.1911
Step 240, Loss: 2.1636
Step 260, Loss: 2.1745
Step 280, Loss: 2.1770
Step 300, Loss: 2.1857
Epoch 43 Loss: 2.1764
Epoch 44/100
Step 20, Loss: 2.1695
Step 40, Loss: 2.2308
Step 60, Loss: 2.2719
Step 80, Loss: 2.2792
Step 100, Loss: 2.2248
Step 120, Loss: 2.2278
Step 140, Loss: 2.2268
Step 160, Loss: 2.1796
Step 180, Loss: 2.1767
Step 200, Loss: 2.1899
Step 220, Loss: 2.1900
Step 240, Loss: 2.1626
Step 260, Loss: 2.1735
Step 280, Loss: 2.1760
Step 300, Loss: 2.1847
Epoch 44 Loss: 2.1754
Epoch 45/100
Step 20, Loss: 2.1686
Step 40, Loss: 2.2298
Step 60, Loss: 2.2709
Step 80, Loss: 2.2782
Step 100, Loss: 2.2238
Step 120, Loss: 2.2268
Step 140, Loss: 2.2257
Step 160, Loss: 2.1786
Step 180, Loss: 2.1757
Step 200, Loss: 2.1889
Step 220, Loss: 2.1890
Step 240, Loss: 2.1616
Step 260, Loss: 2.1725
Step 280, Loss: 2.1750
Step 300, Loss: 2.1837
Epoch 45 Loss: 2.1744
Epoch 46/100
Step 20, Loss: 2.1677
Step 40, Loss: 2.2288
Step 60, Loss: 2.2699
Step 80, Loss: 2.2772
Step 100, Loss: 2.2228
Step 120, Loss: 2.2258
Step 140, Loss: 2.2247
Step 160, Loss: 2.1776
Step 180, Loss: 2.1747
Step 200, Loss: 2.1879
Step 220, Loss: 2.1880
Step 240, Loss: 2.1606
Step 260, Loss: 2.1715
Step 280, Loss: 2.1740
Step 300, Loss: 2.1827
Epoch 46 Loss: 2.1734
Epoch 47/100
Step 20, Loss: 2.1667
Step 40, Loss: 2.2279
Step 60, Loss: 2.2689
Step 80, Loss: 2.2761
Step 100, Loss: 2.2218
Step 120, Loss: 2.2248
Step 140, Loss: 2.2237
Step 160, Loss: 2.1766
Step 180, Loss: 2.1737
Step 200, Loss: 2.1869
Step 220, Loss: 2.1870
Step 240, Loss: 2.1596
Step 260, Loss: 2.1705
Step 280, Loss: 2.1730
Step 300, Loss: 2.1817
Epoch 47 Loss: 2.1724
Epoch 48/100
Step 20, Loss: 2.1658
Step 40, Loss: 2.2269
Step 60, Loss: 2.2680
Step 80, Loss: 2.2752
Step 100, Loss: 2.2208
Step 120, Loss: 2.2238
Step 140, Loss: 2.2227
Step 160, Loss: 2.1756
Step 180, Loss: 2.1727
Step 200, Loss: 2.1859
Step 220, Loss: 2.1860
Step 240, Loss: 2.1586
Step 260, Loss: 2.1695
Step 280, Loss: 2.1720
Step 300, Loss: 2.1807
Epoch 48 Loss: 2.1714
Epoch 49/100
Step 20, Loss: 2.1649
Step 40, Loss: 2.2259
Step 60, Loss: 2.2670
Step 80, Loss: 2.2742
Step 100, Loss: 2.2198
Step 120, Loss: 2.2228
Step 140, Loss: 2.2217
Step 160, Loss: 2.1746
Step 180, Loss: 2.1717
Step 200, Loss: 2.1849
Step 220, Loss: 2.1850
Step 240, Loss: 2.1576
Step 260, Loss: 2.1685
Step 280, Loss: 2.1710
Step 300, Loss: 2.1797
Epoch 49 Loss: 2.1704
Epoch 50/100
Step 20, Loss: 2.1639
Step 40, Loss: 2.2250
Step 60, Loss: 2.2660
Step 80, Loss: 2.2732
Step 100, Loss: 2.2188
Step 120, Loss: 2.2218
Step 140, Loss: 2.2207
Step 160, Loss: 2.1736
Step 180, Loss: 2.1707
Step 200, Loss: 2.1839
Step 220, Loss: 2.1840
Step 240, Loss: 2.1566
Step 260, Loss: 2.1675
Step 280, Loss: 2.1700
Step 300, Loss: 2.1787
Epoch 50 Loss: 2.1694
Epoch 51/100
Step 20, Loss: 2.1630
Step 40, Loss: 2.2240
Step 60, Loss: 2.2650
Step 80, Loss: 2.2722
Step 100, Loss: 2.2178
Step 120, Loss: 2.2208
Step 140, Loss: 2.2197
Step 160, Loss: 2.1726
Step 180, Loss: 2.1697
Step 200, Loss: 2.1829
Step 220, Loss: 2.1830
Step 240, Loss: 2.1556
Step 260, Loss: 2.1665
Step 280, Loss: 2.1690
Step 300, Loss: 2.1777
Epoch 51 Loss: 2.1684
Epoch 52/100
Step 20, Loss: 2.1621
Step 40, Loss: 2.2231
Step 60, Loss: 2.2641
Step 80, Loss: 2.2712
Step 100, Loss: 2.2168
Step 120, Loss: 2.2198
Step 140, Loss: 2.2187
Step 160, Loss: 2.1716
Step 180, Loss: 2.1687
Step 200, Loss: 2.1819
Step 220, Loss: 2.1820
Step 240, Loss: 2.1546
Step 260, Loss: 2.1655
Step 280, Loss: 2.1680
Step 300, Loss: 2.1767
Epoch 52 Loss: 2.1674
Epoch 53/100
Step 20, Loss: 2.1611
Step 40, Loss: 2.2221
Step 60, Loss: 2.2631
Step 80, Loss: 2.2702
Step 100, Loss: 2.2158
Step 120, Loss: 2.2188
Step 140, Loss: 2.2176
Step 160, Loss: 2.1706
Step 180, Loss: 2.1677
Step 200, Loss: 2.1809
Step 220, Loss: 2.1810
Step 240, Loss: 2.1536
Step 260, Loss: 2.1645
Step 280, Loss: 2.1670
Step 300, Loss: 2.1757
Epoch 53 Loss: 2.1664
Epoch 54/100
Step 20, Loss: 2.1602
Step 40, Loss: 2.2211
Step 60, Loss: 2.2621

In [13]:
# save new checkpoint
torch.save({
    "model_state": model.state_dict(),
    "optimizer_state": optimizer.state_dict()
}, "model_checkpoint_500_epochs.pth")

# Model
This is decent for a self trained model. The State of art models have a loss of 1 after training. For a self trained model, loss of 2-3 is decent and will be able to tell the similarities between most words.

Also keep in mind that most embeddings are significantly larger going upto 1000 embedding dimensions. Our model has only 60 embedding dimensions.

In [15]:
checkpoint = torch.load("model_checkpoint_500_epochs.pth", map_location="cuda" if torch.cuda.is_available() else "cpu")

model = ANN()
model.load_state_dict(checkpoint["model_state"])  # use the right key
model.eval()

ANN(
  (fc1): Linear(in_features=5000, out_features=60, bias=True)
  (relu): ReLU()
  (fc2): Linear(in_features=60, out_features=5000, bias=True)
)

In [17]:
embedding_matrix = model.fc2.weight.data.clone().cpu().numpy()

In [18]:
embedding_matrix.shape

(5000, 60)

# Extracting Vectors
Now that we have the Weights of the trained model. We can go ahead and extract the Vectors for each word in our vocabulary.

All the weights leading up to each of the neurons from the hidden layer when arranged in order make up the word vector of that word.

In [19]:
df_embeddings = pd.DataFrame(embedding_matrix)

In [20]:
df_embeddings.head()

,0,1,2,3,4,5,6,7,8,9,...,50,51,52,53,54,55,56,57,58,59
0,0.035566,-0.280325,-0.209905,0.092727,-0.512841,-0.070271,0.017452,-0.073750,-0.246000,-0.034664,...,-0.229457,0.116644,-0.187131,-0.380852,-0.201888,-0.175198,0.051587,-0.059986,0.081284,-0.065884
1,-0.366226,0.445310,-0.370340,-0.565965,0.480987,0.388533,-0.032340,-0.365572,0.032613,0.283541,...,-0.502574,-0.020204,-0.924985,-0.322606,-0.402044,0.259014,0.882215,-0.163126,-0.626576,-0.516701
2,0.258176,-0.317606,0.196751,0.285550,-0.025030,-0.829887,-0.403331,0.248189,-0.258676,0.206602,...,-1.072994,0.137963,-0.395314,0.433717,-0.032723,0.322714,0.758324,0.188737,0.398276,-1.168513
3,0.498756,0.103553,-0.771941,-0.639479,0.631630,0.101978,-0.631072,-0.583583,0.081321,-0.668437,...,0.117473,-1.194255,-0.275528,-0.327657,-0.742398,0.609596,-0.027341,0.566738,0.826060,-0.184296
4,-0.446127,0.729279,-0.294486,0.385511,0.426112,-0.633729,0.385096,0.600576,0.476241,0.169516,...,-1.250619,-0.297400,-0.017004,-0.843019,-0.027971,-0.229272,0.085112,0.341840,-0.174408,0.065009

In [30]:
# Labeling all the word vectors with their respective word
df_embeddings.insert(0, "word", vocabulary)

In [31]:
# Tweaking a few settings to display the embeddings better
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.width', 1000)
pd.set_option('display.precision', 6)

print(df_embeddings.head(10))

   word         0         1         2         3         4         5         6         7         8         9        10        11        12        13        14        15        16        17        18        19        20        21        22        23        24        25        26        27        28        29        30        31        32        33        34        35        36        37        38        39        40        41        42        43        44        45        46        47        48        49        50        51        52        53        54        55        56        57        58        59
0   the  0.035566 -0.280325 -0.209905  0.092727 -0.512841 -0.070271  0.017452 -0.073750 -0.246000 -0.034664 -0.240868  0.028574 -0.095689 -0.298459 -0.177851 -0.097263 -0.297415  0.075913  0.372466 -0.034589 -0.123280 -0.149911 -0.133922 -0.085907  0.010811 -0.168051  0.136708 -0.083664  0.012976 -0.026008 -0.056302 -0.039275  0.056458 -0.127233 -0.252066 -0.004904 -0.250311 -0.123614 -0.031560 -0.149700 -0.179112 -0.138432 -0.148120 -0.203050  0.029704 -0.027943 -0.171329  0.118392 -0.211683  0.001926 -0.229457  0.116644 -0.187131 -0.380852 -0.201888 -0.175198  0.051587 -0.059986  0.081284 -0.065884
1    of -0.366226  0.445310 -0.370340 -0.565965  0.480987  0.388533 -0.032340 -0.365572  0.032613  0.283541 -0.840285 -1.122674  0.051016 -0.042802  0.264012  0.002017 -0.589278  0.179929 -1.261623 -0.629037 -0.662668 -0.276622  0.305538 -0.343552 -0.284149 -0.586194  0.537332  0.122860 -0.844931  0.287202 -0.062298  0.044292 -0.319196  0.367778  0.472045 -0.078016 -0.595259  0.234546  0.330489 -0.313387 -0.384486 -0.735237 -0.793895 -0.125173  0.065045  0.260204 -0.222202  0.109011 -0.044340  0.052781 -0.502574 -0.020204 -0.924985 -0.322606 -0.402044  0.259014  0.882215 -0.163126 -0.626576 -0.516701
2   and  0.258176 -0.317606  0.196751  0.285550 -0.025030 -0.829887 -0.403331  0.248189 -0.258676  0.206602  0.555964  0.214666 -0.018353  0.162818  0.372046 -0.207097 -0.578365  0.199103  0.017821 -0.562081  0.284685 -0.451069  0.238290 -0.537023  0.144623 -0.750661 -0.552808 -0.236792 -0.565083 -0.470057 -0.537959  0.480946  0.379524  0.734522 -0.240615 -0.405468 -0.532866 -0.488267  0.027755 -0.550254 -1.002360 -0.806003 -0.093736  0.495837  0.149675 -0.980456 -0.419500 -0.464179 -1.113891 -1.056614 -1.072994  0.137963 -0.395314  0.433717 -0.032723  0.322714  0.758324  0.188737  0.398276 -1.168513
3    in  0.498756  0.103553 -0.771941 -0.639479  0.631630  0.101978 -0.631072 -0.583583  0.081321 -0.668437 -0.464269  0.250039  0.228771 -0.215779 -0.245870 -0.980918 -0.838673 -0.339986 -0.683339  0.147878 -1.229988  0.217598 -0.470991 -1.015271  0.522729 -0.125340  0.200042 -0.296030  0.128503 -0.014328 -0.243619 -0.618091  0.252277 -0.202341 -0.221886 -0.354817  0.169384  0.183302  0.321711 -0.800282 -1.275065  0.408455 -0.165669  0.354993 -0.319238  0.489131  0.299561 -0.379014  0.124474 -0.770374  0.117473 -1.194255 -0.275528 -0.327657 -0.742398  0.609596 -0.027341  0.566738  0.826060 -0.184296
4    to -0.446127  0.729279 -0.294486  0.385511  0.426112 -0.633729  0.385096  0.600576  0.476241  0.169516 -0.023021  0.224911  0.209699 -0.031109 -0.203644 -1.293571 -0.123569 -0.343024  0.586215 -0.084507  0.268031 -0.368318 -0.705220 -0.639901 -0.368106 -0.171593 -1.601744 -1.191569 -0.795679 -0.627572  0.562761 -0.144540 -0.496805  0.285294  0.500474 -0.029703 -0.599288 -0.212433  0.080489  0.089492 -1.234285  0.102755 -0.612636 -0.380699 -1.195763  0.592998 -0.148800 -1.247983  0.142657  0.531576 -1.250619 -0.297400 -0.017004 -0.843019 -0.027971 -0.229272  0.085112  0.341840 -0.174408  0.065009
5     a  0.521334 -0.374286  0.284715  0.743717 -0.324918 -0.416449 -0.775560 -0.014389  0.320896 -0.872533  0.430116 -0.281140  0.083962 -0.844921 -0.024829 -0.239429  0.398935 -0.347814 -0.062053 -0.140130 -0.534257  0.307225  0.716195 -0.178832 -1.164543 -0.052588 -0.001870  0.190817 -0.799922  0.285387  0.086505 -0.050744 -0.705507 -0.090674 -1.687082 -0.327707 -0.667211  0.029952  0.511346 -0.271109 -0.693686  0.670320 -0.105816 -0.207848 -1.216202 -0.321674 -0.658962 -0.062614 -0.038745  0.375752 -0.101478  0.239476 -0.765449 -1.060077 -0.033872 -0.002629  0.683523 -0.777550  0.194857 -0.641632
6   was -0.012309 -0.885510 -0.621333  0.275095  0.411241 -0.139419 -1.100932  0.393077 -0.408765 -0.779750  0.192385  0.471135 -0.851175  0.351778  0.623557  0.278711  0.417480  0.570244 -0.476918  0.025710 -0.170134 -0.342856  0.331256 -0.812267  0.203394 -0.367500 -1.361859  0.336768  0.000521  0.252636  0.008675 -0.578521 -0.166230 -0.517807 -0.309606  0.154317 -0.420097 -0.273306  0.137716 -1.172925 -0.677961 -0.221432 -0.121567 -0.307826  0.207655  0.951301  0.385771 -0.011209 -0.715089 -0.318525 -0.427291 -0.357149 -0.439321  0.265056 -0.204899 -0.891801 -0.546542 -1.298522 -1.271593  0.240047
7    on  0.331726  0.144703  0.654507  0.604134  0.564236  0.340955 -0.567484 -0.703897 -0.632594  0.758921 -0.430679  0.441873 -0.072520 -0.176215 -0.473795 -0.544589 -0.710452 -0.274742 -1.093064 -0.018762 -0.992940 -0.000190 -0.769733 -1.693760 -1.220313 -0.730855 -1.289846 -0.061321  0.716813 -0.018002  1.004808 -0.248656  0.597104 -0.379482  0.538895  0.210795 -0.784430 -0.081802 -1.292011 -0.169271 -0.015987 -0.731282  0.001046 -1.387390  0.128741 -0.719787 -0.893042 -0.132826 -0.848799 -0.496904  0.328748  0.387963 -0.238639 -0.731827 -0.284884  0.576624 -0.228176  0.027786  0.341780 -0.226465
8    as  0.596970 -1.022499  0.251411 -0.546640  0.430551  0.315682  0.484514  0.170179  0.124608 -1.525412 -0.118573 -1.171378 -0.700909 -0.768254  0.251060 -0.048275  0.380153  0.356974 -0.443071 -1.228655  0.194131 -0.747080 -0.791843 -0.097974 -0.024826 -0.201827 -0.863124 -0.735710 -0.100106 -0.855419  0.395859 -0.085654 -0.121381  0.202119  0.773440 -0.013450  0.488684 -0.024115 -1.950063  0.021607 -0.848162 -0.555074 -0.030219  0.075107 -0.632354 -0.657064  0.594882 -0.966912  0.168832  0.682019 -0.114044  0.877839 -1.875391 -0.153198 -0.960333  0.104503  0.160082 -0.094115 -0.712100 -0.295993
9  that -0.146570  0.442615  0.685971 -0.910981 -0.076481 -0.500526 -1.081785  0.333250  0.125048 -1.015893  0.392040 -0.919360  0.563399 -0.216382 -1.016283 -0.225053 -0.388285 -0.151915  0.070265  0.139174  0.252969 -0.097608 -0.979806 -0.052310 -1.112522 -0.865485  0.426583 -1.214789  0.163003 -0.703904 -0.282662 -0.823329  0.161542 -0.687853 -0.497111 -0.285461 -0.948541 -0.417935  0.699811  0.320134  0.322548  0.396590  0.192608 -0.270896 -0.306962  0.993953  0.350655  0.036566 -1.101940 -0.497785 -1.181258  0.999094 -0.672774 -0.172620 -1.024141  0.641005 -0.131580 -0.493935 -0.323418  0.116707

In [32]:
# Saving the model
pd.to_pickle(df_embeddings, "embeddings_final.pkl")

# Evaluation

We can now see if our very primitive model can capture relationships between words based off their ouccerence.

We could do this in multiple ways:
- Running a KNN algorithm to see which words are closer
- Running similarity tests based off Cosine Similarity


We opt for the second option because KNNs hallucinate when the number of dimensions are too high.

In [33]:
df_embeddings = pd.read_pickle('embeddings_final.pkl')

In [34]:
import torch
import torch.nn.functional as F

def get_vector(word, df):
    row = df[df["word"] == word]
    if row.empty:
        raise ValueError(f"Word '{word}' not in vocabulary")
    vec = torch.tensor(row.iloc[:, 1:].values, dtype=torch.float32).squeeze(0)
    return vec

def most_similar(word, df, topn=10):
    target_vec = get_vector(word, df)
    all_words = df["word"].values
    all_vecs = torch.tensor(df.iloc[:, 1:].values, dtype=torch.float32)

    # Compute cosine similarity with all words
    sims = F.cosine_similarity(target_vec.unsqueeze(0), all_vecs)

    # Sort and pick top-N (skip self at index of the word itself)
    topk = torch.topk(sims, topn + 1)  # +1 because we include the word itself
    results = []
    for idx, score in zip(topk.indices, topk.values):
        w = all_words[idx]
        if w != word:  # skip the same word
            results.append((w, score.item()))
        if len(results) == topn:
            break

    return results

In [38]:
word = "war"
neighbors = most_similar(word, df_embeddings, topn=2)
print(f"Most similar to '{word}':")
for w, s in neighbors:
    print(f"{w}: {s:.4f}")

Most similar to 'war':
vichy: 0.6170
conflict: 0.6149

In [37]:
word = "music"
neighbors = most_similar(word, df_embeddings, topn=2)
print(f"Most similar to '{word}':")
for w, s in neighbors:
    print(f"{w}: {s:.4f}")

Most similar to 'music':
soundtrack: 0.6731
aerial: 0.6603

In [51]:
word = "london"
neighbors = most_similar(word, df_embeddings, topn=3)
print(f"Most similar to '{word}':")
for w, s in neighbors:
    print(f"{w}: {s:.4f}")

Most similar to 'london':
hampton: 0.5774
community: 0.5736
connecticut: 0.5712